// GENERATED section registry chunk 6 — see sections/registry.tsx. One data row per section: title, sub, component.
import type { SectionEntry } from './registry';
import { BoyerMooreSection } from '../BoyerMooreSection';
import { SyscallSection } from '../SyscallSection';
import { GcSection } from '../GcSection';
import { ContainerSection } from '../ContainerSection';
import { DebuggerSection } from '../DebuggerSection';
import { NewtonSection } from '../NewtonSection';
import { CowSection } from '../CowSection';
import { MtfSection } from '../MtfSection';
import { CdcSection } from '../CdcSection';
import { RsyncSection } from '../RsyncSection';
import { TlbSection } from '../TlbSection';
import { NumaSection } from '../NumaSection';
import { BuddyAllocSection } from '../BuddyAllocSection';
import { TimingWheelSection } from '../TimingWheelSection';
import { EpollSection } from '../EpollSection';
import { FutexSection } from '../FutexSection';
import { RcuSection } from '../RcuSection';
import { AbaSection } from '../AbaSection';
import { SeqlockSection } from '../SeqlockSection';
import { IoUringSection } from '../IoUringSection';
import { BakerySection } from '../BakerySection';
import { SuffixArraySection } from '../SuffixArraySection';
import { ManacherSection } from '../ManacherSection';
import { ZalgoSection } from '../ZalgoSection';
import { FftSection } from '../FftSection';
import { SsrfSection } from '../SsrfSection';
import { XxeSection } from '../XxeSection';
import { DnsRebindSection } from '../DnsRebindSection';
import { ArpSpoofSection } from '../ArpSpoofSection';
import { ProtoPolluteSection } from '../ProtoPolluteSection';
import { SagaSection } from '../SagaSection';
import { BlindSigSection } from '../BlindSigSection';
import { VrfSection } from '../VrfSection';
import { OtSection } from '../OtSection';
import { PaillierSection } from '../PaillierSection';
import { ElGamalSection } from '../ElGamalSection';
import { ClickjackSection } from '../ClickjackSection';
import { HstsSection } from '../HstsSection';
import { OpenRedirectSection } from '../OpenRedirectSection';
import { HashFloodSection } from '../HashFloodSection';
import { RedosSection } from '../RedosSection';
import { SubdomainTakeoverSection } from '../SubdomainTakeoverSection';
import { BgpRrSection } from '../BgpRrSection';
import { RouteFlapSection } from '../RouteFlapSection';

export const chunk6: Record<string, SectionEntry> = {
  "boyermoore": { Component: BoyerMooreSection, title: <>Boyer-Moore string search</>, sub: <>The matcher that gets faster on longer patterns by skipping ahead. Comparing from the right end, a mismatch slides the pattern forward by the bad-character rule — often leaping several characters, or a whole pattern length when the text character isn't in the pattern at all. Step through it and watch the comparisons stay far below a naive scan.</> },
  "newton": { Component: NewtonSection, title: <>Newton's method</>, sub: <>Find where a function crosses zero by following its tangent. From a guess, the tangent line's x-intercept becomes the next guess — homing in on the root with quadratic convergence, the correct digits roughly doubling each step. Step through it and watch a handful of iterations reach machine precision.</> },
  "cow": { Component: CowSection, title: <>Copy-on-write fork</>, sub: <>Why fork() is cheap even for a process using gigabytes. Instead of copying memory up front, the child shares the parent's pages read-only; only a write to a shared page faults and copies that one page. Fork, then write pages and watch them diverge — or exec the child and watch nothing get copied at all.</> },
  "mtf": { Component: MtfSection, title: <>Move-to-front coding</>, sub: <>The stage between the Burrows-Wheeler transform and the entropy coder in bzip2. Keep a list of the alphabet; encode each symbol as its current index, then move it to the front — so a run of the same character collapses into a run of zeros, the small-number stream that makes the BWT so compressible.</> },
  "cdc": { Component: CdcSection, title: <>Content-defined chunking &amp; dedup</>, sub: <>How rsync, restic and ZFS avoid re-sending data that barely changed. Split a file into chunks and store each only once — but cut in the wrong place and a one-byte edit shifts every boundary, so nothing dedupes. Edit the text and watch fixed-size chunking turn entirely "new" while content-defined boundaries, set by a rolling hash, keep almost every chunk reusable.</> },
  "rsync": { Component: RsyncSection, title: <>rsync — delta file sync</>, sub: <>Sync a changed file to a remote copy by sending only the differences — without either side seeing the other's data first. The receiver sends block checksums of its old file; the sender rolls a window over the new file, matching whole blocks by a checksum it updates one byte at a time, and emits a delta of copy-references and literal runs. Because it searches at every offset, an insertion near the start doesn't ruin the rest — the window re-aligns. Edit the files and watch the delta.</> },
  "tlb": { Component: TlbSection, title: <>The TLB (translation lookaside buffer)</>, sub: <>The cache that makes virtual memory fast by avoiding the page-table walk. A loop touches a working set of pages; step through it and watch hits resolve in a cycle while misses pay for the walk. Drag the working set past the TLB size and watch the hit rate fall off a cliff — thrashing.</> },
  "numa": { Component: NumaSection, title: <>NUMA &amp; first-touch placement</>, sub: <>On a multi-socket machine, memory has an address AND a home node — and a core pays extra to reach another node's RAM. Linux places a page on the node of the core that first writes it, so initializing a big array from one thread pins it all to one socket. Switch between serial, parallel, and interleaved init and watch the accesses turn local or cross the interconnect.</> },
  "buddyalloc": { Component: BuddyAllocSection, title: <>Buddy allocator</>, sub: <>How the Linux kernel's page allocator hands out and reclaims memory: every block is a power of two, a request rounds up and splits a larger free block in half until it fits, and freeing a block instantly coalesces with its "buddy" (at offset XOR size) back into a larger block. Allocate and free, and watch splitting, coalescing, and fragmentation happen live.</> },
  "gc": { Component: GcSection, title: <>How garbage collection works</>, sub: <>In a managed language you never call free() — so the runtime finds the dead objects itself. A narrated walk through tracing mark-and-sweep: start from the roots, mark everything reachable, free the rest, and see why this collects reference cycles that simple reference counting would leak forever. Drop a reference and run the collector on a live object graph.</> },
  "timingwheel": { Component: TimingWheelSection, title: <>Timing wheel</>, sub: <>How systems that manage millions of timers (the Linux kernel, Kafka, Netty) schedule them in O(1) instead of a heap's O(log n). A circular array of buckets and a hand that advances one tick at a time; a timer for "d ticks from now" drops straight into bucket (current + d) mod N — no sorting. Schedule timers and tick the hand around to watch them fire, with a rounds counter for delays beyond one revolution.</> },
  "epoll": { Component: EpollSection, title: <>epoll &amp; the C10k problem</>, sub: <>How one thread watches 10,000 sockets. select/poll re-scan every file descriptor on each call — O(n) even when one is active — the wall that capped servers at ~10k clients. epoll keeps a kernel ready-list and returns only fds with events: O(active). Drag the connection count to see the gap, then meet the edge-triggered gotcha that strands data if you don't drain fully.</> },
  "futex": { Component: FutexSection, title: <>futex — the fast userspace mutex</>, sub: <>Why a modern mutex is nearly free when uncontended. The lock word lives in userspace, so locking a free mutex or unlocking one with no waiters is a single atomic compare-and-swap — no system call. Only blocking on a held lock or waking a waiter traps into the kernel. Pick a workload and watch which operations stay in userspace and which pay for the kernel.</> },
  "syscall": { Component: SyscallSection, title: <>How a syscall enters the kernel</>, sub: <>The wall every program lives behind. A narrated walk across the user/kernel boundary: your ring-3 program loads a syscall number and arguments into registers, traps in with one instruction, the CPU switches to ring 0 and jumps to a fixed entry point, the kernel validates and does the privileged work, then returns you to ring 3 with the result. Step one read() across and back — and see why the mode switch is the cost futex and io_uring work to avoid.</> },
  "container": { Component: ContainerSection, title: <>How a container isolates a process</>, sub: <>A container is not a virtual machine — there is no guest OS. It is one ordinary process on the host kernel, given a private view of the system (namespaces) and a cap on resources (cgroups). A narrated walk through both, plus the image as its root filesystem. Toggle the PID namespace off and watch host processes become visible; set the memory limit too low and the cgroup OOM-kills it.</> },
  "breakpoint": { Component: DebuggerSection, title: <>How a debugger breakpoint works</>, sub: <>The surprising trick behind every breakpoint. Your code runs at full speed, so the debugger cannot watch each instruction — instead it overwrites one byte at the target address with 0xCC (the x86 INT3 opcode). When the CPU hits it, INT3 traps and SIGTRAP stops the process for the debugger to inspect via ptrace. A narrated walk plus a live step through set → trap → inspect → continue, watching the byte flip between 0xCC and the real instruction.</> },
  "rcu": { Component: RcuSection, title: <>RCU — Read-Copy-Update</>, sub: <>The Linux kernel's trick for near-free reads of shared data. Readers take no lock and never block; a writer copies the data, modifies the copy, and atomically publishes it — then waits out a grace period before freeing the old version, so no reader is ever left holding a freed pointer. Add readers, run writer updates, and watch old versions linger until their last reader leaves.</> },
  "aba": { Component: AbaSection, title: <>The ABA problem</>, sub: <>The subtle bug that makes lock-free programming hard. Compare-and-swap checks that a value is the same, not that it never changed — so if another thread cycles it A → B → A while you're preempted, your CAS is fooled into succeeding on a world that moved underneath it, splicing a freed node back into a stack. Toggle a plain CAS versus a versioned (tagged) CAS and watch one corrupt and the other stay safe.</> },
  "seqlock": { Component: SeqlockSection, title: <>The seqlock (sequence lock)</>, sub: <>How the kernel lets millions of readers per second read a multi-word value (like the clock) without locking or blocking — while a writer updates it. The writer brackets its update with an odd-then-even counter; a reader snapshots the counter, reads the data, and re-checks — retrying if the counter was odd or changed. Step through an interleaving and watch a naive read tear while the seqlock read retries; proven across all 70 interleavings.</> },
  "iouring": { Component: IoUringSection, title: <>io_uring — async I/O without the syscalls</>, sub: <>The modern Linux I/O interface that leaves epoll behind on syscall cost. You fill a shared submission ring with many requests and hand them to the kernel with one io_uring_enter; it does the I/O asynchronously and posts results to a completion ring you read with no syscall. Compare the syscall counts across models, then step the submission/completion ring loop.</> },
  "bakery": { Component: BakerySection, title: <>Lamport's bakery algorithm</>, sub: <>Mutual exclusion using only atomic reads and writes — no test-and-set, no hardware lock. Threads take a bakery ticket one higher than anyone waiting and are served lowest-number-first; since taking a number isn't atomic, ties can happen and are broken by thread id, giving a total order with exactly one winner. Choose how the threads arrive and watch who enters the critical section.</> },
  "suffixarray": { Component: SuffixArraySection, title: <>Suffix array</>, sub: <>A sorted index of every suffix of a string — the workhorse behind fast full-text search. Because the suffixes are sorted, all occurrences of a pattern form one contiguous block; type a pattern and watch that block (and the matching text positions) light up, found by binary search in O(m log n).</> },
  "manacher": { Component: ManacherSection, title: <>Manacher's algorithm — longest palindrome in O(n)</>, sub: <>Find the longest palindromic substring in linear time. The trick: interleave separators so even and odd palindromes look alike, then give every position a radius — and reuse the radii that mirror symmetry already guarantees, so new character comparisons only ever push the frontier right. Type a string and watch the radius bars and the palindrome it picks.</> },
  "zalgo": { Component: ZalgoSection, title: <>The Z-algorithm — linear-time string matching</>, sub: <>One elegant array finds every occurrence of a pattern in a text in linear time. Z[i] measures how much of the string's prefix reappears at position i; run it over "pattern § text" and every spot where Z ≥ |pattern| is a match. Type a pattern and text and watch the Z-values light up the matches — overlaps included.</> },
  "fft": { Component: FftSection, title: <>The Fast Fourier Transform</>, sub: <>Turn a signal between time (samples) and frequency (how much of each tone it contains), in O(n log n). Build a signal by mixing a few cosine frequencies and watch the FFT pull them back apart — a sharp peak at exactly each frequency you added. The same butterfly as the NTT, but over complex numbers.</> },
  "ssrf": { Component: SsrfSection, title: <>SSRF — server-side request forgery</>, sub: <>When an app fetches a URL you control, point it inward. The server sits inside a trusted network, so "fetch this image" becomes "fetch the cloud metadata endpoint" — and out come the IAM credentials (the Capital One breach). Toggle SSRF protection and watch the dangerous fetches get blocked.</> },
  "xxe": { Component: XxeSection, title: <>XXE — XML external entity injection</>, sub: <>XML lets a document define entities whose value is pulled from an external file or URL — so a parser that trusts attacker-uploaded XML will read /etc/passwd, fetch internal cloud metadata (SSRF), or blow up on self-referential entities (billion laughs DoS). It hides in SOAP, SAML, SVG, and DOCX uploads. Pick a variant, toggle the parser defenses, and see why disabling DTD processing is the one fix that stops them all.</> },
  "dnsrebind": { Component: DnsRebindSection, title: <>DNS rebinding</>, sub: <>A browser attack that bypasses the same-origin policy by flipping a domain's DNS from the attacker's IP to 127.0.0.1 after the page loads — so the attacker's JavaScript can read your router admin, cloud metadata, or localhost dev server. The same-origin policy trusts the hostname; packets follow the IP. Toggle the three defenses and watch which layer stops it.</> },
  "arpspoof": { Component: ArpSpoofSection, title: <>ARP spoofing (LAN MITM)</>, sub: <>The oldest man-in-the-middle trick on a local network. ARP has no authentication, so an attacker who announces "the gateway is at my MAC" poisons the victim's cache and reroutes all its traffic through themselves. Toggle static ARP entries, Dynamic ARP Inspection, and TLS, and watch the cache flip and the traffic get intercepted — or the defense that stops it.</> },
  "protopollute": { Component: ProtoPolluteSection, title: <>Prototype pollution</>, sub: <>How attacker JSON with a <code>__proto__</code> key can change the behavior of objects it never touched. A naive deep-merge follows <code>__proto__</code> onto JavaScript's shared prototype, so a brand-new empty object suddenly inherits the attacker's properties — an auth bypass hiding in plain sight. Edit the payload, toggle vulnerable vs safe merge, and watch a fresh <code>{'{}'}</code> become admin. (Sandboxed — never touches the real prototype.)</> },
  "saga": { Component: SagaSection, title: <>The Saga pattern</>, sub: <>How microservices pull off a "transaction" across services with separate databases — without holding distributed locks. A chain of local steps, each with a compensating undo; pick which step fails and watch the compensations fire in reverse for everything already committed, landing back in a consistent state.</> },
  "blindsig": { Component: BlindSigSection, title: <>RSA blind signatures</>, sub: <>Getting a valid signature on a message the signer never sees. The client blinds its message with a random factor; the signer signs the random-looking value blindly; the client divides the factor back out and is left with an ordinary signature that verifies — yet can't be linked to the signing session. The engine behind digital cash and Privacy Pass.</> },
  "vrf": { Component: VrfSection, title: <>Verifiable random function</>, sub: <>A coin only the key-holder can flip, yet everyone can verify. A seed becomes a pseudorandom output plus a proof; anyone with the public key confirms the output is the one true result for that seed — unpredictable in advance, impossible to cherry-pick. The primitive behind leaderless blockchain leader election (Algorand, Cardano) and DNSSEC NSEC5.</> },
  "ot": { Component: OtSection, title: <>Oblivious transfer</>, sub: <>The strange handshake at the root of secure computation: the sender holds two secrets, you take exactly one, and neither side learns what the other knows — you can't see the message you didn't pick, and the sender can't tell which you took. Choose a message and step the EGL exchange; watch your pick decrypt cleanly while the other branch comes out as garbage.</> },
  "paillier": { Component: PaillierSection, title: <>Paillier homomorphic encryption</>, sub: <>Add two encrypted numbers without ever decrypting them. Paillier is additively homomorphic — multiply two ciphertexts and the result decrypts to the sum of the plaintexts. Encrypt two values, multiply the ciphertexts, and watch a server compute your total without learning either input — the primitive behind private e-voting and encrypted aggregation.</> },
  "elgamal": { Component: ElGamalSection, title: <>ElGamal encryption</>, sub: <>Public-key encryption built on Diffie–Hellman: hide a message by multiplying it with a fresh shared secret only the private-key holder can rebuild. Encryption is randomized (the same message encrypts differently every time — semantic security) and multiplicatively homomorphic (multiply ciphertexts to multiply plaintexts). Encrypt, re-roll the randomness, and watch the homomorphism — with real modular arithmetic.</> },
  "clickjack": { Component: ClickjackSection, title: <>Clickjacking</>, sub: <>Tricking you into clicking something you can't see. A malicious page loads your bank in an invisible iframe and positions its real button under a decoy. Drag the reveal slider to expose the trick, then set the bank's framing policy and watch the browser refuse to load the frame at all.</> },
  "hsts": { Component: HstsSection, title: <>HSTS &amp; SSL stripping</>, sub: <>One header that forces https forever. Without it, a man-in-the-middle keeps you on plaintext and reads everything (sslstrip). With HSTS, the browser rewrites http→https itself before any request leaves — but only after it's seen the header once. Toggle the attacker, the recorded header, and the preload list to see exactly where the connection is safe and where the trust-on-first-use gap bites.</> },
  "openredirect": { Component: OpenRedirectSection, title: <>Open redirect &amp; URL-parsing tricks</>, sub: <>A link that starts on a trusted domain but lands on the attacker's — the engine of phishing and OAuth token theft. Type a redirect target and watch how a browser actually resolves it: a backslash becomes a slash, an @ hides the real host, a leading // is scheme-relative. See exactly which "looks like a path" payloads quietly escape the origin.</> },
  "hashflood": { Component: HashFloodSection, title: <>Hash flooding &amp; algorithmic-complexity DoS</>, sub: <>How an attacker turns a hash table's O(1) into O(n²) with nothing but chosen keys. If the hash is predictable, thousands of distinct keys can be made to collide in one bucket — every insert walks a growing chain and one request pins a CPU (the 2011 hashDoS). Flood the buckets, then switch to a seeded SipHash-style hash and watch the same attack scatter harmlessly.</> },
  "redos": { Component: RedosSection, title: <>ReDoS — catastrophic regex backtracking</>, sub: <>How one regular expression can hang a server. A backtracking engine faced with nested quantifiers like (a+)+ and an almost-matching input tries every way to split the input before failing — exponential work in the input length. Pick a pattern, drag the length, and watch the step count explode for an evil pattern while a safe one stays flat.</> },
  "subdomain": { Component: SubdomainTakeoverSection, title: <>Subdomain takeover</>, sub: <>How a forgotten DNS record hands an attacker a real page on your domain. You point a subdomain at a cloud service, later delete the service, but leave the CNAME dangling — and if the provider lets anyone claim the unused name, an attacker serves their content (and a valid TLS cert) from your subdomain. Toggle each resource live/deleted and watch which ones become takeover-able.</> },
  "bgprr": { Component: BgpRrSection, title: <>BGP route reflectors</>, sub: <>How iBGP scales past a few routers. A full mesh needs n(n-1)/2 sessions — 100 routers is ~5,000. A route reflector collapses that to a hub-and-spoke and relays routes between its clients. Drag the router count to watch the mesh explode, then inject routes to see the RFC 4456 reflection rules.</> },
  "routeflap": { Component: RouteFlapSection, title: <>BGP route flap damping</>, sub: <>How routers protect the internet from an unstable link that keeps flapping (a route repeatedly withdrawn and re-announced). Each route accrues a penalty (+1000 per flap) that decays with a 15-minute half-life; above the suppress threshold the route is withheld, and it returns only after decaying below a lower reuse threshold — a hysteresis gap that stops it oscillating. Pick a route's behaviour and watch the penalty rise, decay, and cross the thresholds.</> },
};
