// GENERATED section registry chunk 5 — see sections/registry.tsx. One data row per section: title, sub, component.
import type { SectionEntry } from './registry';
import { MemoryStorySection } from '../MemoryStorySection';
import { CpuCycleSection } from '../CpuCycleSection';
import { CompilerSection } from '../CompilerSection';
import { SsaSection } from '../SsaSection';
import { RegAllocSection } from '../RegAllocSection';
import { PeepholeSection } from '../PeepholeSection';
import { HindleySection } from '../HindleySection';
import { ShuntingYardSection } from '../ShuntingYardSection';
import { BytecodeSection } from '../BytecodeSection';
import { WasmSection } from '../WasmSection';
import { JitSection } from '../JitSection';
import { FloydSection } from '../FloydSection';
import { BellmanFordSection } from '../BellmanFordSection';
import { PageRankSection } from '../PageRankSection';
import { KMeansSection } from '../KMeansSection';
import { DbscanSection } from '../DbscanSection';
import { GmmSection } from '../GmmSection';
import { PcaSection } from '../PcaSection';
import { SvdSection } from '../SvdSection';
import { PerceptronSection } from '../PerceptronSection';
import { LogisticRegressionSection } from '../LogisticRegressionSection';
import { SvmSection } from '../SvmSection';
import { DecisionTreeSection } from '../DecisionTreeSection';
import { RandomForestSection } from '../RandomForestSection';
import { GradientBoostingSection } from '../GradientBoostingSection';
import { LeakyBucketSection } from '../LeakyBucketSection';
import { GcraSection } from '../GcraSection';
import { DramSection } from '../DramSection';
import { AdderSection } from '../AdderSection';
import { LatchSection } from '../LatchSection';
import { WallaceSection } from '../WallaceSection';
import { AluSection } from '../AluSection';
import { MemBusSection } from '../MemBusSection';
import { IoSection } from '../IoSection';
import { SsdSection } from '../SsdSection';
import { FlashCellSection } from '../FlashCellSection';
import { KeystrokeSection } from '../KeystrokeSection';
import { RaytraceSection } from '../RaytraceSection';
import { RasterizeSection } from '../RasterizeSection';
import { PerspectiveSection } from '../PerspectiveSection';
import { MsaaSection } from '../MsaaSection';
import { VerletSection } from '../VerletSection';
import { BarnesHutSection } from '../BarnesHutSection';
import { DoublePendulumSection } from '../DoublePendulumSection';
import { OrbitSection } from '../OrbitSection';
import { RayMarchSection } from '../RayMarchSection';
import { QuaternionSection } from '../QuaternionSection';
import { SystolicSection } from '../SystolicSection';
import { GpuSection } from '../GpuSection';
import { CpuCacheSection } from '../CpuCacheSection';
import { OooExecSection } from '../OooExecSection';
import { RopeSection } from '../RopeSection';
import { GapBufferSection } from '../GapBufferSection';
import { FastInvSqrtSection } from '../FastInvSqrtSection';
import { KahanSumSection } from '../KahanSumSection';
import { CordicSection } from '../CordicSection';
import { KaratsubaSection } from '../KaratsubaSection';
import { SimAnnealSection } from '../SimAnnealSection';
import { AlphaBetaSection } from '../AlphaBetaSection';
import { BackpropSection } from '../BackpropSection';
import { AttentionSection } from '../AttentionSection';
import { MoeSection } from '../MoeSection';
import { SpecDecodeSection } from '../SpecDecodeSection';
import { KvCacheSection } from '../KvCacheSection';
import { QuantizeSection } from '../QuantizeSection';
import { EmbeddingSection } from '../EmbeddingSection';
import { VectorSearchSection } from '../VectorSearchSection';
import { HammingSection } from '../HammingSection';
import { BresenhamSection } from '../BresenhamSection';
import { BezierSection } from '../BezierSection';
import { ConvexHullSection } from '../ConvexHullSection';
import { SatSection } from '../SatSection';
import { SpatialHashSection } from '../SpatialHashSection';
import { MarchSquaresSection } from '../MarchSquaresSection';
import { VoronoiSection } from '../VoronoiSection';
import { DelaunaySection } from '../DelaunaySection';
import { MontgomerySection } from '../MontgomerySection';
import { TwoSatSection } from '../TwoSatSection';
import { WfcSection } from '../WfcSection';
import { PerlinSection } from '../PerlinSection';
import { PoissonSection } from '../PoissonSection';
import { TransistorSection } from '../TransistorSection';
import { KnapsackSection } from '../KnapsackSection';
import { DeployStratSection } from '../DeployStratSection';
import { HealthCheckSection } from '../HealthCheckSection';
import { AutoscaleSection } from '../AutoscaleSection';
import { KubeSchedSection } from '../KubeSchedSection';
import { UslSection } from '../UslSection';
import { PidSection } from '../PidSection';
import { KalmanSection } from '../KalmanSection';
import { SloSection } from '../SloSection';
import { TracingSection } from '../TracingSection';
import { FeatureFlagSection } from '../FeatureFlagSection';
import { GracefulShutdownSection } from '../GracefulShutdownSection';
import { IdempotencySection } from '../IdempotencySection';
import { LoadShedSection } from '../LoadShedSection';
import { BulkheadSection } from '../BulkheadSection';
import { ChaosSection } from '../ChaosSection';
import { SingleFlightSection } from '../SingleFlightSection';
import { StridePrefetchSection } from '../StridePrefetchSection';
import { BranchlessSection } from '../BranchlessSection';
import { BranchPredictSection } from '../BranchPredictSection';
import { SpectreSection } from '../SpectreSection';
import { MeltdownSection } from '../MeltdownSection';
import { RowhammerSection } from '../RowhammerSection';
import { KillChainSection } from '../KillChainSection';

export const chunk5: Record<string, SectionEntry> = {
  "floyd": { Component: FloydSection, title: <>Floyd-Warshall all-pairs shortest paths</>, sub: <>Shortest paths between every pair of vertices in one cubic dynamic program. Step through the intermediate vertices and watch the distance matrix relax — each cell taking the cheaper of what it had and routing through the current waypoint. Handles negative edges, and flags a negative cycle.</> },
  "bellmanford": { Component: BellmanFordSection, title: <>Bellman-Ford &amp; arbitrage detection</>, sub: <>The shortest-path algorithm that survives negative edges — and detects the negative cycles where "shortest" breaks down. Step the relaxation passes to watch distances settle on a graph Dijkstra would get wrong, then turn the same machinery into a currency-arbitrage detector: model each rate as −ln(rate) and a profitable trading loop becomes a negative cycle.</> },
  "pagerank": { Component: PageRankSection, title: <>How Google first ranked the web (PageRank)</>, sub: <>Importance is recursive: a page is important if important pages link to it. Model a random surfer clicking links forever — a page’s PageRank is the fraction of time spent on it (the stationary distribution), found by power iteration (the dominant eigenvector of the link matrix). Now produce the failure damping exists to fix: toggle a spider trap (a page linking only to itself) and drag damping to 1 — the surfer falls in and never leaves, so that one page hoards 100% of the rank and the whole web ranks 0. Drag damping back down and teleport drains the trap, rank flows again. Verified: converges, sums to 1.</> },
  "kmeans": { Component: KMeansSection, title: <>How k-means finds clusters (unsupervised)</>, sub: <>Group unlabeled points into k clusters by alternating two trivial steps: assign each point to its nearest center, then move each center to the mean of its points. Both steps only shrink the total squared distance (inertia), so it drops monotonically and converges in a few rounds — on round blobs it recovers them cleanly (inertia 0.795, ARI 1.00). Then break it: switch to two concentric rings and watch k-means slice a straight line through both (ARI collapses to ~0 — its round objective can’t follow a non-convex shape, which is why DBSCAN exists), or re-seed to strand a center in a worse local optimum. Live.</> },
  "dbscan": { Component: DbscanSection, title: <>Clustering any shape + finding outliers (DBSCAN)</>, sub: <>Where k-means can only make round blobs, DBSCAN clusters by density: a point is “core” if ≥minPts neighbours sit within radius eps, and clusters flood outward along chains of core points — so they take any shape, the count emerges on its own, and stray points are labeled noise. Verified in node on concentric rings: DBSCAN cleanly separates the two rings (eps=0.09 → 2 clusters, 2 noise) while k-means slices them down the middle (~57%). Toggle DBSCAN vs k-means and tune eps.</> },
  "gmm": { Component: GmmSection, title: <>Soft clustering with Gaussians (GMM / EM)</>, sub: <>Where k-means makes hard, round assignments, a Gaussian mixture models the data as a blend of bell curves — each cluster a tilted ellipse — with soft membership, fit by Expectation-Maximization (E-step: responsibilities; M-step: refit each Gaussian). EM provably never lowers the log-likelihood — but produce the trap that guarantee hides: remove the covariance floor and a Gaussian collapses onto a single point, its variance racing to 0 and its density (with the likelihood) diverging to +∞ — a degenerate spike that clusters nothing. That singularity is why every real GMM floors the covariance. Node-verified: healthy fit → log-likelihood ~246; collapse → a component’s variance → ~1e-6 → 0.</> },
  "pca": { Component: PcaSection, title: <>How PCA compresses data (principal components)</>, sub: <>Find the directions data actually spreads along, so you can keep the important ones and drop the rest. The first principal component is the direction of maximum variance — which is exactly the top eigenvector of the covariance matrix; the second is perpendicular. Rotating into that basis and dropping the small axes is the linear projection that loses the least information. Verified three ways (brute-force angle search, analytic eigenvector, power iteration all agree). Rotate the axis and watch the projected variance peak at PC1.</> },
  "svd": { Component: SvdSection, title: <>How SVD compresses an image (low rank)</>, sub: <>Any matrix — an image — is A = UΣVᵀ, a sum of rank-1 layers σᵢuᵢvᵢᵀ ordered by importance. Keep the top k layers and you get a rank-k approximation that, by the Eckart–Young theorem, is the BEST possible rank-k picture — the image sharpens from a blur to exact as k grows, from k(m+n+1) numbers instead of m·n. Verified in node (one-sided Jacobi) four ways: reconstruction to 3e-15, orthonormal U/V, Σσ²=‖A‖²_F, and Eckart–Young ‖A−A_k‖²_F=Σσ². SVD is the stable way to do PCA. Slide the rank dial.</> },
  "perceptron": { Component: PerceptronSection, title: <>The first neural net (perceptron &amp; XOR)</>, sub: <>The perceptron (1958) is the original artificial neuron: output = step(w·x + b), a weighted sum thresholded into a line that splits the plane. It learns by nudging its weights toward every misclassified point. Rosenblatt proved it converges on any linearly-separable data in finite steps (verified: 2 epochs) — but a single neuron draws only one straight line, so it can’t separate XOR (verified: never converges), the limitation that stalled neural nets until layers + backprop. Watch the boundary learn to separate the blobs, then thrash on XOR.</> },
  "logisticregression": { Component: LogisticRegressionSection, title: <>From a hard line to a probability (logistic regression)</>, sub: <>The probabilistic upgrade of the perceptron: the linear score w·x + b squashed through the sigmoid into a probability, trained by gradient descent on the convex cross-entropy loss (one bowl → the global minimum from any start). But it stays LINEAR — produce the wall: on two blobs a line separates them (~91% accuracy), but switch to XOR (a checkerboard) and no line works, so the loss still converges yet accuracy sticks at ~50%, pure chance. Then add one nonlinear feature (x−½)(y−½) and the boundary bends → ~99%, exactly what a hidden layer does. It’s the output unit of a classifier net (softmax = multiclass).</> },
  "svm": { Component: SvmSection, title: <>The widest street between classes (SVM)</>, sub: <>Among the infinitely many lines that separate two classes, a support vector machine picks the one with the widest margin — the biggest empty band before it touches a point — because staying far from both sides generalizes best. That boundary is fixed by only a few support vectors on the margin edge; every other point is irrelevant. Verified in node: sliding a non-support-vector deep in its class moves the boundary 0.02° (unchanged), while a support vector shifts it. The kernel trick bends it into curves. Move a point and watch the boundary hold, then react.</> },
  "decisiontree": { Component: DecisionTreeSection, title: <>How a decision tree splits data (Gini)</>, sub: <>A flowchart of yes/no threshold questions (“is x &gt; 0.45?”) that carve the plane into axis-aligned regions, each split chosen greedily to most reduce Gini impurity. Then produce its defining failure: with noisy data and a held-out TEST set, slide the depth up — TRAIN accuracy climbs to 100% (the tree boxes every point, memorizing even the noise) but TEST accuracy peaks shallow (~depth 2) and then FALLS as the regions fracture into slivers around single points. A live curve shows the two diverge; that widening gap is overfitting. The fix is to stop early (cap depth / prune) or average many trees (a random forest). Node-verified: train 80→100%, test peaks 82% then drops to ~74%.</> },
  "randomforest": { Component: RandomForestSection, title: <>Why a forest beats one tree (bagging)</>, sub: <>A single deep tree overfits — it memorizes noise, so it aces training data but generalizes badly. A random forest trains many trees, each on a bootstrap resample with a random feature subset per split, and votes. The decorrelated trees make different mistakes that cancel: same low bias, far lower variance, a smooth boundary. Verified in node: single deep tree 98% train / 72% test (overfit) → forest ~76% test by a few trees. Slide the tree count and watch the jagged boundary smooth into the true circle.</> },
  "gradientboosting": { Component: GradientBoostingSection, title: <>Learning from residuals (gradient boosting)</>, sub: <>The other way to ensemble: build trees in sequence, each fit to the residual errors the model still makes. Start with the mean, fit a shallow tree to the leftover residuals, add a shrunk copy, and repeat — every round targets exactly what’s still wrong. For squared loss the residual is the negative gradient, so each tree is a gradient-descent step in function space. Verified in node: training MSE falls monotonically 0.0500→0.0002 (305× over 40 rounds). The sequential counterpart to a forest’s parallel bagging; slide the rounds.</> },
  "leakybucket": { Component: LeakyBucketSection, title: <>Leaky bucket traffic shaping</>, sub: <>Turn a bursty arrival stream into a perfectly smooth output. Packets pour into a bucket and drain at a fixed rate; bursts are absorbed up to the bucket's capacity and whatever overflows is dropped. The output never rises above the leak rate — the opposite trade-off from the token bucket, which lets saved-up bursts through.</> },
  "gcra": { Component: GcraSection, title: <>GCRA — rate limiting with a single timestamp</>, sub: <>The Generic Cell Rate Algorithm: the rate limiter behind Redis-Cell and many API gateways, which does everything a token bucket does with just one number of state per client — a "theoretical arrival time." A request is allowed if it arrives no earlier than TAT − τ; if so the TAT jumps forward by T. Idle time banks burst; sending too fast pushes the TAT past your clock until you're throttled, and the gap is your exact Retry-After. Drag the cadence and watch the one-line state throttle the stream.</> },
  "dram": { Component: DramSection, title: <>How RAM works — DRAM, rows &amp; the row buffer</>, sub: <>Main memory is a grid of leaky capacitors that must be refreshed 64 times a second. An access decodes a physical address into (bank, row, column), activates the row into a one-row-wide buffer, then reads a column out. That buffer is a cache — so sequential access hits the open row and flies, while random access keeps conflicting and paying a precharge. Decode an address and run access patterns to see the 3× latency swing.</> },
  "memorystory": { Component: MemoryStorySection, title: <>Memory, up close — a guided tour</>, sub: <>The same idea from the outside in. A narrated fly-through zooms from a RAM stick down through one chip, into the cell grid, to a single transistor-and-capacitor — then hands you the controls to write a bit, read it, and watch the charge leak away. It plays like an explainer, but the last scene is yours to drive.</> },
  "cpucycle": { Component: CpuCycleSection, title: <>How a CPU runs one instruction</>, sub: <>Fetch, decode, execute, writeback — the loop every processor runs billions of times a second. A narrated walkthrough lights up each stage on the datapath and flows the bus that carries the data, then hands you a step button to run a tiny three-instruction program and watch the program counter walk it.</> },
  "shuntingyard": { Component: ShuntingYardSection, title: <>How a calculator parses math (shunting-yard)</>, sub: <>We write math infix (3 + 4 × 2), but a machine can’t evaluate that left-to-right. Dijkstra’s shunting-yard algorithm converts it to Reverse Polish (postfix, 3 4 2 × +) in one linear pass with an operator stack + an output queue — precedence and parentheses resolved purely by when operators leave the stack, no parse tree. Then a stack machine evaluates the RPN. Verified: the result matches an independent recursive-descent parser on every random expression (0 mismatches over 4828). Watch tokens shunt between the queue and stack, then reduce to the answer.</> },
  "compiler": { Component: CompilerSection, title: <>How code becomes machine code</>, sub: <>The CPU only runs opcodes, so something has to turn your text into them. A narrated walk through the passes — lex the characters into tokens, parse the tokens into a tree that captures precedence, then walk the tree to emit instructions. The finale is a real tiny compiler: type an arithmetic expression and watch the actual tokens, AST, and assembly it produces.</> },
  "ssa": { Component: SsaSection, title: <>The form every optimizer uses (SSA &amp; phi nodes)</>, sub: <>Static Single Assignment is the IR where every variable is assigned exactly once: reassignments become versions (x → x₁, x₂), so every use names one definition. At a branch join, a φ (phi) node — x₄ = φ(x₂, x₃) — selects the version from whichever predecessor ran, keeping single-assignment true across control flow (φ nodes go minimally at dominance frontiers). One def per use makes constant propagation, dead-code elimination, and register allocation read straight off the graph — why LLVM, GCC, V8, and the JVM all optimize in SSA. Verified in node: the SSA form matches the mutable original for all inputs on both branches, each version is assigned once, φ picks the executed predecessor, and const-prop folds. Pick the input and follow a value through φ.</> },
  "regalloc": { Component: RegAllocSection, title: <>How variables get registers (graph coloring)</>, sub: <>A compiler invents hundreds of temporaries but the CPU has ~16 registers. Two variables live at the same time interfere and can’t share a register; model that as an interference graph and register allocation becomes graph coloring with K = the register count. Chaitin’s algorithm removes low-degree nodes to a stack (each is guaranteed a color), then pops and colors; if it gets stuck, a variable spills to memory. Verified in node over 600 graphs: the coloring is always proper, and coloring every node means the graph really is K-colorable (brute-force agrees). Slide K and watch variables get registers or spill.</> },
  "peephole": { Component: PeepholeSection, title: <>The compiler’s last polish (peephole optimization)</>, sub: <>The final local-rewrite pass: slide a small window over consecutive instructions and replace patterns with cheaper equivalents. Strength reduction (mul r,4 → shl r,2), algebraic identities and dead ops (add r,0 and mul r,1 vanish; xor r,r → mov r,0), and combining adjacent ops (add r,1; add r,1 → add r,2). Every rule is a proven semantics-preserving identity, and it iterates to a fixpoint since one rewrite can expose another — the closing pass in GCC and LLVM. Verified in node: all rewrites preserve semantics for every 32-bit input, and a 6-instruction sequence optimizes to 3 with identical output. Slide the peephole and watch the program shrink while the result stays 8x+4.</> },
  "hindley": { Component: HindleySection, title: <>How types are inferred with none written (Hindley-Milner)</>, sub: <>How ML, Haskell, Rust, and TypeScript know every type without annotations. Give each unknown a fresh type variable; each application f x forces f to be (type of x)→result, a constraint; solve them by unification, which finds the most general (principal) type. An occurs check forbids infinite types (so λx. x x doesn’t type), and let-bound values are generalized to be used at several types. Verified in node: Algorithm W infers the known principal types of five classic λ-terms exactly (λx.x : a→a, compose : (a→b)→(c→a)→c→b, …) and rejects self-application. Pick a term and read its inferred type.</> },
  "bytecode": { Component: BytecodeSection, title: <>How a bytecode VM runs code</>, sub: <>What the compiler’s output actually runs on. Many languages compile not to machine code but to a portable bytecode that a virtual machine interprets — Python, the JVM, WebAssembly. A narrated walk through the stack machine and its fetch-decode-execute loop (the CPU cycle, in software), then a live box: type an expression, see its real bytecode, and step the VM while the operand stack grows and shrinks.</> },
  "wasm": { Component: WasmSection, title: <>How WebAssembly sandboxes untrusted code</>, sub: <>How a browser runs a downloaded, untrusted program at near-native speed without letting it touch your machine. The module’s whole world is one bounded array (linear memory): every load/store is a bounds-checked index into it, so it has no pointers into host memory; the bytecode is type-checked before it runs; and it has zero ambient authority — only the functions you import. Real WASM opcodes and a real bounds-checked memory: slide the address and watch an out-of-bounds access trap at the sandbox boundary.</> },
  "jit": { Component: JitSection, title: <>How a JIT makes code fast</>, sub: <>The sequel to the bytecode VM: interpreting is portable but slow, so V8, the JVM, and PyPy compile the hot parts to native code while the program runs. A narrated walk through profiling to find hot loops, compiling and type-specializing them, swapping in the fast version, and deoptimizing when an assumption breaks. Run a loop, watch it cross the threshold and get ~50× faster, then break a type and watch it fall back.</> },
  "adder": { Component: AdderSection, title: <>The binary adder — how gates do arithmetic</>, sub: <>Every sum a CPU computes is built from one tiny circuit: the full adder (two bits plus a carry in gives a sum bit and a carry out). Chain eight of them and the carry ripples from the low bit up, exactly like carrying in decimal. Drag two numbers and watch the carry propagate, then see why the worst case (255 + 1, a full ripple) is the delay that pushes real ALUs to carry-lookahead.</> },
  "latch": { Component: LatchSection, title: <>The flip-flop — how a circuit remembers a bit</>, sub: <>The adder forgets; memory needs feedback. Cross-couple two NOR gates and the pair locks into a stable 0 or 1 and holds it. That is an SR latch. Add a clock edge and you get a D flip-flop, the storage element behind CPU registers and SRAM cache. Set, reset, and hold a latch, then clock a flip-flop and watch it capture data only on the rising edge.</> },
  "alu": { Component: AluSection, title: <>The ALU — how a CPU computes</>, sub: <>The arithmetic logic unit is the adder plus a few logic gates, with a multiplexer that an opcode uses to pick which result to keep. It computes add, subtract, and, or, xor, shifts, and compare all at once and selects one, raising the Z/N/C/V flags that turn a comparison into a branch. Pick an operation and two operands and watch the result and flags.</> },
  "wallace": { Component: WallaceSection, title: <>How hardware multiplies fast (Wallace tree)</>, sub: <>Multiplying is a sum of partial products — a shifted copy of a for each 1-bit of b — and adding N of them in sequence is slow. A Wallace tree lays every partial-product bit out as a dot diagram (a column per bit-weight) and reduces it with carry-save adders: a full adder turns 3 dots in a column into 1 sum dot + 1 carry dot next door, with no carry propagation, so every column compresses in parallel. After O(log N) stages only two rows remain, added once. Verified in node: the reduced product equals a·b (2000 multiplies, 0 mismatch) and the weighted dot-sum is invariant every stage. Step the reduction and watch the triangle collapse.</> },
  "membus": { Component: MemBusSection, title: <>Address decoding &amp; the memory bus</>, sub: <>ROM, RAM, and every I/O device sit on one shared address and data bus. When the CPU puts out an address, exactly one chip must answer — address decoding reads the high bits and asserts a single chip-select line, waking one device and keeping the rest off the bus. This is also why I/O is memory-mapped: a device is just an address range. Type an address and watch the decoder pick the chip.</> },
  "io": { Component: IoSection, title: <>Polling, interrupts &amp; DMA — how the CPU talks to devices</>, sub: <>A disk or network card has bytes for memory. The CPU can poll (spin on a status register and copy each byte — simple but 100% busy), take an interrupt per byte (free between bytes but a fixed overhead each — a fast stream drowns it), or hand off to a DMA controller (program it once, get one interrupt at the end — constant CPU cost no matter the size). Slide the transfer size and watch where the CPU's time goes.</> },
  "keystroke": { Component: KeystrokeSection, title: <>How a keystroke reaches the screen</>, sub: <>The whole stack in one journey. Press a key and it crosses the key matrix (a scancode), a hardware interrupt, the OS keymap and event queue, the focused app’s event loop, and finally rasterization into the framebuffer that the display scans out. A narrated walk through all five stages, then press the key yourself and follow the signal — with the latency it gathers at each hop.</> },
  "ssd": { Component: SsdSection, title: <>How an SSD works — flash &amp; the FTL</>, sub: <>Flash reads and writes a page but can only erase a whole block, and a page can't be overwritten in place. So an SSD never overwrites: the flash translation layer writes a fresh page, remaps it, and marks the old one stale, then garbage-collects blocks to reclaim space. That copying is write amplification, and erases are spread for wear leveling. Write pages and watch the FTL, GC, and wear play out.</> },
  "flashcell": { Component: FlashCellSection, title: <>How flash stores a bit — the floating gate</>, sub: <>One level below the FTL: the physics. A narrated zoom to a single floating-gate transistor, where electrons are tunnelled through insulating oxide and trapped so the bit survives with no power. Program it, read it by its threshold shift, erase it, and watch the oxide wear out — the reason SLC lasts ~100k cycles and QLC only ~1k.</> },
  "gpu": { Component: GpuSection, title: <>GPU / SIMT — how parallel compute wins or stalls</>, sub: <>A GPU runs threads in lockstep groups of 32 (a warp), all executing the same instruction each cycle. That makes it brilliant at data-parallel work and brittle in two ways: a branch that splits a warp serializes both paths (divergence), and scattered memory accesses explode into many transactions instead of one (coalescing). Pick a branch pattern and a memory access pattern and watch efficiency soar or collapse.</> },
  "systolic": { Component: SystolicSection, title: <>How a TPU multiplies matrices (systolic array)</>, sub: <>The matrix-multiply engine inside Google’s TPU: a grid of tiny multiply-accumulate cells. Matrix A streams in from the left and B from the top, each row and column staggered by a cycle; every cell multiplies its two inputs, adds to a running sum, and passes them on. The stagger makes the right operands meet at the right cell at the right moment, so a diagonal wavefront sweeps the grid and every cell ends holding one entry of C = A·B — each input read from memory once. Verified in node: bit-exact against the triple-loop matmul (400 matmuls, 0 mismatch), finishing in m+n+k−2 cycles. Step the clock and watch the wavefront.</> },
  "cpucache": { Component: CpuCacheSection, title: <>The CPU cache — sets, ways &amp; the address split</>, sub: <>The small fast SRAM that hides main memory's ~100 ns latency behind ~1 ns hits, by exploiting locality. A physical address splits into tag / set-index / byte-offset; the index picks a set, and the tag is compared against every way in it — a hit is fast, a miss fetches the 64-byte line and evicts the least-recently-used way. Change the associativity and run access patterns to watch conflict misses appear on a direct-mapped cache and vanish on a set-associative one.</> },
  "oooexec": { Component: OooExecSection, title: <>Out-of-order execution</>, sub: <>Why a modern CPU runs your instructions in a different order than you wrote them — and still gets the right answer. An in-order core stalls everything behind a cache-missing load; an out-of-order core issues each instruction the moment its inputs are ready, and register renaming removes false dependencies so only true data dependencies constrain it. Results still retire in program order. Edit a program and watch independent work slide under a load stall.</> },
  "rope": { Component: RopeSection, title: <>The rope — how editors edit huge text fast</>, sub: <>Inserting a character in the middle of a flat string is O(n) — every later byte shifts. A rope stores the document as the leaves of a balanced tree, where each internal node caches the length of its left subtree, so index, split, insert, and delete are all O(log n). Edits rewrite only one root-to-leaf path, and because nodes are immutable and shared, every past version stays alive for free undo. Edit the text and watch the tree splice.</> },
  "gapbuffer": { Component: GapBufferSection, title: <>The gap buffer — how Emacs edits text</>, sub: <>The whole document lives in one array with a run of empty slots — the gap — parked at the cursor. Typing drops a character into the gap in O(1), no shifting. Backspace and delete-forward just grow the gap. The only costly move is relocating the cursor, which slides the gap there by copying the characters it passes over (O(distance)). It bets that edits cluster at one point — and usually wins. Type, delete, and drag the cursor to watch the gap move.</> },
  "fastinvsqrt": { Component: FastInvSqrtSection, title: <>The fast inverse square root</>, sub: <>The most famous 20 lines in game programming — Quake III's trick for computing 1/√x with no sqrt and no division. A float's raw bits, read as an integer, are almost exactly a scaled log₂(x); so a single integer subtraction from the magic constant 0x5f3759df computes x^(−1/2) in log space, and one Newton step polishes the ~3.4% guess to ~0.17%. Pick x and watch the bits become the answer.</> },
  "kahan": { Component: KahanSumSection, title: <>Kahan summation — adding floats without losing accuracy</>, sub: <>A float has ~15–16 significant digits, so adding a small number to a large running total drops the small one's low bits — sum a million values and the lost bits become a real error. Kahan summation carries a compensation term that remembers what each addition dropped and folds it back, keeping the error near one rounding unit no matter how many terms. Watch the naive total drift while Kahan stays pinned to the true sum.</> },
  "cordic": { Component: CordicSection, title: <>How calculators do trig (CORDIC)</>, sub: <>How a pocket calculator or an FPGA with no multiplier computes cos and sin — with only bit-shifts and additions. cos θ and sin θ are the coordinates of a unit vector at angle θ, so CORDIC rotates a vector to θ by a fixed sequence of micro-rotations whose tangents are powers of two (each a shift-and-add), choosing + or − to home in like a binary search; a constant gain K≈0.6073 is cancelled by starting at (K,0). Real CORDIC, verified to five digits. Turn the dial and watch the vector spiral to your angle.</> },
  "karatsuba": { Component: KaratsubaSection, title: <>Karatsuba multiplication — beating n²</>, sub: <>Schoolbook multiplication of two n-digit numbers costs n² single-digit multiplies. In 1960 Karatsuba found you only need three half-size products, not four — because the middle term ad+bc equals (a+b)(c+d) − ac − bd. Recurse and n² collapses to n^1.585, which is why every big-integer library (and thus RSA/ECC key math) uses it. Enter two numbers and watch the recursion split into threes.</> },
  "simanneal": { Component: SimAnnealSection, title: <>Simulated annealing — escaping local minima</>, sub: <>Greedy optimization always moves downhill, so it gets trapped in the first local minimum it finds. Simulated annealing borrows from metallurgy: keep a temperature that starts high and cools, accepting uphill moves with probability exp(−ΔE/T) so the search can climb out of traps early, then settle as it cools. It's the workhorse for rugged combinatorial problems — chip placement, routing, scheduling. Watch greedy get stuck while annealing reaches the deep valley (change the seed — it's probabilistic).</> },
  "alphabeta": { Component: AlphaBetaSection, title: <>How game AI searches (alpha-beta)</>, sub: <>The algorithm behind classical game engines — chess, checkers, Othello. Minimax values a position assuming best play (you maximize, the opponent minimizes); alpha-beta pruning gets the identical value while skipping branches it can prove cannot change the decision, so with good move ordering it searches about twice as deep for the same cost. Real minimax + alpha-beta on a game tree (verified: same value as full minimax, fewer nodes, identical on thousands of random trees). Toggle between them and watch the pruned branches grey out.</> },
  "backprop": { Component: BackpropSection, title: <>How a neural network learns (backprop)</>, sub: <>The algorithm behind all of deep learning. A net is a function with weight knobs; training finds the knobs that make the output match the target. Backpropagation computes the gradient (∂loss/∂weight) for every weight in ONE backward sweep via the chain rule, reusing the forward values — so all gradients cost about one forward pass, which is why training huge nets is feasible. Real 2-2-1 sigmoid net, verified by a gradient check (analytic backprop matches finite-difference to 5 digits). Press train and watch the loss fall.</> },
  "word2vec": { Component: EmbeddingSection, title: <>How word embeddings work (word2vec)</>, sub: <>How words become vectors where meaning is geometry — the representation underneath semantic search, recommendations, and the input layer of every language model. Trained so words in similar contexts get similar vectors, with a startling result: relationships become consistent directions, so king − man + woman ≈ queen. A 2-D illustration (real embeddings use hundreds of dimensions), verified: all four analogies land on the expected word and the gender direction is parallel across pairs. Pick an analogy and watch a − b + c land on its nearest word.</> },
  "vectorsearch": { Component: VectorSearchSection, title: <>How vector search finds nearest embeddings (HNSW)</>, sub: <>How a vector database finds the nearest embeddings to a query — the retrieval behind semantic search and RAG — without comparing against millions of vectors. Build a proximity graph linking each vector to its nearest neighbors, then navigate it: hop toward the query, keeping the best ef candidates (a beam search). HNSW stacks layers — sparse top for long jumps, dense below — for near O(log n). Real best-first search verified: recall rises 91%→99.8% as ef grows, visiting under 20% of the vectors. Move the query and watch it navigate.</> },
  "attention": { Component: AttentionSection, title: <>How attention works (transformers)</>, sub: <>The core of every transformer and LLM. Each token emits a query, a key, and a value; a token attends to another by how well its query matches that key (a dot product), the scores are scaled and softmaxed into weights that sum to 1, and the token’s new representation is the weighted blend of everyone’s values. Real scaled dot-product attention over a 6-token toy: “river” attends to the water words, “money” to the finance words, and ambiguous “bank” to both. Pick the query token and watch the weights and the blended output.</> },
  "moe": { Component: MoeSection, title: <>Mixture of Experts (MoE)</>, sub: <>How a model has hundreds of billions of parameters but spends only a fraction per token. An MoE layer replaces one feed-forward net with N expert nets plus a router; for each token only the top-k experts run, weighted by a softmax gate — so capacity is decoupled from compute. Pick a token and top-k and watch which experts activate and how sparse it is (2 of 8 → 25% of the params). Then a batch view shows a balanced router spreading load vs a skewed one hogging a few experts, which is why MoE training adds a load-balancing loss. Behind Mixtral, DeepSeek, and GPT-4-class models.</> },
  "specdecode": { Component: SpecDecodeSection, title: <>Speculative decoding</>, sub: <>How LLM inference goes 2–3× faster without changing a single output token. A big model normally emits one token per expensive forward pass; speculative decoding runs a cheap <strong>draft</strong> model to propose several tokens, then the big <strong>target</strong> verifies them all in one pass and keeps the longest prefix it agrees with (plus its own token at the first miss). Toggle which draft guesses the target accepts and watch the kept prefix, the discarded tail, and the tokens-per-pass speedup — a good draft yields k+1 tokens per pass, a bad one just 1. The result is bit-for-bit greedy target decoding.</> },
  "kvcache": { Component: KvCacheSection, title: <>KV cache &amp; PagedAttention</>, sub: <>Why an LLM server’s memory, not its compute, caps how many chats it runs at once. Every token’s key and value stay in the <strong>KV cache</strong> so attention can look back; reserving a contiguous slab for each request’s max context wastes almost all of it — the same internal fragmentation that killed fixed-partition OS memory. vLLM’s <strong>PagedAttention</strong> applies the virtual-memory fix: fixed-size blocks + a per-sequence block table, allocated on demand. Slide the sequence length and flip naive↔paged to watch the block pool go from mostly-empty to packed and the sequences-that-fit jump ~10×.</> },
  "quantize": { Component: QuantizeSection, title: <>Weight quantization — int4/int8 &amp; the outlier problem</>, sub: <>How a 70B model runs on one consumer GPU. Weights trained in fp16 are stored at lower precision: map a group to a few integer levels around a shared <strong>scale</strong>, so int4 is a quarter the size (and faster, since inference is memory-bound). The cost is rounding error; the twist is <strong>outliers</strong> — one large weight sets the scale for everyone, spreading the levels so thin that the common small weights collapse toward zero. Slide the bit-width on a number line of weights and toggle an outlier to watch the error jump even though almost nothing moved — the whole reason LLM.int8/GPTQ/AWQ treat outliers specially.</> },
  "hamming": { Component: HammingSection, title: <>Hamming(7,4) — error correction that points at the mistake</>, sub: <>The first error-correcting code (Hamming, 1950). Four data bits become a seven-bit codeword with parity bits at positions 1, 2, 4. Each parity bit checks the positions whose index has that bit set, so the three checks together read out the binary index of any single flipped bit — the syndrome is the error's address. Toggle the data, corrupt a bit in transit, and watch the code locate and fix it.</> },
  "bresenham": { Component: BresenhamSection, title: <>Bresenham's line algorithm — drawing with integers</>, sub: <>How a computer draws a straight line on a grid of pixels (Bresenham, IBM, 1962). The naive way computes y = y0 + slope·(x−x0) and rounds — a floating-point multiply per pixel. Bresenham tracks a single integer error term and decides each step with only additions and comparisons, lighting up the exact same pixels with no multiply, divide, float, or round. Still in every GPU. Click the grid to move the endpoint.</> },
  "bezier": { Component: BezierSection, title: <>How curves are drawn (Bézier &amp; de Casteljau)</>, sub: <>A smooth curve from a few control points, built with nothing but repeated linear interpolation. de Casteljau’s algorithm lerps along the control polygon, then along those points, down to one point on the curve; sweep the parameter and it traces the whole Bézier. It equals the Bernstein polynomial exactly (verified to 3e-16), stays inside the control points’ convex hull, and splits into two sub-Béziers that reproduce it (verified to 1e-16). The workhorse of fonts, SVG/PDF paths, and UI easing. Drag the control points and watch the pyramid.</> },
  "raytracing": { Component: RaytraceSection, title: <>How ray tracing renders an image</>, sub: <>The way photorealistic 3D images are made: shoot a ray from the eye through every pixel, find what it hits, and shade that point by the light. A narrated walk through ray-object intersection, cosine shading, shadow rays (a second ray to the light), and reflection by recursion — beside a real ray-traced image. Drag the light and watch every pixel re-trace.</> },
  "rasterize": { Component: RasterizeSection, title: <>How a GPU rasterizes a triangle</>, sub: <>The other way to turn 3D into pixels, and the one real-time games use: instead of a ray per pixel, take each triangle and find which pixels it covers. A narrated walk through the edge-function inside test, barycentric colour interpolation, and the z-buffer — beside a real rasterized triangle. Slide a vertex and watch it re-rasterize, colours blending smoothly from the corners.</> },
  "perspective": { Component: PerspectiveSection, title: <>How 3D becomes 2D (perspective &amp; the texture warp)</>, sub: <>Projecting 3D to a screen divides each point by its depth (w), so the frustum maps to the NDC cube and parallel lines meet at a vanishing point. But texturing a receding surface can’t interpolate texture coordinates linearly across the screen — it warps (the PlayStation-1 wobble), because equal screen steps are unequal 3D steps. The fix: 1/w is the linear-in-screen quantity, so interpolate u/w, v/w, 1/w then divide. Verified in node: frustum corners → NDC cube exactly, and perspective-correct interpolation equals the true 3D value to 1e-15 while affine is off by a third of the range. Toggle the warp on a receding checkerboard floor.</> },
  "msaa": { Component: MsaaSection, title: <>How GPUs smooth jagged edges (MSAA)</>, sub: <>Why slanted edges staircase into jaggies — each pixel is fully inside or outside a triangle — and how multisample antialiasing fixes it cheaply. Supersampling renders at N× and averages, but shades N× too. MSAA takes N coverage samples per pixel (is each inside?) but shades once, then blends each pixel by its coverage — smooth edges at close to no extra shading, since only edge pixels aren’t fully in/out. Verified: 4-sample coverage matches the true area coverage. Toggle it on and off and tilt the edge.</> },
  "verlet": { Component: VerletSection, title: <>How game physics simulates rope &amp; cloth</>, sub: <>The Verlet integration behind cloth, rope, hair, and ragdolls. Store only positions — now and last frame — and their difference IS the velocity, so momentum is free. Advance each point by its momentum plus gravity, then satisfy distance constraints by moving points back to their rest length (relaxation). No stored velocity, no springs, and unconditionally stable. A live rope you can nudge; turn the relaxation passes up to stiffen it, down to make it rubbery.</> },
  "barneshut": { Component: BarnesHutSection, title: <>How galaxies simulate gravity fast (Barnes-Hut)</>, sub: <>Simulating gravity among n bodies is O(n²) — every star pulls on every other. Barnes-Hut cuts it to O(n log n) using one fact: a distant clump of stars pulls almost exactly like a single body at its center of mass. A quadtree summarizes each region’s mass and center of mass; to find a body’s force you walk the tree, lumping any node far enough that its width ÷ distance is below θ, and opening the rest. Verified against the exact sum: ~2% force error at θ=0.5. Turn the θ dial and watch the approximation boxes grow.</> },
  "doublependulum": { Component: DoublePendulumSection, title: <>Why the weather is unpredictable (chaos)</>, sub: <>The double pendulum: a system whose equations are exact and fully deterministic — energy conserved to nine digits — yet two starts differing by a thousandth of a degree diverge exponentially and do completely different things within seconds. That’s deterministic chaos: not randomness, but sensitivity so extreme that any imprecision in the start explodes into unpredictability — the same reason weather can’t be forecast far ahead. Real RK4 physics; set the starting gap and watch the two pendulums track, then split.</> },
  "orbit": { Component: OrbitSection, title: <>Why simulated orbits drift (symplectic integrators)</>, sub: <>Simulating a planet means stepping time forward and updating velocity and position from gravity — but the update order decides stability. Forward Euler systematically injects energy every step, so the orbit spirals outward and escapes; velocity-Verlet centers the update, is symplectic, and conserves energy essentially forever, keeping the orbit closed for millions of steps at the same cost. Verified: over a few orbits Euler drifts ~75% in energy (radius nearly quadruples) while Verlet drifts 0%. Race the two integrators from the same start.</> },
  "raymarch": { Component: RayMarchSection, title: <>How ray-marching renders with math (SDF)</>, sub: <>How Shadertoy and demoscene intros render whole worlds with no meshes — the scene is a signed distance function (for any point, the distance to the nearest surface), and a ray steps forward by that distance each time (sphere tracing), safe because nothing is closer. Big steps in open space, small near surfaces, converging in a handful of iterations. Real sphere tracing on a 2-D slice: aim the ray and watch it leap, creep, and converge (or miss). The field also gives normals, CSG, soft shadows, and AO almost for free.</> },
  "quaternion": { Component: QuaternionSection, title: <>How 3D rotation really works (quaternions &amp; slerp)</>, sub: <>Euler angles (yaw/pitch/roll) are intuitive but hit gimbal lock — at pitch 90° two axes align and a degree of freedom vanishes. A unit quaternion q = cos(θ/2) + sin(θ/2)·axis is a point on the 4-sphere with no gimbal lock; it rotates a vector by the sandwich v′ = q·v·q⁻¹, and slerp blends two orientations along the shortest great-circle arc at constant angular velocity. Verified in node: quat→matrix == the Rodrigues axis-angle matrix to 1e-15, v′=q·v·q⁻¹ == R·v, slerp stays unit-norm and moves at constant speed. Blend two poses and compare slerp vs Euler lerp.</> },
  "convexhull": { Component: ConvexHullSection, title: <>Convex hull — the rubber band around your points</>, sub: <>The smallest convex polygon enclosing a set of points — the shape a rubber band makes snapped around a bed of nails. Andrew's monotone chain sorts the points, then sweeps once for the lower hull and once for the upper, using the cross product (turn left / right / straight — no trig) to pop any point that would make a dent. O(n log n), and that's optimal. Click to add points and watch the hull re-form.</> },
  "sat": { Component: SatSection, title: <>How games detect collisions (SAT)</>, sub: <>The exact test behind convex collision detection: two convex shapes are disjoint if and only if some axis exists on which their projected shadows don’t overlap. For polygons only the edge normals need checking — one gap on any axis proves no collision, and if every axis overlaps, the smallest overlap gives the minimum push to separate them. Real SAT verified against a brute-force oracle. Slide a triangle through a square and watch the shadows open a gap.</> },
  "spatialhash": { Component: SpatialHashSection, title: <>How games skip the n² collision test (spatial hash)</>, sub: <>SAT is the exact test — but running it on every pair of objects is O(n²), which explodes. The broad phase is a cheap pre-filter: overlay a uniform grid, bucket each object into its cell, and only test pairs that share a cell, since anything farther can’t touch. Verified against a brute-force oracle: it finds the identical collisions from about 1% of the pair-tests (248 vs 19,900 for 200 objects). Toggle brute force vs the grid and watch the candidate count collapse while the collisions stay the same.</> },
  "marchsquares": { Component: MarchSquaresSection, title: <>Marching squares — grid of numbers to smooth contour</>, sub: <>How you turn a scalar field (elevation, brightness, density) into the contour line where it equals a threshold — the coastline between above and below. Each cell's four corners give one of 16 cases; the contour crosses the edges separating an above corner from a below one, cut at the linear-interpolated crossing for smoothness. Every cell is independent (great for the GPU), and it's the 2-D sibling of marching cubes. Slide the threshold and watch the blobs merge.</> },
  "voronoi": { Component: VoronoiSection, title: <>Voronoi diagram — the plane split by nearest site</>, sub: <>Carve a plane into one cell per site, where every point belongs to whichever site is nearest — the honeycomb you see in cracked mud, giraffe coats, and cell-tower coverage maps. Each boundary is the perpendicular bisector of two sites, so every cell is convex, and the whole diagram is the exact dual of the Delaunay triangulation. Click to add sites; switch the distance metric (Euclidean / Manhattan / Chebyshev) to reshape the cells.</> },
  "delaunay": { Component: DelaunaySection, title: <>Delaunay triangulation — fat triangles, no slivers</>, sub: <>Connect scattered points into triangles that avoid slivers: the Delaunay triangulation maximizes the smallest angle, giving triangles as close to equilateral as the points allow — essential for finite-element meshes, terrain, and interpolation. Its defining rule is the empty-circumcircle property (no point inside any triangle's circumcircle), and it's the exact dual of the Voronoi diagram. Built here with Bowyer-Watson. Click to add points; toggle the Voronoi dual to see the connection.</> },
  "montgomery": { Component: MontgomerySection, title: <>Montgomery multiplication — modular multiply without division</>, sub: <>RSA and elliptic-curve crypto compute a·b mod n for a huge modulus thousands of times, and the slow, timing-leaky part is the "mod n" — a full division. Montgomery's trick works in a coordinate system where numbers are held as a·R mod n, so reduction (REDC) needs only multiplies, adds, a bit-mask (mod R) and a shift (÷R) — never a division by n, and the same fixed operations regardless of the values (constant-time). Enter a modulus and two numbers and watch a·b mod n fall out with only masks and shifts.</> },
  "twosat": { Component: TwoSatSection, title: <>2-SAT — boolean satisfiability in linear time</>, sub: <>General SAT is NP-complete, but restrict every clause to two literals and it becomes solvable in linear time by a beautiful reduction to graph theory. A clause (a ∨ b) is two implications (¬a ⇒ b, ¬b ⇒ a); build the implication graph and the formula is unsatisfiable exactly when some variable and its negation land in the same strongly-connected component. One SCC pass decides it and builds a satisfying assignment. Pick a formula and watch the components and verdict.</> },
  "wfc": { Component: WfcSection, title: <>Generating maps by constraints (wave function collapse)</>, sub: <>Fill a grid so every neighboring pair obeys adjacency rules. Each cell starts in superposition (any tile); repeatedly collapse the lowest-entropy cell (fewest options) to one random tile, then propagate — delete now-impossible tiles from neighbors, cascading outward (arc-consistency, like a Sudoku solver). When every cell holds one tile, the whole grid satisfies the rules by construction — no final check needed. Verified in node: 0 constraint violations across 2000 generated grids, contradictions ~0% with the min-entropy order, and varied output. The engine behind procedural game maps and textures. Step the collapse or generate a fresh map.</> },
  "perlin": { Component: PerlinSection, title: <>Perlin noise — smooth randomness for procedural worlds</>, sub: <>The gradient-noise algorithm (Ken Perlin, 1983, soon after working on Tron) behind procedural terrain, clouds, fire, and marble textures. Instead of a random value per pixel (harsh white noise), it assigns a random gradient to each grid point and blends the neighbors with the fade curve 6t⁵−15t⁴+10t³ — smooth everywhere, and exactly zero at the lattice points. Stack octaves at doubling frequency for fractal detail. Reseed, zoom, and add octaves to grow a landscape.</> },
  "poisson": { Component: PoissonSection, title: <>Poisson-disk sampling — evenly-spaced randomness</>, sub: <>Scatter points that look random but never clump: every pair at least r apart, yet the area stays evenly covered. This "blue noise" is what rendering, stippling, and procedural scattering want — uniform random points bunch up and leave holes, causing splotchy shadows and grainy antialiasing. Bridson's algorithm builds it in O(n) by firing candidate darts into the ring between r and 2r around active points, with an O(1) grid spacing-check. Flip blue vs white noise and watch the min distance.</> },
  "transistor": { Component: TransistorSection, title: <>Transistors &rarr; logic gates</>, sub: <>The bottom of the stack. A transistor is a voltage-controlled switch: NMOS conducts when its gate is high, PMOS when low. Wire a PMOS pull-up and NMOS pull-down together and you get a CMOS gate — an inverter, a NAND, a NOR. And NAND alone is universal: every other gate is built from it. Toggle inputs to watch the transistors conduct, then build any gate from NAND. Everything above — the adder, the ALU, the flip-flop — is just billions of these.</> },
  "knapsack": { Component: KnapsackSection, title: <>0/1 Knapsack (dynamic programming)</>, sub: <>Pick a subset of items to maximize value within a weight budget — where greedy fails and DP wins. Watch the table fill row by row, read the answer off the bottom-right corner, and follow the highlighted backtrack path to see which items were chosen. The greedy-by-ratio result is shown losing alongside.</> },
  "deployments": { Component: DeployStratSection, title: <>Deployment strategies</>, sub: <>How you ship v2 without taking the service down — and the risk/speed/cost trade-offs between them. Step through recreate, rolling, blue-green, and canary: watch the fleet flip versions, the router split traffic, and the availability meter reveal who feels the rollout.</> },
  "healthcheck": { Component: HealthCheckSection, title: <>Liveness vs readiness probes</>, sub: <>The Kubernetes distinction that, gotten wrong, causes restart storms. Readiness decides whether a pod gets traffic; liveness decides whether it gets killed and restarted. Step through scenarios — including the anti-pattern where a slow-under-load check on the liveness probe crashloops the whole fleet.</> },
  "autoscale": { Component: AutoscaleSection, title: <>Horizontal autoscaling (HPA)</>, sub: <>How a service grows and shrinks its replica count to track load, from one simple formula: desired = ceil(replicas × metric / target). Step through a load series and watch replicas chase demand — scaling up instantly, scaling down only after a stabilization window rides out brief dips.</> },
  "kubesched": { Component: KubeSchedSection, title: <>Kubernetes pod scheduling</>, sub: <>How the kube-scheduler places a pod: it <strong>filters</strong> out nodes that can’t run it (not enough allocatable CPU/memory, an untolerated <strong>taint</strong>, a <strong>nodeSelector</strong> that doesn’t match), then <strong>scores</strong> the survivors — the default spreads load to the node with the most room left — and binds the pod there. Tune the pod’s requests and constraints and watch nodes get filtered or scored; ask for more than any node has free and the pod stays <strong>Pending</strong>.</> },
  "usl": { Component: UslSection, title: <>Universal Scalability Law</>, sub: <>Why adding workers eventually stops helping — and then starts hurting. Amdahl's law says a serial fraction caps speedup; the USL adds a coherency term for the coordination cost between workers (which grows with the number of pairs, ∝ N²), so throughput peaks at an optimal concurrency and goes retrograde past it. Drag contention α and coherency β and watch the curve bend back down.</> },
  "pid": { Component: PidSection, title: <>PID controller</>, sub: <>The feedback loop behind cruise control, thermostats, drones — and, increasingly, autoscaling and congestion control. It drives a process to a setpoint from three terms on the error: proportional (fast, but leaves a droop), integral (erases the droop), derivative (damps overshoot). Tune Kp, Ki, Kd and watch a positioning system overshoot, droop, or settle cleanly — the same trade-offs that make aggressive autoscaling oscillate.</> },
  "kalman": { Component: KalmanSection, title: <>How a Kalman filter tracks</>, sub: <>The optimal way to track a moving thing from noisy measurements — it flew Apollo to the Moon and now smooths your GPS dot, stabilises drones, and fuses your phone’s sensors. Each step it predicts where the thing should be from its motion, then corrects with the new measurement, weighting the two by their uncertainties (the Kalman gain). Real 1D constant-velocity filter: watch the estimate hug the truth while the raw sensor scatters, and slide the sensor/model noise to see the filter trust one or the other.</> },
  "slo": { Component: SloSection, title: <>SLOs &amp; error budgets</>, sub: <>The math that turns "be reliable" into a number you can spend. Pick an availability target, see the error budget it buys (downtime allowed per month), and watch the release policy flip from "ship" to "freeze" when it runs out. The burn-rate panel turns a current error rate into how fast you're spending and which alerts page you.</> },
  "tracing": { Component: TracingSection, title: <>Distributed tracing</>, sub: <>Follow one request as it fans out across services, and see where the time actually went. Each span is a bar on the waterfall — positioned by when it started, indented by call depth — and the self-time breakdown points straight at the real bottleneck instead of a guess.</> },
  "featureflags": { Component: FeatureFlagSection, title: <>Feature flags</>, sub: <>Decouple deploy from release: the code already shipped, so turning a feature on is a config change that takes effect in seconds. Drag the rollout and watch users flip on in a stable order, force a cohort on with a targeting rule, or hit the kill switch and everyone goes off instantly — no redeploy.</> },
  "gracefulshutdown": { Component: GracefulShutdownSection, title: <>Graceful shutdown &amp; connection draining</>, sub: <>How to take an instance down without dropping the requests it's already serving. SIGTERM lands; fail readiness so new traffic stops, drain in-flight requests, then exit. Drag the grace period below your longest request and watch the orchestrator force-kill the stragglers into 5xxs — the unglamorous half of every zero-downtime claim.</> },
  "idempotency": { Component: IdempotencySection, title: <>Idempotency keys</>, sub: <>How an API makes "charge $100" safe to retry. The network only promises at-least-once delivery, so clients retry lost requests — and without protection, the retry charges again. Watch the same scenario run down two paths: without a key it double-charges; with a key the server replays the stored result, exactly once.</> },
  "loadshed": { Component: LoadShedSection, title: <>Load shedding &amp; backpressure</>, sub: <>Under overload, rejecting work fast beats queuing it. Same demand, two servers: one with a bounded queue that sheds the excess, one that queues everything. Drag the offered load past the service rate and watch the unbounded server's backlog explode into congestion collapse while the shedding one holds steady useful throughput.</> },
  "bulkhead": { Component: BulkheadSection, title: <>Bulkhead isolation</>, sub: <>Why one slow dependency can take down your whole service — and how per-dependency resource pools contain the damage. From a shared thread pool, a sick dependency's piled-up requests consume every slot, starving healthy calls too. Drag a dependency's latency up and compare a shared pool (total outage) to bulkheads (only the sick one degrades).</> },
  "chaos": { Component: ChaosSection, title: <>Chaos engineering</>, sub: <>Deliberately break one thing to discover how far the damage spreads — and prove your resilience contains it. Click a service to kill it and watch the failure cascade; a hard dependency drags its callers down, a resilient one absorbs it. Flip on resilience shields and watch the blast radius shrink.</> },
  "singleflight": { Component: SingleFlightSection, title: <>Request coalescing (singleflight)</>, sub: <>Stopping a cache miss from becoming a stampede. When a hot key expires, every concurrent request misses at once and they all hit the backend for the same value. Singleflight lets the first compute it while the rest wait and share the result — N simultaneous misses become one backend call.</> },
  "branchpredict": { Component: BranchPredictSection, title: <>Branch prediction</>, sub: <>How a CPU guesses which way a branch goes before it knows, so the pipeline doesn't stall. Step a 2-bit saturating counter through a branch-outcome pattern and watch the hysteresis at work — then compare its mispredictions against a 1-bit predictor on the loop-exit pattern, where the extra bit halves the misses.</> },
  "strideprefetch": { Component: StridePrefetchSection, title: <>How the CPU prefetches memory (stride prefetcher)</>, sub: <>A cache miss stalls the CPU for hundreds of cycles, so hardware fetches the next line before it’s asked for. A stride prefetcher keeps a reference prediction table indexed by each load’s PC {'{'}last address, stride, state{'}'}; when two consecutive address deltas match, it locks onto the stride and prefetches addr+stride. Verified in node: on a strided array walk coverage is ~99.9% (only the two warm-up accesses miss), while random access and pointer-chasing a shuffled linked list get ~0% — the concrete reason arrays are cache-friendly and linked lists are not. Pick a pattern and watch the RPT lock on.</> },
  "branchless": { Component: BranchlessSection, title: <>Code with no branches (branchless / cmov)</>, sub: <>A branch on unpredictable or secret data costs a ~15-cycle misprediction flush and leaks the condition through timing and speculative execution. Branchless code turns the condition into a full-width mask — −(a&lt;b) is all-1 bits or all-0 bits — and selects with arithmetic: max(a,b) = a ^ ((a^b) &amp; mask). The same operations run every time, so it’s fast (no misprediction) and constant-time (no timing side channel); hardware exposes it as the cmov instruction. Verified in node: branchless min/max/abs/select match the branchy versions across all inputs. Why constant-time crypto never branches on secrets. Build the mask and watch it select.</> },
  "spectre": { Component: SpectreSection, title: <>Spectre — leaking secrets through speculation</>, sub: <>How the 2018 attack reads memory it isn't allowed to, by abusing speculative execution. The CPU runs ahead past a bounds check it mispredicts, speculatively reads a secret byte, and leaves a trace in the cache — which timing (Flush+Reload) then recovers. Step through the leak and watch the secret appear byte by byte, then flip on the lfence barrier and watch it stop.</> },
  "meltdown": { Component: MeltdownSection, title: <>How Meltdown reads kernel memory (transient execution)</>, sub: <>Spectre’s sibling, and the attack that forced kernel page-table isolation into every OS. An unprivileged read of a kernel address faults — but out-of-order execution forwards the byte to later instructions transiently, before the fault retires, and they cache probe[secret]. Architecturally the read never happened; but Flush+Reload times all 256 lines and the one fast line names the byte. Verified: the oracle recovers every value 0–255. Sandboxed simulation, defenses-forward (KPTI unmaps the kernel). Set a secret and recover it by timing.</> },
  "rowhammer": { Component: RowhammerSection, title: <>How Rowhammer flips bits in DRAM (fault injection)</>, sub: <>A software-only fault-injection attack on hardware. DRAM cells are packed so densely that activating one row leaks charge from its neighbours; hammer a row hundreds of thousands of times before the next refresh and adjacent-row bits flip — in memory the attacker never wrote to. Double-sided hammering flips a sandwiched victim in half the activations. A flip in a page-table entry is privilege escalation (Google 2015). Sandboxed model, invariant-tested and anchored to Kim et al. 2014 (~139K activations); defenses-forward (TRR/ECC/refresh). Hammer it and watch bits flip, then out-refresh it.</> },
  "killchain": { Component: KillChainSection, title: <>The kill chain &amp; defense-in-depth (attacker’s lens)</>, sub: <>A real breach is a chain of stages the attacker must complete in order — recon, exploitation (buffer overflow → ROP), privilege escalation (Meltdown / Rowhammer), lateral movement (ARP spoof / Kaminsky), collection (padding oracle / Spectre), exfiltration — each a technique with its own Apex story, and each with a defense. The chain is a conjunction: the attacker needs every stage, so breaking any one link stops the whole attack. Verified: of all 2⁶ defense combinations, a full breach happens in exactly one (nothing defended). Click a stage to raise its defense and contain the intrusion.</> },
};
