// GENERATED section registry chunk 5 — see sections/registry.tsx. One data row per section: title, sub, component.
import type { SectionEntry } from './registry';
import { MemoryStorySection } from '../MemoryStorySection';
import { CpuCycleSection } from '../CpuCycleSection';
import { CompilerSection } from '../CompilerSection';
import { BytecodeSection } from '../BytecodeSection';
import { WasmSection } from '../WasmSection';
import { JitSection } from '../JitSection';
import { FloydSection } from '../FloydSection';
import { BellmanFordSection } from '../BellmanFordSection';
import { LeakyBucketSection } from '../LeakyBucketSection';
import { GcraSection } from '../GcraSection';
import { DramSection } from '../DramSection';
import { AdderSection } from '../AdderSection';
import { LatchSection } from '../LatchSection';
import { AluSection } from '../AluSection';
import { MemBusSection } from '../MemBusSection';
import { IoSection } from '../IoSection';
import { SsdSection } from '../SsdSection';
import { FlashCellSection } from '../FlashCellSection';
import { KeystrokeSection } from '../KeystrokeSection';
import { RaytraceSection } from '../RaytraceSection';
import { RasterizeSection } from '../RasterizeSection';
import { MsaaSection } from '../MsaaSection';
import { VerletSection } from '../VerletSection';
import { BarnesHutSection } from '../BarnesHutSection';
import { RayMarchSection } from '../RayMarchSection';
import { GpuSection } from '../GpuSection';
import { CpuCacheSection } from '../CpuCacheSection';
import { OooExecSection } from '../OooExecSection';
import { RopeSection } from '../RopeSection';
import { GapBufferSection } from '../GapBufferSection';
import { FastInvSqrtSection } from '../FastInvSqrtSection';
import { KahanSumSection } from '../KahanSumSection';
import { CordicSection } from '../CordicSection';
import { KaratsubaSection } from '../KaratsubaSection';
import { SimAnnealSection } from '../SimAnnealSection';
import { AlphaBetaSection } from '../AlphaBetaSection';
import { BackpropSection } from '../BackpropSection';
import { AttentionSection } from '../AttentionSection';
import { EmbeddingSection } from '../EmbeddingSection';
import { VectorSearchSection } from '../VectorSearchSection';
import { HammingSection } from '../HammingSection';
import { BresenhamSection } from '../BresenhamSection';
import { ConvexHullSection } from '../ConvexHullSection';
import { SatSection } from '../SatSection';
import { SpatialHashSection } from '../SpatialHashSection';
import { MarchSquaresSection } from '../MarchSquaresSection';
import { VoronoiSection } from '../VoronoiSection';
import { DelaunaySection } from '../DelaunaySection';
import { MontgomerySection } from '../MontgomerySection';
import { TwoSatSection } from '../TwoSatSection';
import { PerlinSection } from '../PerlinSection';
import { PoissonSection } from '../PoissonSection';
import { TransistorSection } from '../TransistorSection';
import { KnapsackSection } from '../KnapsackSection';
import { DeployStratSection } from '../DeployStratSection';
import { HealthCheckSection } from '../HealthCheckSection';
import { AutoscaleSection } from '../AutoscaleSection';
import { UslSection } from '../UslSection';
import { PidSection } from '../PidSection';
import { KalmanSection } from '../KalmanSection';
import { SloSection } from '../SloSection';
import { TracingSection } from '../TracingSection';
import { FeatureFlagSection } from '../FeatureFlagSection';
import { GracefulShutdownSection } from '../GracefulShutdownSection';
import { IdempotencySection } from '../IdempotencySection';
import { LoadShedSection } from '../LoadShedSection';
import { BulkheadSection } from '../BulkheadSection';
import { ChaosSection } from '../ChaosSection';
import { SingleFlightSection } from '../SingleFlightSection';
import { BranchPredictSection } from '../BranchPredictSection';
import { SpectreSection } from '../SpectreSection';

export const chunk5: Record<string, SectionEntry> = {
  "floyd": { Component: FloydSection, title: <>Floyd-Warshall all-pairs shortest paths</>, sub: <>Shortest paths between every pair of vertices in one cubic dynamic program. Step through the intermediate vertices and watch the distance matrix relax — each cell taking the cheaper of what it had and routing through the current waypoint. Handles negative edges, and flags a negative cycle.</> },
  "bellmanford": { Component: BellmanFordSection, title: <>Bellman-Ford &amp; arbitrage detection</>, sub: <>The shortest-path algorithm that survives negative edges — and detects the negative cycles where "shortest" breaks down. Step the relaxation passes to watch distances settle on a graph Dijkstra would get wrong, then turn the same machinery into a currency-arbitrage detector: model each rate as −ln(rate) and a profitable trading loop becomes a negative cycle.</> },
  "leakybucket": { Component: LeakyBucketSection, title: <>Leaky bucket traffic shaping</>, sub: <>Turn a bursty arrival stream into a perfectly smooth output. Packets pour into a bucket and drain at a fixed rate; bursts are absorbed up to the bucket's capacity and whatever overflows is dropped. The output never rises above the leak rate — the opposite trade-off from the token bucket, which lets saved-up bursts through.</> },
  "gcra": { Component: GcraSection, title: <>GCRA — rate limiting with a single timestamp</>, sub: <>The Generic Cell Rate Algorithm: the rate limiter behind Redis-Cell and many API gateways, which does everything a token bucket does with just one number of state per client — a "theoretical arrival time." A request is allowed if it arrives no earlier than TAT − τ; if so the TAT jumps forward by T. Idle time banks burst; sending too fast pushes the TAT past your clock until you're throttled, and the gap is your exact Retry-After. Drag the cadence and watch the one-line state throttle the stream.</> },
  "dram": { Component: DramSection, title: <>How RAM works — DRAM, rows &amp; the row buffer</>, sub: <>Main memory is a grid of leaky capacitors that must be refreshed 64 times a second. An access decodes a physical address into (bank, row, column), activates the row into a one-row-wide buffer, then reads a column out. That buffer is a cache — so sequential access hits the open row and flies, while random access keeps conflicting and paying a precharge. Decode an address and run access patterns to see the 3× latency swing.</> },
  "memorystory": { Component: MemoryStorySection, title: <>Memory, up close — a guided tour</>, sub: <>The same idea from the outside in. A narrated fly-through zooms from a RAM stick down through one chip, into the cell grid, to a single transistor-and-capacitor — then hands you the controls to write a bit, read it, and watch the charge leak away. It plays like an explainer, but the last scene is yours to drive.</> },
  "cpucycle": { Component: CpuCycleSection, title: <>How a CPU runs one instruction</>, sub: <>Fetch, decode, execute, writeback — the loop every processor runs billions of times a second. A narrated walkthrough lights up each stage on the datapath and flows the bus that carries the data, then hands you a step button to run a tiny three-instruction program and watch the program counter walk it.</> },
  "compiler": { Component: CompilerSection, title: <>How code becomes machine code</>, sub: <>The CPU only runs opcodes, so something has to turn your text into them. A narrated walk through the passes — lex the characters into tokens, parse the tokens into a tree that captures precedence, then walk the tree to emit instructions. The finale is a real tiny compiler: type an arithmetic expression and watch the actual tokens, AST, and assembly it produces.</> },
  "bytecode": { Component: BytecodeSection, title: <>How a bytecode VM runs code</>, sub: <>What the compiler’s output actually runs on. Many languages compile not to machine code but to a portable bytecode that a virtual machine interprets — Python, the JVM, WebAssembly. A narrated walk through the stack machine and its fetch-decode-execute loop (the CPU cycle, in software), then a live box: type an expression, see its real bytecode, and step the VM while the operand stack grows and shrinks.</> },
  "wasm": { Component: WasmSection, title: <>How WebAssembly sandboxes untrusted code</>, sub: <>How a browser runs a downloaded, untrusted program at near-native speed without letting it touch your machine. The module’s whole world is one bounded array (linear memory): every load/store is a bounds-checked index into it, so it has no pointers into host memory; the bytecode is type-checked before it runs; and it has zero ambient authority — only the functions you import. Real WASM opcodes and a real bounds-checked memory: slide the address and watch an out-of-bounds access trap at the sandbox boundary.</> },
  "jit": { Component: JitSection, title: <>How a JIT makes code fast</>, sub: <>The sequel to the bytecode VM: interpreting is portable but slow, so V8, the JVM, and PyPy compile the hot parts to native code while the program runs. A narrated walk through profiling to find hot loops, compiling and type-specializing them, swapping in the fast version, and deoptimizing when an assumption breaks. Run a loop, watch it cross the threshold and get ~50× faster, then break a type and watch it fall back.</> },
  "adder": { Component: AdderSection, title: <>The binary adder — how gates do arithmetic</>, sub: <>Every sum a CPU computes is built from one tiny circuit: the full adder (two bits plus a carry in gives a sum bit and a carry out). Chain eight of them and the carry ripples from the low bit up, exactly like carrying in decimal. Drag two numbers and watch the carry propagate, then see why the worst case (255 + 1, a full ripple) is the delay that pushes real ALUs to carry-lookahead.</> },
  "latch": { Component: LatchSection, title: <>The flip-flop — how a circuit remembers a bit</>, sub: <>The adder forgets; memory needs feedback. Cross-couple two NOR gates and the pair locks into a stable 0 or 1 and holds it. That is an SR latch. Add a clock edge and you get a D flip-flop, the storage element behind CPU registers and SRAM cache. Set, reset, and hold a latch, then clock a flip-flop and watch it capture data only on the rising edge.</> },
  "alu": { Component: AluSection, title: <>The ALU — how a CPU computes</>, sub: <>The arithmetic logic unit is the adder plus a few logic gates, with a multiplexer that an opcode uses to pick which result to keep. It computes add, subtract, and, or, xor, shifts, and compare all at once and selects one, raising the Z/N/C/V flags that turn a comparison into a branch. Pick an operation and two operands and watch the result and flags.</> },
  "membus": { Component: MemBusSection, title: <>Address decoding &amp; the memory bus</>, sub: <>ROM, RAM, and every I/O device sit on one shared address and data bus. When the CPU puts out an address, exactly one chip must answer — address decoding reads the high bits and asserts a single chip-select line, waking one device and keeping the rest off the bus. This is also why I/O is memory-mapped: a device is just an address range. Type an address and watch the decoder pick the chip.</> },
  "io": { Component: IoSection, title: <>Polling, interrupts &amp; DMA — how the CPU talks to devices</>, sub: <>A disk or network card has bytes for memory. The CPU can poll (spin on a status register and copy each byte — simple but 100% busy), take an interrupt per byte (free between bytes but a fixed overhead each — a fast stream drowns it), or hand off to a DMA controller (program it once, get one interrupt at the end — constant CPU cost no matter the size). Slide the transfer size and watch where the CPU's time goes.</> },
  "keystroke": { Component: KeystrokeSection, title: <>How a keystroke reaches the screen</>, sub: <>The whole stack in one journey. Press a key and it crosses the key matrix (a scancode), a hardware interrupt, the OS keymap and event queue, the focused app’s event loop, and finally rasterization into the framebuffer that the display scans out. A narrated walk through all five stages, then press the key yourself and follow the signal — with the latency it gathers at each hop.</> },
  "ssd": { Component: SsdSection, title: <>How an SSD works — flash &amp; the FTL</>, sub: <>Flash reads and writes a page but can only erase a whole block, and a page can't be overwritten in place. So an SSD never overwrites: the flash translation layer writes a fresh page, remaps it, and marks the old one stale, then garbage-collects blocks to reclaim space. That copying is write amplification, and erases are spread for wear leveling. Write pages and watch the FTL, GC, and wear play out.</> },
  "flashcell": { Component: FlashCellSection, title: <>How flash stores a bit — the floating gate</>, sub: <>One level below the FTL: the physics. A narrated zoom to a single floating-gate transistor, where electrons are tunnelled through insulating oxide and trapped so the bit survives with no power. Program it, read it by its threshold shift, erase it, and watch the oxide wear out — the reason SLC lasts ~100k cycles and QLC only ~1k.</> },
  "gpu": { Component: GpuSection, title: <>GPU / SIMT — how parallel compute wins or stalls</>, sub: <>A GPU runs threads in lockstep groups of 32 (a warp), all executing the same instruction each cycle. That makes it brilliant at data-parallel work and brittle in two ways: a branch that splits a warp serializes both paths (divergence), and scattered memory accesses explode into many transactions instead of one (coalescing). Pick a branch pattern and a memory access pattern and watch efficiency soar or collapse.</> },
  "cpucache": { Component: CpuCacheSection, title: <>The CPU cache — sets, ways &amp; the address split</>, sub: <>The small fast SRAM that hides main memory's ~100 ns latency behind ~1 ns hits, by exploiting locality. A physical address splits into tag / set-index / byte-offset; the index picks a set, and the tag is compared against every way in it — a hit is fast, a miss fetches the 64-byte line and evicts the least-recently-used way. Change the associativity and run access patterns to watch conflict misses appear on a direct-mapped cache and vanish on a set-associative one.</> },
  "oooexec": { Component: OooExecSection, title: <>Out-of-order execution</>, sub: <>Why a modern CPU runs your instructions in a different order than you wrote them — and still gets the right answer. An in-order core stalls everything behind a cache-missing load; an out-of-order core issues each instruction the moment its inputs are ready, and register renaming removes false dependencies so only true data dependencies constrain it. Results still retire in program order. Edit a program and watch independent work slide under a load stall.</> },
  "rope": { Component: RopeSection, title: <>The rope — how editors edit huge text fast</>, sub: <>Inserting a character in the middle of a flat string is O(n) — every later byte shifts. A rope stores the document as the leaves of a balanced tree, where each internal node caches the length of its left subtree, so index, split, insert, and delete are all O(log n). Edits rewrite only one root-to-leaf path, and because nodes are immutable and shared, every past version stays alive for free undo. Edit the text and watch the tree splice.</> },
  "gapbuffer": { Component: GapBufferSection, title: <>The gap buffer — how Emacs edits text</>, sub: <>The whole document lives in one array with a run of empty slots — the gap — parked at the cursor. Typing drops a character into the gap in O(1), no shifting. Backspace and delete-forward just grow the gap. The only costly move is relocating the cursor, which slides the gap there by copying the characters it passes over (O(distance)). It bets that edits cluster at one point — and usually wins. Type, delete, and drag the cursor to watch the gap move.</> },
  "fastinvsqrt": { Component: FastInvSqrtSection, title: <>The fast inverse square root</>, sub: <>The most famous 20 lines in game programming — Quake III's trick for computing 1/√x with no sqrt and no division. A float's raw bits, read as an integer, are almost exactly a scaled log₂(x); so a single integer subtraction from the magic constant 0x5f3759df computes x^(−1/2) in log space, and one Newton step polishes the ~3.4% guess to ~0.17%. Pick x and watch the bits become the answer.</> },
  "kahan": { Component: KahanSumSection, title: <>Kahan summation — adding floats without losing accuracy</>, sub: <>A float has ~15–16 significant digits, so adding a small number to a large running total drops the small one's low bits — sum a million values and the lost bits become a real error. Kahan summation carries a compensation term that remembers what each addition dropped and folds it back, keeping the error near one rounding unit no matter how many terms. Watch the naive total drift while Kahan stays pinned to the true sum.</> },
  "cordic": { Component: CordicSection, title: <>How calculators do trig (CORDIC)</>, sub: <>How a pocket calculator or an FPGA with no multiplier computes cos and sin — with only bit-shifts and additions. cos θ and sin θ are the coordinates of a unit vector at angle θ, so CORDIC rotates a vector to θ by a fixed sequence of micro-rotations whose tangents are powers of two (each a shift-and-add), choosing + or − to home in like a binary search; a constant gain K≈0.6073 is cancelled by starting at (K,0). Real CORDIC, verified to five digits. Turn the dial and watch the vector spiral to your angle.</> },
  "karatsuba": { Component: KaratsubaSection, title: <>Karatsuba multiplication — beating n²</>, sub: <>Schoolbook multiplication of two n-digit numbers costs n² single-digit multiplies. In 1960 Karatsuba found you only need three half-size products, not four — because the middle term ad+bc equals (a+b)(c+d) − ac − bd. Recurse and n² collapses to n^1.585, which is why every big-integer library (and thus RSA/ECC key math) uses it. Enter two numbers and watch the recursion split into threes.</> },
  "simanneal": { Component: SimAnnealSection, title: <>Simulated annealing — escaping local minima</>, sub: <>Greedy optimization always moves downhill, so it gets trapped in the first local minimum it finds. Simulated annealing borrows from metallurgy: keep a temperature that starts high and cools, accepting uphill moves with probability exp(−ΔE/T) so the search can climb out of traps early, then settle as it cools. It's the workhorse for rugged combinatorial problems — chip placement, routing, scheduling. Watch greedy get stuck while annealing reaches the deep valley (change the seed — it's probabilistic).</> },
  "alphabeta": { Component: AlphaBetaSection, title: <>How game AI searches (alpha-beta)</>, sub: <>The algorithm behind classical game engines — chess, checkers, Othello. Minimax values a position assuming best play (you maximize, the opponent minimizes); alpha-beta pruning gets the identical value while skipping branches it can prove cannot change the decision, so with good move ordering it searches about twice as deep for the same cost. Real minimax + alpha-beta on a game tree (verified: same value as full minimax, fewer nodes, identical on thousands of random trees). Toggle between them and watch the pruned branches grey out.</> },
  "backprop": { Component: BackpropSection, title: <>How a neural network learns (backprop)</>, sub: <>The algorithm behind all of deep learning. A net is a function with weight knobs; training finds the knobs that make the output match the target. Backpropagation computes the gradient (∂loss/∂weight) for every weight in ONE backward sweep via the chain rule, reusing the forward values — so all gradients cost about one forward pass, which is why training huge nets is feasible. Real 2-2-1 sigmoid net, verified by a gradient check (analytic backprop matches finite-difference to 5 digits). Press train and watch the loss fall.</> },
  "word2vec": { Component: EmbeddingSection, title: <>How word embeddings work (word2vec)</>, sub: <>How words become vectors where meaning is geometry — the representation underneath semantic search, recommendations, and the input layer of every language model. Trained so words in similar contexts get similar vectors, with a startling result: relationships become consistent directions, so king − man + woman ≈ queen. A 2-D illustration (real embeddings use hundreds of dimensions), verified: all four analogies land on the expected word and the gender direction is parallel across pairs. Pick an analogy and watch a − b + c land on its nearest word.</> },
  "vectorsearch": { Component: VectorSearchSection, title: <>How vector search finds nearest embeddings (HNSW)</>, sub: <>How a vector database finds the nearest embeddings to a query — the retrieval behind semantic search and RAG — without comparing against millions of vectors. Build a proximity graph linking each vector to its nearest neighbors, then navigate it: hop toward the query, keeping the best ef candidates (a beam search). HNSW stacks layers — sparse top for long jumps, dense below — for near O(log n). Real best-first search verified: recall rises 91%→99.8% as ef grows, visiting under 20% of the vectors. Move the query and watch it navigate.</> },
  "attention": { Component: AttentionSection, title: <>How attention works (transformers)</>, sub: <>The core of every transformer and LLM. Each token emits a query, a key, and a value; a token attends to another by how well its query matches that key (a dot product), the scores are scaled and softmaxed into weights that sum to 1, and the token’s new representation is the weighted blend of everyone’s values. Real scaled dot-product attention over a 6-token toy: “river” attends to the water words, “money” to the finance words, and ambiguous “bank” to both. Pick the query token and watch the weights and the blended output.</> },
  "hamming": { Component: HammingSection, title: <>Hamming(7,4) — error correction that points at the mistake</>, sub: <>The first error-correcting code (Hamming, 1950). Four data bits become a seven-bit codeword with parity bits at positions 1, 2, 4. Each parity bit checks the positions whose index has that bit set, so the three checks together read out the binary index of any single flipped bit — the syndrome is the error's address. Toggle the data, corrupt a bit in transit, and watch the code locate and fix it.</> },
  "bresenham": { Component: BresenhamSection, title: <>Bresenham's line algorithm — drawing with integers</>, sub: <>How a computer draws a straight line on a grid of pixels (Bresenham, IBM, 1962). The naive way computes y = y0 + slope·(x−x0) and rounds — a floating-point multiply per pixel. Bresenham tracks a single integer error term and decides each step with only additions and comparisons, lighting up the exact same pixels with no multiply, divide, float, or round. Still in every GPU. Click the grid to move the endpoint.</> },
  "raytracing": { Component: RaytraceSection, title: <>How ray tracing renders an image</>, sub: <>The way photorealistic 3D images are made: shoot a ray from the eye through every pixel, find what it hits, and shade that point by the light. A narrated walk through ray-object intersection, cosine shading, shadow rays (a second ray to the light), and reflection by recursion — beside a real ray-traced image. Drag the light and watch every pixel re-trace.</> },
  "rasterize": { Component: RasterizeSection, title: <>How a GPU rasterizes a triangle</>, sub: <>The other way to turn 3D into pixels, and the one real-time games use: instead of a ray per pixel, take each triangle and find which pixels it covers. A narrated walk through the edge-function inside test, barycentric colour interpolation, and the z-buffer — beside a real rasterized triangle. Slide a vertex and watch it re-rasterize, colours blending smoothly from the corners.</> },
  "msaa": { Component: MsaaSection, title: <>How GPUs smooth jagged edges (MSAA)</>, sub: <>Why slanted edges staircase into jaggies — each pixel is fully inside or outside a triangle — and how multisample antialiasing fixes it cheaply. Supersampling renders at N× and averages, but shades N× too. MSAA takes N coverage samples per pixel (is each inside?) but shades once, then blends each pixel by its coverage — smooth edges at close to no extra shading, since only edge pixels aren’t fully in/out. Verified: 4-sample coverage matches the true area coverage. Toggle it on and off and tilt the edge.</> },
  "verlet": { Component: VerletSection, title: <>How game physics simulates rope &amp; cloth</>, sub: <>The Verlet integration behind cloth, rope, hair, and ragdolls. Store only positions — now and last frame — and their difference IS the velocity, so momentum is free. Advance each point by its momentum plus gravity, then satisfy distance constraints by moving points back to their rest length (relaxation). No stored velocity, no springs, and unconditionally stable. A live rope you can nudge; turn the relaxation passes up to stiffen it, down to make it rubbery.</> },
  "barneshut": { Component: BarnesHutSection, title: <>How galaxies simulate gravity fast (Barnes-Hut)</>, sub: <>Simulating gravity among n bodies is O(n²) — every star pulls on every other. Barnes-Hut cuts it to O(n log n) using one fact: a distant clump of stars pulls almost exactly like a single body at its center of mass. A quadtree summarizes each region’s mass and center of mass; to find a body’s force you walk the tree, lumping any node far enough that its width ÷ distance is below θ, and opening the rest. Verified against the exact sum: ~2% force error at θ=0.5. Turn the θ dial and watch the approximation boxes grow.</> },
  "raymarch": { Component: RayMarchSection, title: <>How ray-marching renders with math (SDF)</>, sub: <>How Shadertoy and demoscene intros render whole worlds with no meshes — the scene is a signed distance function (for any point, the distance to the nearest surface), and a ray steps forward by that distance each time (sphere tracing), safe because nothing is closer. Big steps in open space, small near surfaces, converging in a handful of iterations. Real sphere tracing on a 2-D slice: aim the ray and watch it leap, creep, and converge (or miss). The field also gives normals, CSG, soft shadows, and AO almost for free.</> },
  "convexhull": { Component: ConvexHullSection, title: <>Convex hull — the rubber band around your points</>, sub: <>The smallest convex polygon enclosing a set of points — the shape a rubber band makes snapped around a bed of nails. Andrew's monotone chain sorts the points, then sweeps once for the lower hull and once for the upper, using the cross product (turn left / right / straight — no trig) to pop any point that would make a dent. O(n log n), and that's optimal. Click to add points and watch the hull re-form.</> },
  "sat": { Component: SatSection, title: <>How games detect collisions (SAT)</>, sub: <>The exact test behind convex collision detection: two convex shapes are disjoint if and only if some axis exists on which their projected shadows don’t overlap. For polygons only the edge normals need checking — one gap on any axis proves no collision, and if every axis overlaps, the smallest overlap gives the minimum push to separate them. Real SAT verified against a brute-force oracle. Slide a triangle through a square and watch the shadows open a gap.</> },
  "spatialhash": { Component: SpatialHashSection, title: <>How games skip the n² collision test (spatial hash)</>, sub: <>SAT is the exact test — but running it on every pair of objects is O(n²), which explodes. The broad phase is a cheap pre-filter: overlay a uniform grid, bucket each object into its cell, and only test pairs that share a cell, since anything farther can’t touch. Verified against a brute-force oracle: it finds the identical collisions from about 1% of the pair-tests (248 vs 19,900 for 200 objects). Toggle brute force vs the grid and watch the candidate count collapse while the collisions stay the same.</> },
  "marchsquares": { Component: MarchSquaresSection, title: <>Marching squares — grid of numbers to smooth contour</>, sub: <>How you turn a scalar field (elevation, brightness, density) into the contour line where it equals a threshold — the coastline between above and below. Each cell's four corners give one of 16 cases; the contour crosses the edges separating an above corner from a below one, cut at the linear-interpolated crossing for smoothness. Every cell is independent (great for the GPU), and it's the 2-D sibling of marching cubes. Slide the threshold and watch the blobs merge.</> },
  "voronoi": { Component: VoronoiSection, title: <>Voronoi diagram — the plane split by nearest site</>, sub: <>Carve a plane into one cell per site, where every point belongs to whichever site is nearest — the honeycomb you see in cracked mud, giraffe coats, and cell-tower coverage maps. Each boundary is the perpendicular bisector of two sites, so every cell is convex, and the whole diagram is the exact dual of the Delaunay triangulation. Click to add sites; switch the distance metric (Euclidean / Manhattan / Chebyshev) to reshape the cells.</> },
  "delaunay": { Component: DelaunaySection, title: <>Delaunay triangulation — fat triangles, no slivers</>, sub: <>Connect scattered points into triangles that avoid slivers: the Delaunay triangulation maximizes the smallest angle, giving triangles as close to equilateral as the points allow — essential for finite-element meshes, terrain, and interpolation. Its defining rule is the empty-circumcircle property (no point inside any triangle's circumcircle), and it's the exact dual of the Voronoi diagram. Built here with Bowyer-Watson. Click to add points; toggle the Voronoi dual to see the connection.</> },
  "montgomery": { Component: MontgomerySection, title: <>Montgomery multiplication — modular multiply without division</>, sub: <>RSA and elliptic-curve crypto compute a·b mod n for a huge modulus thousands of times, and the slow, timing-leaky part is the "mod n" — a full division. Montgomery's trick works in a coordinate system where numbers are held as a·R mod n, so reduction (REDC) needs only multiplies, adds, a bit-mask (mod R) and a shift (÷R) — never a division by n, and the same fixed operations regardless of the values (constant-time). Enter a modulus and two numbers and watch a·b mod n fall out with only masks and shifts.</> },
  "twosat": { Component: TwoSatSection, title: <>2-SAT — boolean satisfiability in linear time</>, sub: <>General SAT is NP-complete, but restrict every clause to two literals and it becomes solvable in linear time by a beautiful reduction to graph theory. A clause (a ∨ b) is two implications (¬a ⇒ b, ¬b ⇒ a); build the implication graph and the formula is unsatisfiable exactly when some variable and its negation land in the same strongly-connected component. One SCC pass decides it and builds a satisfying assignment. Pick a formula and watch the components and verdict.</> },
  "perlin": { Component: PerlinSection, title: <>Perlin noise — smooth randomness for procedural worlds</>, sub: <>The gradient-noise algorithm (Ken Perlin, 1983, soon after working on Tron) behind procedural terrain, clouds, fire, and marble textures. Instead of a random value per pixel (harsh white noise), it assigns a random gradient to each grid point and blends the neighbors with the fade curve 6t⁵−15t⁴+10t³ — smooth everywhere, and exactly zero at the lattice points. Stack octaves at doubling frequency for fractal detail. Reseed, zoom, and add octaves to grow a landscape.</> },
  "poisson": { Component: PoissonSection, title: <>Poisson-disk sampling — evenly-spaced randomness</>, sub: <>Scatter points that look random but never clump: every pair at least r apart, yet the area stays evenly covered. This "blue noise" is what rendering, stippling, and procedural scattering want — uniform random points bunch up and leave holes, causing splotchy shadows and grainy antialiasing. Bridson's algorithm builds it in O(n) by firing candidate darts into the ring between r and 2r around active points, with an O(1) grid spacing-check. Flip blue vs white noise and watch the min distance.</> },
  "transistor": { Component: TransistorSection, title: <>Transistors &rarr; logic gates</>, sub: <>The bottom of the stack. A transistor is a voltage-controlled switch: NMOS conducts when its gate is high, PMOS when low. Wire a PMOS pull-up and NMOS pull-down together and you get a CMOS gate — an inverter, a NAND, a NOR. And NAND alone is universal: every other gate is built from it. Toggle inputs to watch the transistors conduct, then build any gate from NAND. Everything above — the adder, the ALU, the flip-flop — is just billions of these.</> },
  "knapsack": { Component: KnapsackSection, title: <>0/1 Knapsack (dynamic programming)</>, sub: <>Pick a subset of items to maximize value within a weight budget — where greedy fails and DP wins. Watch the table fill row by row, read the answer off the bottom-right corner, and follow the highlighted backtrack path to see which items were chosen. The greedy-by-ratio result is shown losing alongside.</> },
  "deployments": { Component: DeployStratSection, title: <>Deployment strategies</>, sub: <>How you ship v2 without taking the service down — and the risk/speed/cost trade-offs between them. Step through recreate, rolling, blue-green, and canary: watch the fleet flip versions, the router split traffic, and the availability meter reveal who feels the rollout.</> },
  "healthcheck": { Component: HealthCheckSection, title: <>Liveness vs readiness probes</>, sub: <>The Kubernetes distinction that, gotten wrong, causes restart storms. Readiness decides whether a pod gets traffic; liveness decides whether it gets killed and restarted. Step through scenarios — including the anti-pattern where a slow-under-load check on the liveness probe crashloops the whole fleet.</> },
  "autoscale": { Component: AutoscaleSection, title: <>Horizontal autoscaling (HPA)</>, sub: <>How a service grows and shrinks its replica count to track load, from one simple formula: desired = ceil(replicas × metric / target). Step through a load series and watch replicas chase demand — scaling up instantly, scaling down only after a stabilization window rides out brief dips.</> },
  "usl": { Component: UslSection, title: <>Universal Scalability Law</>, sub: <>Why adding workers eventually stops helping — and then starts hurting. Amdahl's law says a serial fraction caps speedup; the USL adds a coherency term for the coordination cost between workers (which grows with the number of pairs, ∝ N²), so throughput peaks at an optimal concurrency and goes retrograde past it. Drag contention α and coherency β and watch the curve bend back down.</> },
  "pid": { Component: PidSection, title: <>PID controller</>, sub: <>The feedback loop behind cruise control, thermostats, drones — and, increasingly, autoscaling and congestion control. It drives a process to a setpoint from three terms on the error: proportional (fast, but leaves a droop), integral (erases the droop), derivative (damps overshoot). Tune Kp, Ki, Kd and watch a positioning system overshoot, droop, or settle cleanly — the same trade-offs that make aggressive autoscaling oscillate.</> },
  "kalman": { Component: KalmanSection, title: <>How a Kalman filter tracks</>, sub: <>The optimal way to track a moving thing from noisy measurements — it flew Apollo to the Moon and now smooths your GPS dot, stabilises drones, and fuses your phone’s sensors. Each step it predicts where the thing should be from its motion, then corrects with the new measurement, weighting the two by their uncertainties (the Kalman gain). Real 1D constant-velocity filter: watch the estimate hug the truth while the raw sensor scatters, and slide the sensor/model noise to see the filter trust one or the other.</> },
  "slo": { Component: SloSection, title: <>SLOs &amp; error budgets</>, sub: <>The math that turns "be reliable" into a number you can spend. Pick an availability target, see the error budget it buys (downtime allowed per month), and watch the release policy flip from "ship" to "freeze" when it runs out. The burn-rate panel turns a current error rate into how fast you're spending and which alerts page you.</> },
  "tracing": { Component: TracingSection, title: <>Distributed tracing</>, sub: <>Follow one request as it fans out across services, and see where the time actually went. Each span is a bar on the waterfall — positioned by when it started, indented by call depth — and the self-time breakdown points straight at the real bottleneck instead of a guess.</> },
  "featureflags": { Component: FeatureFlagSection, title: <>Feature flags</>, sub: <>Decouple deploy from release: the code already shipped, so turning a feature on is a config change that takes effect in seconds. Drag the rollout and watch users flip on in a stable order, force a cohort on with a targeting rule, or hit the kill switch and everyone goes off instantly — no redeploy.</> },
  "gracefulshutdown": { Component: GracefulShutdownSection, title: <>Graceful shutdown &amp; connection draining</>, sub: <>How to take an instance down without dropping the requests it's already serving. SIGTERM lands; fail readiness so new traffic stops, drain in-flight requests, then exit. Drag the grace period below your longest request and watch the orchestrator force-kill the stragglers into 5xxs — the unglamorous half of every zero-downtime claim.</> },
  "idempotency": { Component: IdempotencySection, title: <>Idempotency keys</>, sub: <>How an API makes "charge $100" safe to retry. The network only promises at-least-once delivery, so clients retry lost requests — and without protection, the retry charges again. Watch the same scenario run down two paths: without a key it double-charges; with a key the server replays the stored result, exactly once.</> },
  "loadshed": { Component: LoadShedSection, title: <>Load shedding &amp; backpressure</>, sub: <>Under overload, rejecting work fast beats queuing it. Same demand, two servers: one with a bounded queue that sheds the excess, one that queues everything. Drag the offered load past the service rate and watch the unbounded server's backlog explode into congestion collapse while the shedding one holds steady useful throughput.</> },
  "bulkhead": { Component: BulkheadSection, title: <>Bulkhead isolation</>, sub: <>Why one slow dependency can take down your whole service — and how per-dependency resource pools contain the damage. From a shared thread pool, a sick dependency's piled-up requests consume every slot, starving healthy calls too. Drag a dependency's latency up and compare a shared pool (total outage) to bulkheads (only the sick one degrades).</> },
  "chaos": { Component: ChaosSection, title: <>Chaos engineering</>, sub: <>Deliberately break one thing to discover how far the damage spreads — and prove your resilience contains it. Click a service to kill it and watch the failure cascade; a hard dependency drags its callers down, a resilient one absorbs it. Flip on resilience shields and watch the blast radius shrink.</> },
  "singleflight": { Component: SingleFlightSection, title: <>Request coalescing (singleflight)</>, sub: <>Stopping a cache miss from becoming a stampede. When a hot key expires, every concurrent request misses at once and they all hit the backend for the same value. Singleflight lets the first compute it while the rest wait and share the result — N simultaneous misses become one backend call.</> },
  "branchpredict": { Component: BranchPredictSection, title: <>Branch prediction</>, sub: <>How a CPU guesses which way a branch goes before it knows, so the pipeline doesn't stall. Step a 2-bit saturating counter through a branch-outcome pattern and watch the hysteresis at work — then compare its mispredictions against a 1-bit predictor on the loop-exit pattern, where the extra bit halves the misses.</> },
  "spectre": { Component: SpectreSection, title: <>Spectre — leaking secrets through speculation</>, sub: <>How the 2018 attack reads memory it isn't allowed to, by abusing speculative execution. The CPU runs ahead past a bounds check it mispredicts, speculatively reads a secret byte, and leaves a trace in the cache — which timing (Flush+Reload) then recovers. Step through the leak and watch the secret appear byte by byte, then flip on the lfence barrier and watch it stop.</> },
};
