// GENERATED section registry chunk 2 — see sections/registry.tsx. One data row per section: title, sub, component.
import type { SectionEntry } from './registry';
import { ChandySection } from '../ChandySection';
import { LpmSection } from '../LpmSection';
import { VitSection } from '../VitSection';
import { SctpSection } from '../SctpSection';
import { MptcpSection } from '../MptcpSection';
import { PageReplaceSection } from '../PageReplaceSection';
import { RetrySection } from '../RetrySection';
import { SmuggleSection } from '../SmuggleSection';
import { PhiSection } from '../PhiSection';
import { CtSection } from '../CtSection';
import { CertTransSection } from '../CertTransSection';
import { SigstoreSection } from '../SigstoreSection';
import { AttestSection } from '../AttestSection';
import { CondSection } from '../CondSection';
import { IsoSection } from '../IsoSection';
import { VxSection } from '../VxSection';
import { SriSection } from '../SriSection';
import { AeSection } from '../AeSection';
import { HintedHandoffSection } from '../HintedHandoffSection';
import { ReadRepairSection } from '../ReadRepairSection';
import { VrrpSection } from '../VrrpSection';
import { TtSection } from '../TtSection';
import { EcnSection } from '../EcnSection';
import { DotxSection } from '../DotxSection';
import { IpsecSection } from '../IpsecSection';
import { WireGuardSection } from '../WireGuardSection';
import { CbSection } from '../CbSection';
import { EcmpSection } from '../EcmpSection';
import { RtmSection } from '../RtmSection';
import { X3dhSection } from '../X3dhSection';
import { ThresholdSection } from '../ThresholdSection';
import { TfoSection } from '../TfoSection';
import { ZeroRttSection } from '../ZeroRttSection';
import { RaftLogSection } from '../RaftLogSection';
import { AvlSection } from '../AvlSection';
import { SplayTreeSection } from '../SplayTreeSection';
import { TreapSection } from '../TreapSection';
import { PieceTableSection } from '../PieceTableSection';
import { EncodingSection } from '../EncodingSection';
import { FloatSection } from '../FloatSection';
import { GrayCodeSection } from '../GrayCodeSection';
import { JpegSection } from '../JpegSection';
import { SeamCarveSection } from '../SeamCarveSection';
import { MotionCompSection } from '../MotionCompSection';
import { Mp3Section } from '../Mp3Section';
import { DitherSection } from '../DitherSection';
import { GammaSection } from '../GammaSection';
import { ColorSpaceSection } from '../ColorSpaceSection';
import { HdrSection } from '../HdrSection';
import { VarintSection } from '../VarintSection';
import { Base58Section } from '../Base58Section';
import { HuffmanSection } from '../HuffmanSection';
import { GolombRiceSection } from '../GolombRiceSection';
import { EliasCodeSection } from '../EliasCodeSection';
import { GorillaSection } from '../GorillaSection';
import { CobsSection } from '../CobsSection';
import { ErrorDetectSection } from '../ErrorDetectSection';
import { BarcodeSection } from '../BarcodeSection';
import { QrSection } from '../QrSection';
import { IdentitySection } from '../IdentitySection';
import { JwtSection } from '../JwtSection';
import { AttacksSection } from '../AttacksSection';
import { RoutingSection } from '../RoutingSection';
import { DnsJourneySection } from '../DnsJourneySection';
import { SubnetSection } from '../SubnetSection';

export const chunk2: Record<string, SectionEntry> = {
  "chandy": { Component: ChandySection, title: <>Chandy-Lamport snapshot</>, sub: <>Record a consistent global state of a distributed system with no shared clock — using marker messages over FIFO channels. Step through a two-account bank and watch the snapshot capture the money caught in flight, keeping the books balanced.</> },
  "viterbi": { Component: VitSection, title: <>Viterbi / convolutional codes</>, sub: <>Forward error correction: a rate-1/2 encoder doubles each bit, and the Viterbi decoder walks a trellis to recover the most-likely message. Click a received bit to inject an error and watch it get corrected — no retransmission.</> },
  "sctp": { Component: SctpSection, title: <>SCTP multi-homing</>, sub: <>The transport that survives a dead network path. An association binds multiple addresses per endpoint and fails over to an alternate when a path dies — no reconnect, no lost connection. Fire timeouts and watch it reroute, then see the stateless cookie handshake.</> },
  "mptcp": { Component: MptcpSection, title: <>Multipath TCP</>, sub: <>One TCP connection spread across several network paths at once — your phone using Wi-Fi and cellular together. The stream is striped across subflows, each byte carrying a connection-level Data Sequence Number so segments reassemble in order despite racing across paths. Toggle a path off and watch every byte reroute onto the survivor, connection intact.</> },
  "pagereplace": { Component: PageReplaceSection, title: <>Page replacement</>, sub: <>When memory is full, which page gets evicted? Compare FIFO, LRU, Clock and Optimal on a reference string — count the page faults and watch FIFO's Belady anomaly, where more frames cause more faults.</> },
  "retry": { Component: RetrySection, title: <>Retry &amp; circuit breaker</>, sub: <>How resilient clients avoid making an outage worse. Compare backoff strategies and watch jitter flatten a thundering-herd retry storm, then see a circuit breaker trip open, shed load, and probe its way back to healthy.</> },
  "smuggle": { Component: SmuggleSection, title: <>HTTP request smuggling</>, sub: <>When a front-end proxy and back-end server disagree on how to delimit a request body, the leftover bytes get smuggled onto the next victim's request. Watch CL.TE and TE.CL desyncs split the same bytes at different offsets.</> },
  "phiaccrual": { Component: PhiSection, title: <>Failure detectors (φ-accrual)</>, sub: <>How distributed systems decide a peer is dead without a brittle fixed timeout. A continuous suspicion level adapts to the link's jitter — drag the threshold and compare it against a naive timeout across a GC pause and a real crash.</> },
  "certtrans": { Component: CertTransSection, title: <>Certificate Transparency</>, sub: <>Any of hundreds of CAs can issue a cert for your domain, and before Certificate Transparency you’d never know a mis-issued one existed. CT forces every cert into public, append-only Merkle logs — so a rogue cert is either rejected (no proof it was logged) or public (logged, and your monitor catches it). Play the rogue CA and watch the dilemma, with a live inclusion proof putting the forged cert in the log.</> },
  "sigstore": { Component: SigstoreSection, title: <>Sigstore — keyless software signing</>, sub: <>Signing releases with a long-lived private key is how a compromised maintainer (xz) or build server (SolarWinds) poisons everyone downstream. Sigstore removes the key: sign with an ephemeral keypair, prove your <strong>identity</strong> over OIDC so <strong>Fulcio</strong> issues a 10-minute cert, and log it in <strong>Rekor</strong> (a transparency log). The twist is verification — the cert is expired by the time you check, so trust comes from the identity and the log’s timestamp, not the cert. Toggle the checks and watch a wrong identity or a missing log entry get rejected.</> },
  "attest": { Component: AttestSection, title: <>Remote attestation — trusting a machine you don’t control</>, sub: <>Confidential computing’s strange promise: run on someone else’s server, and not even they can read your data. A <strong>TEE</strong> (Intel SGX/TDX, AMD SEV, a confidential VM) encrypts an enclave’s memory in hardware — but you only trust it if the silicon proves what booted. The CPU signs a <strong>quote</strong> carrying a <strong>measurement</strong> (code hash) and your <strong>nonce</strong>, chaining to the vendor’s root. Toggle the three checks — genuine hardware, expected code, fresh nonce — and watch a fake TEE, a modified binary, or a replayed quote get rejected before any secret is released. The same chain-of-trust as a TLS cert, but the leaf is a measurement of software.</> },
  "consttime": { Component: CtSection, title: <>Timing attacks</>, sub: <>Why comparing a secret with <code>==</code> is a vulnerability. A naive compare leaks the matching-prefix length through its running time — watch the byte-by-byte attack walk the secret out of it, and watch constant-time compare give the attacker nothing.</> },
  "conditional": { Component: CondSection, title: <>Conditional &amp; range requests</>, sub: <>ETags and validators let HTTP skip work: 304 Not Modified reuses a cached body, 206 Partial Content resumes a download, and If-Match prevents lost updates. Build requests and watch the server's status and bytes-sent change.</> },
  "siteisolation": { Component: IsoSection, title: <>Site isolation</>, sub: <>How a page earns its own process and re-unlocks SharedArrayBuffer post-Spectre. Set COOP and COEP headers and watch crossOriginIsolated resolve, plus which cross-origin subresources are still allowed to embed.</> },
  "vxlan": { Component: VxSection, title: <>VXLAN overlay</>, sub: <>How clouds run millions of isolated tenant L2 networks over one shared L3 fabric. Watch a VTEP wrap a tenant frame in VXLAN/UDP/IP, learn inner-MAC → remote-VTEP to turn floods into unicast, and keep VNIs fully isolated.</> },
  "sri": { Component: SriSection, title: <>Subresource Integrity</>, sub: <>How a page pins the exact bytes of a CDN script so a compromised file can't run. Edit the served file or simulate a CDN compromise and watch the browser re-hash it and block the mismatch.</> },
  "antientropy": { Component: AeSection, title: <>Read-repair &amp; anti-entropy</>, sub: <>How leaderless replicas heal divergence. Make a replica diverge and watch a Merkle-tree comparison drill down only through differing branches to pinpoint the bad keys in O(log n), plus read-repair on the quorum-read path.</> },
  "hintedhandoff": { Component: HintedHandoffSection, title: <>Hinted handoff</>, sub: <>How Dynamo-style stores keep accepting writes while a replica is down. The value is parked as a "hint" on the next healthy node — counting toward the write quorum (a sloppy quorum) — and replayed when the owner recovers. Knock nodes down, tune N and W, and watch writes stay available, then heal.</> },
  "readrepair": { Component: ReadRepairSection, title: <>Read repair — fix-on-read</>, sub: <>How an eventually-consistent store (Dynamo, Cassandra) heals stale replicas as a side effect of ordinary reads: query R replicas, return the freshest, and write it back to the ones that were behind. Build a read set, watch stale replicas get repaired — and see the stale read you get when the read set misses the newest write, the reason strong reads want R + W &gt; N.</> },
  "vrrp": { Component: VrrpSection, title: <>VRRP redundancy</>, sub: <>First-hop redundancy: a group of routers shares one virtual gateway IP so a host is never stranded by a single failure. Toggle routers and watch mastership move, with a priority skew that prevents two backups colliding.</> },
  "truetime": { Component: TtSection, title: <>TrueTime &amp; commit-wait</>, sub: <>How Spanner orders transactions globally using real clocks with bounded uncertainty. Drag ε and watch the commit timestamp and the 2ε commit-wait that buys external consistency — then toggle it off to see ordering break.</> },
  "ecn": { Component: EcnSection, title: <>ECN marking</>, sub: <>How a router signals congestion by marking a packet instead of dropping it. Walk the CE→ECE→CWR signal and compare an ECN flow (marks, zero loss) against a drop-based one — same backoff, no retransmits.</> },
  "dot1x": { Component: DotxSection, title: <>802.1X / EAPOL</>, sub: <>Port-based network access control: a switch port stays blocked until your device passes EAP authentication against a RADIUS server. Step the exchange and watch the authenticator relay EAP and the port flip to authorized.</> },
  "ipsec": { Component: IpsecSection, title: <>IPsec ESP (VPN)</>, sub: <>How a VPN encrypts IP packets. Flip between transport and tunnel mode and watch the ESP wrapping, the encrypted region (opaque, never faked), what an eavesdropper can still read, and how the receiver demuxes by SPI to the right key.</> },
  "wireguard": { Component: WireGuardSection, title: <>WireGuard — cryptokey routing</>, sub: <>The modern VPN threw out the PKI: a peer is just a Curve25519 public key plus a list of <strong>AllowedIPs</strong>, and that one list does two jobs — it’s the outbound <strong>route</strong> (a destination goes to whichever peer’s AllowedIPs covers it, longest prefix) <em>and</em> the inbound <strong>ACL</strong> (a packet decrypted with a peer’s key is accepted only if its source is in that peer’s AllowedIPs). Send to different destinations and watch them route or drop; receive with different source IPs and watch spoofs get rejected. One list, bound to one key, replacing a routing table and a firewall.</> },
  "causalbcast": { Component: CbSection, title: <>Causal broadcast</>, sub: <>Delivering messages so a reply never appears before the message it answers, even when the network reorders them. Step through a reordered conversation and watch the receiver buffer and release messages to preserve causal order.</> },
  "ecmp": { Component: EcmpSection, title: <>ECMP load spreading</>, sub: <>How a router spreads traffic across equal-cost paths by hashing each flow — keeping flows in order while balancing load. Watch flows scatter, then see the polarization trap when cascaded routers share a hash seed.</> },
  "realtime": { Component: RtmSection, title: <>Realtime: SSE vs WebSocket</>, sub: <>Three ways to push server events to a browser — long-poll, SSE, and WebSocket — compared on one timeline. Drag the network delay and watch long-poll stall events that fire during its reconnect gap.</> },
  "x3dh": { Component: X3dhSection, title: <>X3DH key agreement</>, sub: <>How Signal starts an encrypted session with someone who's offline. Bob's prekey bundle plus Alice's ephemeral fold into four Diffie-Hellman results and one shared key — which Bob rederives later, no live handshake.</> },
  "threshsig": { Component: ThresholdSection, title: <>Threshold signatures</>, sub: <>A t-of-n signing key that no single party holds. Pick a coalition and watch partial signatures combine — via Lagrange interpolation — into one signature that verifies under the group key, while fewer than t signers fail.</> },
  "tfo": { Component: TfoSection, title: <>TCP Fast Open</>, sub: <>Shaving the handshake round-trip off repeat connections by sending request data right in the SYN — with a cookie to keep spoofers out. Compare normal TCP, the first cookie-fetching visit, and a 0-RTT repeat.</> },
  "zerortt": { Component: ZeroRttSection, title: <>0-RTT resumption &amp; the replay problem</>, sub: <>How TLS 1.3 and QUIC send your request in the very first packet — zero round trips to the first byte — using a resumption ticket from a prior visit. The sharp edge: that early data has no server freshness yet, so it can be replayed. Toggle first vs return visit, pick a method, and watch an attacker's replay be harmless for a GET and a double-charge for a POST.</> },
  "raftlog": { Component: RaftLogSection, title: <>Raft log replication</>, sub: <>How an elected leader makes every follower's log identical and decides when an entry is safely committed — including the subtle §5.4.2 rule that stops a majority-stored entry from being overwritten.</> },
  "avl": { Component: AvlSection, title: <>AVL tree</>, sub: <>A binary search tree that rebalances itself after every insert via rotations, so it never degrades into a linked list. Insert keys (or 7 sorted ones) and watch the balance factors and rotations keep it log-deep.</> },
  "splaytree": { Component: SplayTreeSection, title: <>Splay tree — the self-adjusting BST</>, sub: <>A binary search tree that rebalances around whatever you touch: every lookup rotates that node all the way to the root, so recently- and frequently-accessed keys stay near the top and cost O(1). No balance factors or colors — just "move what you touched up." Click nodes and watch the tree remold itself to your access pattern.</> },
  "treap": { Component: TreapSection, title: <>Treap — the randomized BST</>, sub: <>A binary search tree that stays balanced by accident, not by rules. Every node gets a random priority, and the tree maintains BST order on keys plus heap order on priorities at once — which, for random priorities, is a balanced tree with no rotations to track. Add keys (even a sorted run that would ruin a plain BST) and watch it stay shallow; because priorities come from a key hash, the shape depends only on the key set, not insertion order.</> },
  "piecetable": { Component: PieceTableSection, title: <>Piece table — how a text editor holds your document</>, sub: <>The structure VS Code (and historically Word) uses to edit text without ever moving the bytes. The original file is loaded once and never mutated; everything you type is appended to a separate buffer; and the document is just an ordered list of pieces — spans into those two immutable buffers. That's why edits are cheap and undo is nearly free. Insert and delete, and watch the pieces re-stitch while the buffers stay put.</> },
  "encoding": { Component: EncodingSection, title: <>Encoding</>, sub: <>How data is represented as bytes — type and watch it transform, for real.</> },
  "float": { Component: FloatSection, title: <>How a computer stores a fraction</>, sub: <>The reason 0.1 + 0.2 is not 0.3. A narrated walk through IEEE-754: binary scientific notation, the 32-bit layout (1 sign · 8 exponent · 23 mantissa), a worked decode of 0.15625, and why 0.1 repeats forever in binary and can only be rounded. Type any number and see its real bits and the value actually stored.</> },
  "graycode": { Component: GrayCodeSection, title: <>Why encoders use Gray code (one bit at a time)</>, sub: <>A rotary or optical encoder reads its position as bits, and plain binary flips several bits at a carry boundary (3→4 is 011→100) — so a mistimed read mid-transition can be garbage like 7 or 0. Gray code reorders the values so consecutive ones differ by exactly one bit, so any read is off by at most one. Build it by reflect-and-prefix, or gray(n)=n XOR (n≫1). Verified: every consecutive pair (incl. wrap) differs by one bit. Step the dial and compare binary vs Gray. Used in encoders, clock-domain counters, and Karnaugh maps.</> },
  "varint": { Component: VarintSection, title: <>Varint &amp; zigzag encoding</>, sub: <>How Protocol Buffers packs integers: seven data bits per byte plus a continuation flag, so small numbers cost one byte and you only pay for the magnitude you use. Type a value to see the bytes and their continuation bits — then meet the negative-number gotcha (a plain signed varint is always 10 bytes) and watch zigzag collapse it back to one.</> },
  "base58": { Component: Base58Section, title: <>Base58 &amp; Base58Check</>, sub: <>The encoding behind Bitcoin addresses and IPFS content IDs. Like Base64 but it drops the look-alike characters (0, O, I, l) so a human can transcribe it, and because 58 isn't a power of two it encodes the whole input as one big base-58 number. Base58Check wraps a version byte and a 4-byte double-SHA256 checksum so a mistyped address is caught before any coins move. Build a real address and watch the checksum catch a typo.</> },
  "huffman": { Component: HuffmanSection, title: <>Huffman coding</>, sub: <>Optimal prefix-free compression — type text and watch the tree build, frequent symbols get short codes, and the bitstream shrink below fixed-width.</> },
  "jpeg": { Component: JpegSection, title: <>How JPEG compresses an image</>, sub: <>The lossy compression behind almost every photo. A narrated walk through the discrete cosine transform (pixels → frequency coefficients), quantization (dividing and rounding so high-frequency detail becomes zero — the actual lossy step and most of the shrink), and decode. Real 8×8 DCT: slide the quality and watch coefficients vanish and the rebuilt block turn blocky.</> },
  "seamcarve": { Component: SeamCarveSection, title: <>How content-aware resize works (seam carving)</>, sub: <>Resize an image without distorting it: instead of cropping edges or squishing everyone thin, delete the pixels that matter least. Each pixel gets an energy (gradient magnitude); the least-energy connected seam (one pixel per row) is found by dynamic programming — M[r][c] = energy + min of the three above — and removed, repeatedly, so the picture narrows while the sun and tower stay intact. Verified in node: the DP’s min-seam equals a brute-force search over 400 grids (0 mismatch). It’s Photoshop’s Content-Aware Scale, and the same min-path DP as Viterbi and edit distance. Drag to remove seams and toggle the energy view.</> },
  "interframe": { Component: MotionCompSection, title: <>How video inter-frame compression works</>, sub: <>The temporal counterpart to JPEG, and why an hour of video fits on a phone. Instead of coding every frame whole, a P-frame predicts this frame from the previous one: real block-matching motion estimation finds each block’s motion vector (the offset to its best match), and only the tiny leftover residual is coded — DCT-quantized like a JPEG block, but nearly empty. Pan the camera and watch the vectors track it and the frame shrink to ~1–2%; drop in a new object and watch the residual spike (that’s when the encoder codes a fresh I-frame).</> },
  "mp3": { Component: Mp3Section, title: <>How MP3 shrinks audio (psychoacoustic masking)</>, sub: <>The ear’s counterpart to JPEG’s exploitation of the eye. A sound is a spectrum of frequencies, but you can’t hear all of them: there’s an absolute threshold of hearing (worst at low and very high frequencies), and a loud tone raises that threshold around itself so quieter neighbours become inaudible — masked. MP3 computes this threshold and drops every component beneath it. Real Terhardt hearing curve + a Bark-domain spreading function: slide the loud tone and watch its masking bump hide different quiet tones.</> },
  "dithering": { Component: DitherSection, title: <>How dithering fakes gray with black &amp; white</>, sub: <>How a photo appears on a display that can only draw black or white — e-ink, receipt printers, newsprint. Rounding each pixel to the nearer of black/white bands a gradient into flat blocks and loses all tone. Floyd–Steinberg keeps the tone by spreading each pixel’s rounding error onto its not-yet-drawn neighbours (7/16 right; 3/16, 5/16, 1/16 below), so a patch of two-colour dots averages back to the original gray. Real error-diffusion on a canvas: flip between threshold and dithering, and zoom in to see it’s just two colours.</> },
  "gamma": { Component: GammaSection, title: <>Why 128 isn’t half-bright (gamma)</>, sub: <>A pixel value of 128 emits only about 22% of full light, not 50% — displays are deliberately non-linear, because the eye resolves dark tones better, so images store brightness perceptually (value ≈ light^(1/2.2), sRGB). Half the light is value 188. The consequence: averaging, opacity, resizing, and blur done on raw pixel values are physically wrong and come out too dark; you must decode to linear light first. Real sRGB math, verified: naive average of black+white is 128, the correct one is 188.</> },
  "colorspace": { Component: ColorSpaceSection, title: <>Why RGB blends look muddy (OKLab)</>, sub: <>Averaging two vivid colors by their RGB values makes a muddy, too-dark midpoint, because RGB codes are gamma-encoded emitted light, not perception. OKLab (Ottosson 2020) is a perceptual color space — gamma-decode → LMS cones → cube root → L/a/b — so blending in it keeps the lightness even. Verified in node: the sRGB→OKLab→sRGB round-trip returns to 1.6e-6, sRGB red maps to Ottosson’s reference (0.628, 0.225, 0.126), and the sRGB gradient midpoint measures up to ~11% darker in perceived L than OKLab’s. It’s CSS Color 4’s oklch(). Compare the two blends and watch the lightness curve sag or stay straight.</> },
  "hdr": { Component: HdrSection, title: <>How HDR fits the sun on your screen (tone-mapping)</>, sub: <>A real scene runs from deep shadow to direct sun — a range of millions — but a screen shows only about 0 to 1. Clipping everything brighter than 1 to white destroys the highlights (the sky and sun become one flat blob). Tone-mapping compresses the whole range non-linearly instead: the Reinhard operator L/(1+L) sends 0→0 and ∞→1, keeping highlights distinct, like the retina does. Real synthetic HDR scene, verified: naive clip blows out most of the range while Reinhard keeps it ordered and visible. Then gamma-encodes (pairs with the gamma story).</> },
  "golombrice": { Component: GolombRiceSection, title: <>Golomb-Rice coding</>, sub: <>The variable-length integer code that's optimal when small values dominate — audio residuals, gaps between events, sparse bitmaps. Split a number into a quotient sent in unary and a remainder in k binary bits; tiny values get tiny codes. Tune the parameter k and watch the bits-per-value curve find its sweet spot.</> },
  "eliascode": { Component: EliasCodeSection, title: <>Elias γ/δ coding</>, sub: <>Parameter-free, self-delimiting codes for positive integers: write a number in binary so a decoder knows where it ends with no separator and no fixed width. γ prefixes the value with ⌊log2 n⌋ zeros as a unary length; δ encodes that length with γ itself, winning for larger numbers. Type a number to see it decompose, then feed a list of gaps and compare against fixed-width.</> },
  "gorilla": { Component: GorillaSection, title: <>Gorilla — time-series compression</>, sub: <>How monitoring systems (Prometheus, InfluxDB) store billions of metric points in a fraction of the space. Timestamps ride on delta-of-delta (regular intervals → one bit); values are XOR'd against the previous point (unchanged or similar → almost no bits). Pick a metric shape and watch a 128-bit-per-sample series collapse — losslessly.</> },
  "cobs": { Component: CobsSection, title: <>COBS — Consistent Overhead Byte Stuffing</>, sub: <>How you frame a raw byte stream so 0x00 can mark the end of a frame — even when the payload contains zeros. COBS removes every zero byte with a tiny, bounded overhead (⌊n/254⌋+1 bytes, never the doubling that escaping risks), leaving 0x00 free as the delimiter. Pick a payload and watch the zeros vanish into code bytes, then decode back exactly.</> },
  "errors": { Component: ErrorDetectSection, title: <>Error control</>, sub: <>How the wire catches — and sometimes repairs — flipped bits, from parity to CRC to Hamming.</> },
  "barcode": { Component: BarcodeSection, title: <>How a barcode works (UPC check digit)</>, sub: <>The bars are just 12 digits a laser can read, and the last one isn’t data — it’s a mod-10 check digit computed from the other eleven that exists only to catch errors. Real UPC-A encoding (L/R codes + guard bars, 95 modules) and the real formula (odd positions ×3 + even, completed to a multiple of 10). Click a digit and every single-digit error goes red — all caught. Then slip one past it: transpose two neighbours with the ⇄ handles, and swapping two that differ by 5 (the 2 and the 7) spells a different, still-valid product — the scanner accepts the wrong item. No checksum catches everything. The same idea as an ISBN, a credit card’s Luhn digit, and every packet checksum.</> },
  "qrcode": { Component: QrSection, title: <>How a QR code is built (Reed-Solomon + masking)</>, sub: <>A QR code is a little error-corrected data packet drawn as a grid. Build a real Version-1 (21×21) code end to end: the finder patterns a scanner locks onto, numeric data packed into codewords, Reed-Solomon ECC over GF(256) (why a torn or logo-covered code still reads), the zig-zag bit placement, and the mask chosen by a penalty score to keep the grid readable. The generator is verified in node against the ISO/IEC 18004 Annex-I example — data codewords 10 20 0C 56 61 80…, ECC A5 24 D4 C1 ED 36 C7 87 2C 55, all ten RS syndromes zero — and the component decodes its own matrix back to the digits (reading the mask from the format strip), an in-UI round-trip. Type your own digits and watch every layer recompute.</> },
  "identity": { Component: IdentitySection, title: <>Identity &amp; Auth</>, sub: <>Tokens, one-time codes, and delegated access — how systems prove who you are.</> },
  "jwt": { Component: JwtSection, title: <>JWT &amp; the alg=none attack</>, sub: <>The signed tokens behind most stateless auth: header.payload.signature, base64url-encoded, signed (not encrypted) so anyone can read the claims but only the key holder can forge a valid one. See a real HS256 token built with genuine HMAC-SHA256, toggle a claim to watch the signature change, then forge an alg=none token and watch a naive verifier accept the unsigned forgery while a strict one rejects it.</> },
  "attacks": { Component: AttacksSection, title: <>Attacks, made visible</>, sub: <>Real mechanisms with real numbers — each shown with its defence. For understanding, not harm.</> },
  "routing": { Component: RoutingSection, title: <>Routing &amp; paths</>, sub: <>Watch a link-state network compute shortest paths with Dijkstra — and reroute when a link cost changes.</> },
  "lpm": { Component: LpmSection, title: <>How a router forwards a packet</>, sub: <>Routing protocols learn the routes; this is the split-second data-plane decision that uses them. A narrated walk through longest-prefix match: a packet arrives, several prefixes in the forwarding table match at once, and the most specific (longest) one wins — found fast by walking a trie. Type any destination and watch which port it takes.</> },
  "dns": { Component: DnsJourneySection, title: <>DNS journey</>, sub: <>Follow a name down the delegation hierarchy — root to TLD to authoritative — and see why caching makes it fast.</> },
  "subnet": { Component: SubnetSection, title: <>Subnetting &amp; CIDR</>, sub: <>See where the network ends and the host begins — on the actual bits — then split a block into subnets.</> },
};
