// Elliptic-curve crypto on a tiny, fully-enumerable field, so the whole group is
// visible at once. The curve y² = x³ + ax + b (mod p) with point addition forms a
// finite cyclic group; multiplying the generator by k is easy, but recovering k
// from kG (the elliptic-curve discrete log) is hard — that asymmetry is ECDH and
// ECDSA. Default curve y² = x³ + 2x + 2 mod 17, G = (5,1), order 19 (Paar &
// Pelzl). Real modular arithmetic; teaching values only.

export interface Point { x: number; y: number } // affine point; O (infinity) is null
export type Pt = Point | null;

export interface Curve { a: number; b: number; p: number; G: Point }
export const CURVE: Curve = { a: 2, b: 2, p: 17, G: { x: 5, y: 1 } };

const mod = (n: number, p: number) => ((n % p) + p) % p;

/** Modular inverse via extended Euclid (small fields). */
export function modinv(a: number, p: number): number {
  let [old_r, r] = [mod(a, p), p];
  let [old_s, s] = [1, 0];
  while (r !== 0) {
    const qt = Math.floor(old_r / r);
    [old_r, r] = [r, old_r - qt * r];
    [old_s, s] = [s, old_s - qt * s];
  }
  if (old_r !== 1) throw new Error('no inverse');
  return mod(old_s, p);
}

export const onCurve = (P: Pt, c: Curve): boolean =>
  P === null || mod(P.y * P.y, c.p) === mod(P.x * P.x * P.x + c.a * P.x + c.b, c.p);

const eq = (P: Pt, Q: Pt) => (P === null ? Q === null : Q !== null && P.x === Q.x && P.y === Q.y);

/** The group law: chord-and-tangent addition, done modularly. */
export function add(P: Pt, Q: Pt, c: Curve): Pt {
  if (P === null) return Q;
  if (Q === null) return P;
  if (P.x === Q.x && mod(P.y + Q.y, c.p) === 0) return null; // P + (−P) = O
  let lam: number;
  if (eq(P, Q)) {
    lam = mod((3 * P.x * P.x + c.a) * modinv(2 * P.y, c.p), c.p); // tangent (doubling)
  } else {
    lam = mod((Q.y - P.y) * modinv(Q.x - P.x, c.p), c.p); // chord
  }
  const x = mod(lam * lam - P.x - Q.x, c.p);
  const y = mod(lam * (P.x - x) - P.y, c.p);
  return { x, y };
}

export const dbl = (P: Pt, c: Curve): Pt => add(P, P, c);

export interface MulStep { bit: number; op: 'double' | 'double+add'; point: Pt }

/** Scalar multiplication kG by double-and-add, recording each step. */
export function mul(k: number, P: Pt, c: Curve): { point: Pt; steps: MulStep[] } {
  const bits = k.toString(2).split('').map(Number); // MSB first
  let R: Pt = null;
  const steps: MulStep[] = [];
  for (const bit of bits) {
    R = dbl(R, c);
    if (bit) R = add(R, P, c);
    steps.push({ bit, op: bit ? 'double+add' : 'double', point: R });
  }
  return { point: R, steps };
}

/** Every affine point on the curve (the whole finite group, minus O). */
export function allPoints(c: Curve): Point[] {
  const pts: Point[] = [];
  for (let x = 0; x < c.p; x++)
    for (let y = 0; y < c.p; y++)
      if (mod(y * y, c.p) === mod(x * x * x + c.a * x + c.b, c.p)) pts.push({ x, y });
  return pts;
}

/** Order of the generator: the smallest k>0 with kG = O. */
export function order(c: Curve): number {
  let R: Pt = c.G;
  let k = 1;
  while (R !== null) { R = add(R, c.G, c); k++; }
  return k;
}

/** The cyclic subgroup generated by G, indexed so subgroup[k] = kG (subgroup[0] = O). */
export function subgroup(c: Curve): Pt[] {
  const out: Pt[] = [null];
  let R: Pt = c.G;
  while (R !== null) { out.push(R); R = add(R, c.G, c); }
  return out; // out[order] = O again is omitted; length = order
}
