// Feldman Verifiable Secret Sharing (VSS) — Shamir secret sharing, but where nobody has to TRUST the
// dealer. In plain Shamir, the dealer hands each participant a point on a secret polynomial; a malicious
// dealer could hand out inconsistent points that don't lie on any single polynomial, and you'd only find
// out when reconstruction silently failed. Feldman fixes this by having the dealer also PUBLISH commitments
// to each polynomial coefficient — C_j = g^{a_j} — without revealing the coefficients. Each participant can
// then check their share s_i against the commitments: g^{s_i} must equal ∏_j C_j^{i^j}. If it does, the
// share provably lies on the committed polynomial; if not, the dealer is caught. The secret stays hidden
// (the commitments are one-way), yet every share is publicly verifiable. This is the backbone of
// distributed key generation and threshold cryptography. Reference: Feldman, "A Practical Scheme for
// Non-interactive Verifiable Secret Sharing" (FOCS 1987).

import { modpow, modinv } from './blindsig';

// Toy group: p=23 prime, the order-q=11 subgroup generated by g=2 (2^11 ≡ 1 mod 23). Coefficients and
// shares live in Z_q; group elements (commitments) live mod p.
export const P = 23, Q = 11, G = 2;

const mod = (n: number, m: number) => ((n % m) + m) % m;

/** Dealer publishes a commitment to each coefficient: C_j = g^{a_j} mod p. The coefficients stay secret. */
export const commitments = (coeffs: number[]): number[] => coeffs.map((a) => modpow(G, mod(a, Q), P));

/** The share for participant i is f(i) mod q, where f is the polynomial with the given coefficients. */
export function share(coeffs: number[], i: number): number {
  let acc = 0, pow = 1;
  for (const a of coeffs) { acc = mod(acc + a * pow, Q); pow = mod(pow * i, Q); }
  return acc;
}

/** Verify a share against the public commitments: g^{s_i} ?= ∏_j C_j^{i^j} mod p. True ⇒ the share provably
 *  lies on the committed polynomial (the dealer didn't cheat). */
export function verifyShare(i: number, s_i: number, commits: number[]): boolean {
  let rhs = 1;
  for (let j = 0; j < commits.length; j++) rhs = mod(rhs * modpow(commits[j], i ** j, P), P);
  return modpow(G, mod(s_i, Q), P) === rhs;
}

/** Lagrange-interpolate the secret f(0) from any `threshold` shares, over Z_q. */
export function reconstruct(points: { x: number; y: number }[]): number {
  let secret = 0;
  for (let i = 0; i < points.length; i++) {
    let num = 1, den = 1;
    for (let j = 0; j < points.length; j++) if (j !== i) {
      num = mod(num * mod(-points[j].x, Q), Q);
      den = mod(den * mod(points[i].x - points[j].x, Q), Q);
    }
    secret = mod(secret + mod(points[i].y * num, Q) * modinv(den, Q), Q);
  }
  return secret;
}
