// Guided journeys — curated, ordered walks through existing sections that tell ONE story end to end.
// At 170+ sections the flat catalog answers "what is there?" but not "where do I start?"; a journey
// answers the second. A path is pure data: an ordered list of section ids, each with a one-line note
// on what to watch for. The engine derives the learner's position from the active section (no extra
// state), so the same section can live in several journeys. Every step id must be a real section —
// enforced by tests/paths.test.ts, the same taxonomy-guard discipline as the nav groups.

export interface PathStep { id: string; note: string }
export interface LearningPath { id: string; title: string; icon: string; blurb: string; steps: PathStep[] }

export const PATHS: LearningPath[] = [
  {
    id: 'https',
    title: 'How an HTTPS page loads',
    icon: '🌐',
    blurb: 'Follow one browser request from a typed name to an encrypted, multiplexed response — the flagship end-to-end story.',
    steps: [
      { id: 'dns', note: 'Turn the name into an IP — the recursive resolver walks root → TLD → authoritative.' },
      { id: 'arp', note: 'Off-subnet traffic still needs the gateway’s MAC — ARP shouts to find it on the LAN.' },
      { id: 'tcphand', note: 'A TCP 3-way handshake (SYN / SYN-ACK / ACK) opens the connection before any data.' },
      { id: 'certs', note: 'The server proves who it is with a certificate chain back to a trusted root.' },
      { id: 'dhkex', note: 'Both sides derive a shared secret over the public channel — the key is never sent.' },
      { id: 'aead', note: 'From here every record is encrypted AND authenticated; an eavesdropper sees only ciphertext.' },
      { id: 'http2', note: 'The actual GET — multiplexed as HTTP/2 streams over the one encrypted connection.' },
      { id: 'cdn', note: 'The response is often served from a nearby CDN edge, not the distant origin.' },
    ],
  },
  {
    id: 'packet',
    title: 'A packet’s journey across the internet',
    icon: '📦',
    blurb: 'One datagram, hop by hop: from "is this even local?" through NAT, TTL, and BGP to longest-prefix match at every router.',
    steps: [
      { id: 'subnet', note: 'First question: is the destination on my subnet, or does it go to the gateway?' },
      { id: 'arp', note: 'Off-subnet → resolve the gateway’s MAC with ARP to build the L2 frame.' },
      { id: 'switch', note: 'The LAN switch forwards by MAC address, learning which port each host is on.' },
      { id: 'nat', note: 'At the edge, NAT rewrites your private source IP to a public one.' },
      { id: 'ttlhop', note: 'Every router decrements TTL and recomputes the IPv4 header checksum.' },
      { id: 'traceroute', note: 'Traceroute weaponizes TTL expiry to reveal each hop along the path.' },
      { id: 'bgp', note: 'Between networks, BGP chooses the AS-path the packet will follow.' },
      { id: 'routing', note: 'At each hop, longest-prefix match picks the outgoing interface.' },
    ],
  },
  {
    id: 'crypto',
    title: 'Cryptography from scratch',
    icon: '🔒',
    blurb: 'Build trust from nothing: perfect secrecy → why classical fails → AES → modes → AEAD → key exchange → public keys → signatures.',
    steps: [
      { id: 'otpad', note: 'Start with provable perfect secrecy — the one-time pad — and its unforgiving key rule.' },
      { id: 'classical', note: 'Classical ciphers fall to frequency analysis; secrecy can’t live in a secret algorithm.' },
      { id: 'aesround', note: 'AES: watch SubBytes / ShiftRows / MixColumns / AddRoundKey diffuse one byte across the block.' },
      { id: 'ecbpenguin', note: 'A block cipher needs a mode — ECB leaks structure, and the penguin is still visible.' },
      { id: 'aead', note: 'AEAD (GCM / ChaCha-Poly) gives confidentiality AND integrity in a single pass.' },
      { id: 'dhkex', note: 'Diffie–Hellman lets two strangers agree on a key over a fully public wire.' },
      { id: 'rsa', note: 'Public-key crypto: encrypt with the public key, decrypt with the private one.' },
      { id: 'crt', note: 'The Chinese Remainder Theorem behind fast RSA: work mod p and mod q separately, then recombine — ~4× quicker.' },
      { id: 'ecdsa', note: 'Sign with elliptic curves — and watch how one reused nonce leaks the private key.' },
      { id: 'montladder', note: 'Do the secret exponentiation without leaking it: the Montgomery ladder runs the same operations every bit, constant-time.' },
    ],
  },
  {
    id: 'tcp',
    title: 'How TCP delivers a reliable stream',
    icon: '🚀',
    blurb: 'A lossy, reordering network underneath — yet an ordered, reliable byte stream on top. See every mechanism that makes that true.',
    steps: [
      { id: 'tcphand', note: 'SYN / SYN-ACK / ACK — both sides agree on their starting sequence numbers.' },
      { id: 'flow', note: 'The receive window stops a fast sender from overrunning a slow receiver.' },
      { id: 'arq', note: 'Lost a segment? ARQ retransmits — go-back-N versus selective repeat.' },
      { id: 'rto', note: 'The retransmission timer adapts to RTT; Karn’s rule avoids ambiguous samples.' },
      { id: 'congestion', note: 'Congestion control probes the network: slow-start, then additive-increase / multiplicative-decrease.' },
      { id: 'cubic', note: 'CUBIC grows the window along a cubic curve to fill fat, fast links quickly.' },
      { id: 'bbr', note: 'BBR models bottleneck bandwidth and RTT instead of treating loss as the only signal.' },
      { id: 'sack', note: 'Selective ACK tells the sender exactly which segments already arrived.' },
    ],
  },
  {
    id: 'database',
    title: 'Build a database',
    icon: '🗄️',
    blurb: 'From a single index on disk to a durable, isolated, replicated, distributed store — the layers a real database is made of.',
    steps: [
      { id: 'btree', note: 'The B+tree index: how a database finds a row in a handful of disk seeks.' },
      { id: 'wal', note: 'Write-ahead logging makes a crash recoverable — log the change first, then apply it.' },
      { id: 'mvcc', note: 'MVCC gives each transaction a consistent snapshot without blocking readers.' },
      { id: 'locking', note: 'Where snapshots aren’t enough, locks serialize access — and can deadlock.' },
      { id: 'serializable', note: 'The correctness those locks enforce: a schedule is safe exactly when its precedence graph is acyclic.' },
      { id: 'lsm', note: 'LSM-trees flip the design for write-heavy loads: append to memory, then compact.' },
      { id: 'replication', note: 'Ship the WAL to replicas so a copy of the data survives a node loss.' },
      { id: 'quorum', note: 'Read/write quorums (R + W > N) keep replicas consistent under failure.' },
      { id: 'twopc', note: 'Two-phase commit makes one transaction atomic across several machines.' },
    ],
  },
  {
    id: 'distributed',
    title: 'Distributed systems foundations',
    icon: '🕸️',
    blurb: 'No global clock, no shared memory, nodes that fail — yet the cluster must agree. Walk from ordering time to reaching consensus.',
    steps: [
      { id: 'lamport', note: 'With no global clock, Lamport timestamps give a consistent "happened-before" order.' },
      { id: 'vclock', note: 'Vector clocks go further — they detect when two events are genuinely concurrent.' },
      { id: 'quorum', note: 'Quorums (R + W > N) let a replicated store stay consistent without a single leader.' },
      { id: 'raft', note: 'Raft elects one leader so a replicated log becomes easy to reason about.' },
      { id: 'raftlog', note: 'The leader replicates its log; an entry commits once a majority have stored it.' },
      { id: 'paxos', note: 'Paxos is the classic consensus core that Raft repackages to be teachable.' },
      { id: 'crdt', note: 'CRDTs let replicas edit independently and always merge without conflict.' },
      { id: 'cap', note: 'Under a network partition you must choose: stay consistent, or stay available.' },
    ],
  },
  {
    id: 'websec',
    title: 'How the browser defends you',
    icon: '🛡️',
    blurb: 'The web is hostile by default. See the layered defenses — origins, cookies, CSP, isolation, passkeys — and the attacks they stop.',
    steps: [
      { id: 'cors', note: 'The same-origin policy walls sites off; CORS opens precise, opt-in holes.' },
      { id: 'cookies', note: 'Cookies carry the session — and SameSite / HttpOnly decide who can use them.' },
      { id: 'csp', note: 'Content-Security-Policy whitelists what may run, blunting injected scripts.' },
      { id: 'webinject', note: 'Watch SQLi and XSS land — then the escaping and parameterization that stop them.' },
      { id: 'siteisolation', note: 'Site isolation puts each origin in its own process against Spectre-class leaks.' },
      { id: 'webauthn', note: 'Passkeys replace passwords with an origin-bound key a phisher can’t relay.' },
    ],
  },
  {
    id: 'cpu',
    title: 'Inside the CPU',
    icon: '🖥️',
    blurb: 'How a chip actually runs your code: instructions flowing through a pipeline, guessing branches, juggling caches and memory, up to the OS scheduler.',
    steps: [
      { id: 'pipeline', note: 'Instructions overlap in a 5-stage pipeline — and stall when one depends on another.' },
      { id: 'branchpredict', note: 'A branch’s direction is guessed before it’s known; a 2-bit counter keeps the pipeline full.' },
      { id: 'strideprefetch', note: 'The other predictor: spot a constant address stride and fetch the next line before the load asks for it.' },
      { id: 'mesi', note: 'Each core caches memory privately; MESI keeps those copies coherent over a snooping bus.' },
      { id: 'tso', note: 'Store buffers let a core reorder its own writes — why two threads can both read stale values.' },
      { id: 'pagewalk', note: 'Every memory access translates a virtual address through a 4-level page table.' },
      { id: 'nestedpaging', note: 'Inside a VM the walk goes two-dimensional — guest and host tables — costing 24 accesses.' },
      { id: 'cpusched', note: 'The OS time-slices many processes onto the cores — FCFS, SJF, round-robin.' },
      { id: 'cfs', note: 'Linux’s CFS shares the CPU fairly by virtual runtime, weighted by nice value.' },
      { id: 'eevdf', note: 'Its successor, EEVDF, adds eligibility and virtual deadlines for a latency bound — the scheduler since 6.6.' },
    ],
  },
  {
    id: 'production',
    title: 'Operating a service in production',
    icon: '🛠️',
    blurb: 'The lifecycle of running software reliably: ship it safely, keep it healthy, survive overload, and observe and harden it.',
    steps: [
      { id: 'deployments', note: 'Roll out v2 without downtime — rolling, blue-green, or canary.' },
      { id: 'healthcheck', note: 'Readiness gates traffic; liveness restarts — confusing them causes restart storms.' },
      { id: 'autoscale', note: 'Track load by adding and removing replicas with the HPA formula.' },
      { id: 'slo', note: 'Turn “be reliable” into an error budget you can spend on features.' },
      { id: 'loadshed', note: 'Under overload, shed fast — queuing everything collapses goodput.' },
      { id: 'idempotency', note: 'Make retries safe so a lost response can’t double-charge.' },
      { id: 'tracing', note: 'Follow one request across services to see where the latency really goes.' },
      { id: 'chaos', note: 'Inject failures on purpose to prove the blast radius is contained.' },
    ],
  },
  {
    id: 'mlclassify',
    title: 'How machines learn to classify',
    icon: '🧠',
    blurb: 'From one neuron to tree ensembles — how supervised classifiers draw the boundary between classes, each method fixing the last one’s limitation.',
    steps: [
      { id: 'perceptron', note: 'The first neuron: one line, learning from its mistakes — but it can’t separate XOR.' },
      { id: 'logisticregression', note: 'Keep the line, but output a probability, trained on a convex loss that always converges.' },
      { id: 'svm', note: 'Among all separating lines, pick the widest-margin one — pinned by just a few support vectors.' },
      { id: 'decisiontree', note: 'Swap lines for yes/no questions: axis-aligned regions that even solve the XOR a perceptron can’t.' },
      { id: 'randomforest', note: 'One deep tree overfits; average many decorrelated trees to slash the variance.' },
      { id: 'gradientboosting', note: 'Or add shallow trees in sequence, each fitting the errors the last one left behind.' },
    ],
  },
  {
    id: 'mlstructure',
    title: 'Finding structure without labels',
    icon: '🔍',
    blurb: 'Unsupervised learning: compress the dimensions, then find clusters by centers, by density, and by probability — no labels required.',
    steps: [
      { id: 'pca', note: 'Compress high-dimensional data onto the few axes it actually varies along.' },
      { id: 'kmeans', note: 'Partition the points into k round clusters, each owned by its nearest center.' },
      { id: 'dbscan', note: 'Cluster by density instead — clusters of any shape, with outliers left labeled as noise.' },
      { id: 'gmm', note: 'Soft, elliptical clusters via Expectation-Maximization; k-means is the hard-assignment special case.' },
    ],
  },
  {
    id: 'exploits',
    title: 'Breaking a program: exploits & defenses',
    icon: '💥',
    blurb: 'The attacker–defender arms race, from a stack buffer overflow up through ASLR and CFI to the CPU speculation attacks that leak beneath them all. Sandboxed and conceptual.',
    steps: [
      { id: 'bufferoverflow', note: 'Overflow a stack buffer to overwrite the saved return address and hijack control flow.' },
      { id: 'nxbit', note: 'First defense: mark the stack non-executable so injected shellcode can’t run as code.' },
      { id: 'rop', note: 'Defeat NX by chaining gadgets — snippets of existing code that each end in a return.' },
      { id: 'aslr', note: 'Randomize the address layout so the attacker can’t find those gadgets in the first place.' },
      { id: 'stackcanary', note: 'A random guard between the locals and the return address; the linear overflow smashes it and aborts.' },
      { id: 'cfi', note: 'Verify every indirect call and return lands on a legitimate target, not an attacker’s.' },
      { id: 'spectre', note: 'Even with perfect software defenses, speculation leaks secrets through cache timing.' },
      { id: 'meltdown', note: 'Out-of-order execution reads across the user/kernel boundary — fixed only by unmapping the kernel.' },
    ],
  },
  {
    id: 'sketches',
    title: 'Approximate answers in tiny memory',
    icon: '📊',
    blurb: 'Trade exactness for space: four probabilistic sketches that answer membership, frequency, cardinality, and similarity in a fraction of the memory, with tunable error.',
    steps: [
      { id: 'bloom', note: 'Membership in a few bits per element — no false negatives, tunable false positives, and it never stores the items themselves.' },
      { id: 'countmin', note: 'The frequency of each item in a high-volume stream, in sublinear space — counts that can overestimate but never miss.' },
      { id: 'hll', note: 'Count distinct items (cardinality) in kilobytes even for billions, from the longest run of leading zeros in their hashes.' },
      { id: 'minhash', note: 'Estimate how similar two sets are (their Jaccard overlap) from a handful of min-hashes — the engine of near-duplicate detection.' },
    ],
  },
  {
    id: 'randomized',
    title: 'Randomness as an algorithm',
    icon: '🎲',
    blurb: 'Randomness isn’t just noise — it’s a tool. Estimate, sample from a stream, draw by weight, shuffle fairly, and fit through outliers, each solved cleanly by the controlled use of chance.',
    steps: [
      { id: 'montecarlo', note: 'Estimate a quantity by random sampling — throw darts to get π, with error shrinking as 1/√N in any number of dimensions.' },
      { id: 'reservoir', note: 'Sample k items uniformly from a stream of unknown length, in a single pass and O(k) memory.' },
      { id: 'aliasmethod', note: 'Draw from a weighted distribution in O(1) — one die roll plus one coin flip, after a clever setup.' },
      { id: 'shuffle', note: 'Shuffle an array so every permutation is equally likely (Fisher–Yates) — and the subtle bias of doing it the wrong way.' },
      { id: 'ransac', note: 'Fit a model despite 50% outliers by random sampling plus consensus — where averaging with least-squares gets dragged off.' },
      { id: 'wfc', note: 'Generate structure with chance: wave function collapse makes a random choice at the most-constrained cell and propagates, building a rule-abiding map.' },
    ],
  },
  {
    id: 'language',
    title: 'How your code actually runs',
    icon: '⚙️',
    blurb: 'Follow a line of source from characters to running native code: lex it, parse it, compile it, run it on a VM, JIT the hot paths, and let the collector reclaim memory.',
    steps: [
      { id: 'dfa', note: 'Lexing: a finite-state machine scans characters into tokens — numbers, names, operators — in one linear pass.' },
      { id: 'shuntingyard', note: 'Parsing: shunting-yard turns infix tokens into unambiguous postfix, resolving precedence with a stack.' },
      { id: 'compiler', note: 'Codegen: walk the parsed expression and emit the actual machine instructions a CPU runs.' },
      { id: 'hindley', note: 'Type-checking: Hindley-Milner infers every type from usage alone, catching mismatches before a line runs.' },
      { id: 'regalloc', note: 'A backend pass fits the code’s unlimited temporaries into the CPU’s few registers by coloring an interference graph.' },
      { id: 'bytecode', note: 'Or target a portable bytecode and run it on a stack VM — how the JVM and CPython execute.' },
      { id: 'jit', note: 'Hot bytecode is compiled to native code at runtime — profile, specialize, and patch the call site.' },
      { id: 'gc', note: 'The runtime reclaims unreachable memory automatically, so the program never has to free by hand.' },
    ],
  },
  {
    id: 'graphics',
    title: 'How a screen gets drawn',
    icon: '🎨',
    blurb: 'From the humblest pixel line to photorealistic rays: the primitives and paradigms that turn geometry and math into the image on your display.',
    steps: [
      { id: 'bresenham', note: 'The humblest primitive: draw a straight line on a pixel grid with nothing but integer adds.' },
      { id: 'bezier', note: 'Smooth curves from a few control points — every font glyph and SVG path is Béziers.' },
      { id: 'perspective', note: 'Project the 3D scene onto the 2D screen by dividing by depth — and interpolate perspective-correctly, or the texture warps.' },
      { id: 'rasterize', note: 'Fill a triangle by testing pixels against its edges — the primitive every GPU is built around.' },
      { id: 'raytracing', note: 'The other paradigm: trace a ray from the eye through each pixel to find what it hits.' },
      { id: 'raymarch', note: 'March along each ray in steps sized by a signed-distance field — the shader and demoscene way.' },
      { id: 'perlin', note: 'Procedural noise builds textures, terrain, and clouds — infinite detail with no stored image.' },
    ],
  },
  {
    id: 'compression',
    title: 'Compression: keep what matters',
    icon: '🗜️',
    blurb: 'How data shrinks — from lossless codes that give back every bit, through repeat-finding and byte-reordering, to lossy schemes that throw away exactly what you won’t miss.',
    steps: [
      { id: 'huffman', note: 'Lossless entropy coding: give frequent symbols shorter codes with an optimal prefix tree.' },
      { id: 'lz77', note: 'Replace repeated substrings with back-references to earlier text — the core of gzip and zip.' },
      { id: 'bwt', note: 'The Burrows-Wheeler transform reversibly clusters similar bytes so the coder compresses harder (bzip2).' },
      { id: 'jpeg', note: 'Go lossy for images: the DCT concentrates energy into low frequencies you can quantize away.' },
      { id: 'svd', note: 'Low-rank approximation keeps only an image’s top singular values — the provably optimal rank-k.' },
    ],
  },
  {
    id: 'strings',
    title: 'Searching and assembling text',
    icon: '🔤',
    blurb: 'Work with sequences at scale: find one pattern without backtracking, match thousands at once, index every suffix, search inside compressed data, and reassemble a whole sequence from fragments.',
    steps: [
      { id: 'kmp', note: 'Find a pattern in text without ever backtracking, using a precomputed failure function.' },
      { id: 'rabinkarp', note: 'A rolling hash slides a fingerprint along the text to spot candidate matches in O(1) per step.' },
      { id: 'ahocorasick', note: 'Match thousands of patterns at once with a trie threaded by failure links.' },
      { id: 'suffixarray', note: 'Sort all suffixes once, then answer any substring query by binary search.' },
      { id: 'bwt', note: 'The Burrows-Wheeler transform powers the FM-index — full-text search inside compressed data.' },
      { id: 'debruijn', note: 'Assemble a whole sequence from short overlapping k-mers by walking an Eulerian path.' },
    ],
  },
  {
    id: 'dp',
    title: 'Dynamic programming everywhere',
    icon: '🧩',
    blurb: 'One idea — build the answer from overlapping subproblems and never recompute one twice — solves a startling range of problems. Watch the same table-filling logic reappear across sequences, images, and probabilities.',
    steps: [
      { id: 'lis', note: 'The core move: the best answer ending here is built from the best answers before it (longest increasing subsequence).' },
      { id: 'knapsack', note: 'DP over choices: a table of best value per weight budget, each cell reusing smaller ones.' },
      { id: 'editdist', note: 'DP over two sequences: the cheapest edits to turn one string into another, one cell per prefix pair.' },
      { id: 'diff', note: 'The same longest-common-subsequence DP is exactly how git diff lines up two files.' },
      { id: 'seamcarve', note: 'DP over a pixel grid: the least-energy connected seam, for content-aware image resizing.' },
      { id: 'viterbi', note: 'DP over a probability trellis: the single most likely hidden sequence — speech, decoding, tagging.' },
    ],
  },
  {
    id: 'iterative',
    title: 'How computers converge on an answer',
    icon: '🔁',
    blurb: 'Most real math has no closed form, so computers iterate: start with a guess and improve it until it stops changing. Five very different problems, all solved by convergence.',
    steps: [
      { id: 'newton', note: 'Root-finding by tangent steps — the correct digits roughly double each iteration (quadratic convergence).' },
      { id: 'conjgrad', note: 'Solve a linear system Ax=b by conjugate directions — exact in n steps, far fewer when preconditioned.' },
      { id: 'pagerank', note: 'Find a matrix’s dominant eigenvector by multiplying repeatedly — the random surfer’s stationary distribution.' },
      { id: 'kmeans', note: 'Alternate assign-to-nearest and move-the-center until the clustering stops changing.' },
      { id: 'montecarlo', note: 'When you can’t integrate, sample at random — the estimate’s error shrinks as 1/√N.' },
    ],
  },
  {
    id: 'memory',
    title: 'Allocating and reclaiming memory',
    icon: '🧹',
    blurb: 'A program asks for memory and later stops using it — but how is it handed out, and how does the system know when it’s free again? Allocation, then three ways to reclaim, each fixing the last one’s blind spot.',
    steps: [
      { id: 'buddyalloc', note: 'Allocation: the kernel hands out memory in power-of-two blocks, splitting and merging buddies to fight fragmentation.' },
      { id: 'arena', note: 'The opposite extreme: one block, one bump pointer, no per-object free — reset the whole arena at once when the request or frame ends.' },
      { id: 'refcount', note: 'The simplest reclaim: count references and free at zero — but a reference cycle keeps itself alive and leaks.' },
      { id: 'gc', note: 'Tracing mark-and-sweep collects from the roots instead, so it reclaims the cycles reference counting can’t.' },
      { id: 'cheney', note: 'A copying collector goes further — it relocates the survivors into a fresh space, compacting fragmentation away.' },
    ],
  },
  {
    id: 'query',
    title: 'How a database answers a query',
    icon: '📇',
    blurb: 'The read path: find the rows with an index, combine tables with a join, handle inputs far bigger than memory, and let the planner pick the cheapest way to do it all.',
    steps: [
      { id: 'btree', note: 'The B+tree index finds a row by sorted key in a handful of disk seeks — the default database index.' },
      { id: 'exthash', note: 'A hash index finds rows by exact key and grows without rehashing, splitting one bucket at a time.' },
      { id: 'joins', note: 'Combine two tables on a key — nested-loop, hash, or sort-merge, all returning the same rows at different costs.' },
      { id: 'gracejoin', note: 'When both tables dwarf memory, partition by hash and join the aligned partition-pairs one at a time.' },
      { id: 'queryplan', note: 'The optimizer estimates the cost of each index and join order, then picks the cheapest plan to execute.' },
    ],
  },
  {
    id: 'moderncrypto',
    title: 'Cryptography beyond secrecy',
    icon: '🔏',
    blurb: 'Crypto is more than hiding messages. Commit to a value, prove membership, transfer a choice obliviously, generate verifiable randomness — then go post-quantum and meet the lattice attack that sets the bar.',
    steps: [
      { id: 'pedersen', note: 'A commitment locks in a value you can’t change but haven’t revealed — Pedersen commitments are perfectly hiding, computationally binding.' },
      { id: 'merkle', note: 'A Merkle tree commits to a whole set with one hash and proves any member belongs with a short path.' },
      { id: 'accumulator', note: 'An RSA accumulator commits to a set with one number and proves membership with one number — constant size, no growing path.' },
      { id: 'ot', note: 'Oblivious transfer: the sender offers two messages, the receiver takes one, and neither learns the other’s choice — the seed of secure computation.' },
      { id: 'garbled', note: 'Yao garbled circuits build on OT: two parties compute f(a,b) revealing neither input, by evaluating an encrypted, shuffled gate.' },
      { id: 'vrf', note: 'A verifiable random function emits randomness plus a proof it was computed correctly — unpredictable yet checkable.' },
      { id: 'sumcheck', note: 'The sumcheck protocol proves a huge sum over 2ⁿ inputs in n cheap rounds and one evaluation — the engine inside modern SNARKs.' },
      { id: 'vdf', note: 'A verifiable delay function forces a fixed sequential compute (repeated squaring) that a tiny proof checks fast — unbiasable randomness beacons.' },
      { id: 'pqc', note: 'Post-quantum encryption hides a bit in noise (Learning With Errors), staying secure even against a quantum computer.' },
      { id: 'lll', note: 'And the attack that sets the bar: LLL reduces a lattice basis to find short vectors — why lattice crypto needs hundreds of dimensions.' },
    ],
  },
  {
    id: 'privacy',
    title: 'Privacy beyond encryption',
    icon: '🕶️',
    blurb: 'Encryption hides the contents of your data — but not the statistics you publish, the computation you run, the queries you make, or the blocks you touch. Four techniques that hide those too.',
    steps: [
      { id: 'diffpriv', note: 'Publish statistics about a group while provably hiding every individual — add calibrated Laplace noise (differential privacy).' },
      { id: 'garbled', note: 'Compute a function of two parties’ secret inputs, revealing neither — Yao garbled circuits.' },
      { id: 'pir', note: 'Fetch a record from a database without the server learning which record you asked for.' },
      { id: 'oram', note: 'Hide even your access pattern to your own outsourced storage — every access looks like a random path.' },
    ],
  },
  {
    id: 'arithmetic',
    title: 'From transistors to matrix multiply',
    icon: '🔢',
    blurb: 'Build arithmetic from the bottom up: a transistor is a switch, switches make an adder, an adder plus logic makes an ALU, a tree of adders multiplies fast, and a grid of multiply-accumulate cells becomes the matrix engine inside a TPU.',
    steps: [
      { id: 'transistor', note: 'The switch: a voltage on the gate opens or closes a channel — the physical 1s and 0s under everything else.' },
      { id: 'adder', note: 'Wire gates into a binary adder; the carry ripples (or looks ahead) to sum two numbers bit by bit.' },
      { id: 'alu', note: 'The compute core: an adder plus logic gates and a mux the opcode uses to pick add/sub/and/or/shift, raising the flags.' },
      { id: 'wallace', note: 'Multiplication done fast: a Wallace tree reduces the partial-product dot diagram with carry-save adders in O(log n) depth.' },
      { id: 'systolic', note: 'Now tile multiply-accumulate cells into a grid: data flows through and a whole matrix multiply falls out — the heart of a TPU.' },
    ],
  },
  {
    id: 'sortselect',
    title: 'How computers sort and select',
    icon: '📊',
    blurb: 'From the five textbook sorts to the one in your standard library, then the flip side: finding the k-th element without sorting at all. Partitioning is the thread that ties them together.',
    steps: [
      { id: 'sorting', note: 'The five textbook sorts — bubble, insertion, selection, merge, quicksort — and the O(n²) vs O(n log n) gap between them.' },
      { id: 'timsort', note: 'The real-world hybrid (Python, Java, Rust default): exploit natural runs, merge in balanced order, gallop — adaptive and stable.' },
      { id: 'dnf', note: 'Dutch national flag: partition into <, =, > a pivot in one linear pass — the three-way split quicksort and selection lean on.' },
      { id: 'quickselect', note: 'Don’t sort to find the k-th element — partition and recurse into only the side that holds it, O(n) on average.' },
      { id: 'medianofmedians', note: 'Choose the pivot as a median of medians and quickselect becomes O(n) even in the worst case — a provably good split.' },
      { id: 'heap', note: 'A binary heap keeps the min or max at the root in O(log n) — heapsort, and the priority queue behind schedulers and Dijkstra.' },
    ],
  },
];

export const pathById: Record<string, LearningPath> = Object.fromEntries(PATHS.map((p) => [p.id, p]));

/** The index of `sectionId` within a path's steps, or -1 if the learner has stepped off the path. */
export function stepIndexOf(path: LearningPath, sectionId: string): number {
  return path.steps.findIndex((s) => s.id === sectionId);
}
