// Guided journeys — curated, ordered walks through existing sections that tell ONE story end to end.
// At 170+ sections the flat catalog answers "what is there?" but not "where do I start?"; a journey
// answers the second. A path is pure data: an ordered list of section ids, each with a one-line note
// on what to watch for. The engine derives the learner's position from the active section (no extra
// state), so the same section can live in several journeys. Every step id must be a real section —
// enforced by tests/paths.test.ts, the same taxonomy-guard discipline as the nav groups.

export interface PathStep { id: string; note: string }
export interface LearningPath { id: string; title: string; icon: string; blurb: string; steps: PathStep[] }

export const PATHS: LearningPath[] = [
  {
    id: 'https',
    title: 'How an HTTPS page loads',
    icon: '🌐',
    blurb: 'Follow one browser request from a typed name to an encrypted, multiplexed response — the flagship end-to-end story.',
    steps: [
      { id: 'dns', note: 'Turn the name into an IP — the recursive resolver walks root → TLD → authoritative.' },
      { id: 'arp', note: 'Off-subnet traffic still needs the gateway’s MAC — ARP shouts to find it on the LAN.' },
      { id: 'tcphand', note: 'A TCP 3-way handshake (SYN / SYN-ACK / ACK) opens the connection before any data.' },
      { id: 'certs', note: 'The server proves who it is with a certificate chain back to a trusted root.' },
      { id: 'dhkex', note: 'Both sides derive a shared secret over the public channel — the key is never sent.' },
      { id: 'aead', note: 'From here every record is encrypted AND authenticated; an eavesdropper sees only ciphertext.' },
      { id: 'http2', note: 'The actual GET — multiplexed as HTTP/2 streams over the one encrypted connection.' },
      { id: 'cdn', note: 'The response is often served from a nearby CDN edge, not the distant origin.' },
    ],
  },
  {
    id: 'packet',
    title: 'A packet’s journey across the internet',
    icon: '📦',
    blurb: 'One datagram, hop by hop: from "is this even local?" through NAT, TTL, and BGP to longest-prefix match at every router.',
    steps: [
      { id: 'subnet', note: 'First question: is the destination on my subnet, or does it go to the gateway?' },
      { id: 'arp', note: 'Off-subnet → resolve the gateway’s MAC with ARP to build the L2 frame.' },
      { id: 'switch', note: 'The LAN switch forwards by MAC address, learning which port each host is on.' },
      { id: 'nat', note: 'At the edge, NAT rewrites your private source IP to a public one.' },
      { id: 'ttlhop', note: 'Every router decrements TTL and recomputes the IPv4 header checksum.' },
      { id: 'traceroute', note: 'Traceroute weaponizes TTL expiry to reveal each hop along the path.' },
      { id: 'bgp', note: 'Between networks, BGP chooses the AS-path the packet will follow.' },
      { id: 'routing', note: 'At each hop, longest-prefix match picks the outgoing interface.' },
    ],
  },
  {
    id: 'crypto',
    title: 'Cryptography from scratch',
    icon: '🔒',
    blurb: 'Build trust from nothing: perfect secrecy → why classical fails → AES → modes → AEAD → key exchange → public keys → signatures.',
    steps: [
      { id: 'otpad', note: 'Start with provable perfect secrecy — the one-time pad — and its unforgiving key rule.' },
      { id: 'classical', note: 'Classical ciphers fall to frequency analysis; secrecy can’t live in a secret algorithm.' },
      { id: 'aesround', note: 'AES: watch SubBytes / ShiftRows / MixColumns / AddRoundKey diffuse one byte across the block.' },
      { id: 'ecbpenguin', note: 'A block cipher needs a mode — ECB leaks structure, and the penguin is still visible.' },
      { id: 'aead', note: 'AEAD (GCM / ChaCha-Poly) gives confidentiality AND integrity in a single pass.' },
      { id: 'dhkex', note: 'Diffie–Hellman lets two strangers agree on a key over a fully public wire.' },
      { id: 'rsa', note: 'Public-key crypto: encrypt with the public key, decrypt with the private one.' },
      { id: 'millerrabin', note: 'But first you need the primes: Miller–Rabin decides primality in a few exponentiations, so you can pick 2048-bit primes for the key.' },
      { id: 'crt', note: 'The Chinese Remainder Theorem behind fast RSA: work mod p and mod q separately, then recombine — ~4× quicker.' },
      { id: 'ecdsa', note: 'Sign with elliptic curves — and watch how one reused nonce leaks the private key.' },
      { id: 'montladder', note: 'Do the secret exponentiation without leaking it: the Montgomery ladder runs the same operations every bit, constant-time.' },
      { id: 'tonelli', note: 'Recover a point from a compressed key: a modular square root (Tonelli–Shanks) turns x and a sign bit back into y = √(x³+ax+b) mod p.' },
    ],
  },
  {
    id: 'tcp',
    title: 'How TCP delivers a reliable stream',
    icon: '🚀',
    blurb: 'A lossy, reordering network underneath — yet an ordered, reliable byte stream on top. See every mechanism that makes that true.',
    steps: [
      { id: 'tcphand', note: 'SYN / SYN-ACK / ACK — both sides agree on their starting sequence numbers.' },
      { id: 'flow', note: 'The receive window stops a fast sender from overrunning a slow receiver.' },
      { id: 'arq', note: 'Lost a segment? ARQ retransmits — go-back-N versus selective repeat.' },
      { id: 'rto', note: 'The retransmission timer adapts to RTT; Karn’s rule avoids ambiguous samples.' },
      { id: 'congestion', note: 'Congestion control probes the network: slow-start, then additive-increase / multiplicative-decrease.' },
      { id: 'cubic', note: 'CUBIC grows the window along a cubic curve to fill fat, fast links quickly.' },
      { id: 'bbr', note: 'BBR models bottleneck bandwidth and RTT instead of treating loss as the only signal.' },
      { id: 'sack', note: 'Selective ACK tells the sender exactly which segments already arrived.' },
    ],
  },
  {
    id: 'database',
    title: 'Build a database',
    icon: '🗄️',
    blurb: 'From a single index on disk to a durable, isolated, replicated, distributed store — the layers a real database is made of.',
    steps: [
      { id: 'btree', note: 'The B+tree index: how a database finds a row in a handful of disk seeks.' },
      { id: 'wal', note: 'Write-ahead logging makes a crash recoverable — log the change first, then apply it.' },
      { id: 'mvcc', note: 'MVCC gives each transaction a consistent snapshot without blocking readers.' },
      { id: 'locking', note: 'Where snapshots aren’t enough, locks serialize access — and can deadlock.' },
      { id: 'serializable', note: 'The correctness those locks enforce: a schedule is safe exactly when its precedence graph is acyclic.' },
      { id: 'lsm', note: 'LSM-trees flip the design for write-heavy loads: append to memory, then compact.' },
      { id: 'replication', note: 'Ship the WAL to replicas so a copy of the data survives a node loss.' },
      { id: 'quorum', note: 'Read/write quorums (R + W > N) keep replicas consistent under failure.' },
      { id: 'twopc', note: 'Two-phase commit makes one transaction atomic across several machines.' },
    ],
  },
  {
    id: 'distributed',
    title: 'Distributed systems foundations',
    icon: '🕸️',
    blurb: 'No global clock, no shared memory, nodes that fail — yet the cluster must agree. Walk from ordering time to reaching consensus.',
    steps: [
      { id: 'lamport', note: 'With no global clock, Lamport timestamps give a consistent "happened-before" order.' },
      { id: 'vclock', note: 'Vector clocks go further — they detect when two events are genuinely concurrent.' },
      { id: 'quorum', note: 'Quorums (R + W > N) let a replicated store stay consistent without a single leader.' },
      { id: 'raft', note: 'Raft elects one leader so a replicated log becomes easy to reason about.' },
      { id: 'raftlog', note: 'The leader replicates its log; an entry commits once a majority have stored it.' },
      { id: 'paxos', note: 'Paxos is the classic consensus core that Raft repackages to be teachable.' },
      { id: 'crdt', note: 'CRDTs let replicas edit independently and always merge without conflict.' },
      { id: 'cap', note: 'Under a network partition you must choose: stay consistent, or stay available.' },
    ],
  },
  {
    id: 'websec',
    title: 'How the browser defends you',
    icon: '🛡️',
    blurb: 'The web is hostile by default. See the layered defenses — origins, cookies, CSP, isolation, passkeys — and the attacks they stop.',
    steps: [
      { id: 'cors', note: 'The same-origin policy walls sites off; CORS opens precise, opt-in holes.' },
      { id: 'cookies', note: 'Cookies carry the session — and SameSite / HttpOnly decide who can use them.' },
      { id: 'csp', note: 'Content-Security-Policy whitelists what may run, blunting injected scripts.' },
      { id: 'webinject', note: 'Watch SQLi and XSS land — then the escaping and parameterization that stop them.' },
      { id: 'siteisolation', note: 'Site isolation puts each origin in its own process against Spectre-class leaks.' },
      { id: 'webauthn', note: 'Passkeys replace passwords with an origin-bound key a phisher can’t relay.' },
    ],
  },
  {
    id: 'cpu',
    title: 'Inside the CPU',
    icon: '🖥️',
    blurb: 'How a chip actually runs your code: instructions flowing through a pipeline, guessing branches, juggling caches and memory, up to the OS scheduler.',
    steps: [
      { id: 'pipeline', note: 'Instructions overlap in a 5-stage pipeline — and stall when one depends on another.' },
      { id: 'branchpredict', note: 'A branch’s direction is guessed before it’s known; a 2-bit counter keeps the pipeline full.' },
      { id: 'strideprefetch', note: 'The other predictor: spot a constant address stride and fetch the next line before the load asks for it.' },
      { id: 'branchless', note: 'When a branch is unpredictable, don’t guess — eliminate it: compute both sides and select with a bitmask or cmov, no misprediction.' },
      { id: 'mesi', note: 'Each core caches memory privately; MESI keeps those copies coherent over a snooping bus.' },
      { id: 'tso', note: 'Store buffers let a core reorder its own writes — why two threads can both read stale values.' },
      { id: 'pagewalk', note: 'Every memory access translates a virtual address through a 4-level page table.' },
      { id: 'nestedpaging', note: 'Inside a VM the walk goes two-dimensional — guest and host tables — costing 24 accesses.' },
      { id: 'cpusched', note: 'The OS time-slices many processes onto the cores — FCFS, SJF, round-robin.' },
      { id: 'cfs', note: 'Linux’s CFS shares the CPU fairly by virtual runtime, weighted by nice value.' },
      { id: 'eevdf', note: 'Its successor, EEVDF, adds eligibility and virtual deadlines for a latency bound — the scheduler since 6.6.' },
    ],
  },
  {
    id: 'production',
    title: 'Operating a service in production',
    icon: '🛠️',
    blurb: 'The lifecycle of running software reliably: ship it safely, keep it healthy, survive overload, and observe and harden it.',
    steps: [
      { id: 'deployments', note: 'Roll out v2 without downtime — rolling, blue-green, or canary.' },
      { id: 'healthcheck', note: 'Readiness gates traffic; liveness restarts — confusing them causes restart storms.' },
      { id: 'autoscale', note: 'Track load by adding and removing replicas with the HPA formula.' },
      { id: 'slo', note: 'Turn “be reliable” into an error budget you can spend on features.' },
      { id: 'loadshed', note: 'Under overload, shed fast — queuing everything collapses goodput.' },
      { id: 'idempotency', note: 'Make retries safe so a lost response can’t double-charge.' },
      { id: 'tracing', note: 'Follow one request across services to see where the latency really goes.' },
      { id: 'chaos', note: 'Inject failures on purpose to prove the blast radius is contained.' },
    ],
  },
  {
    id: 'mlclassify',
    title: 'How machines learn to classify',
    icon: '🧠',
    blurb: 'From one neuron to tree ensembles — how supervised classifiers draw the boundary between classes, each method fixing the last one’s limitation.',
    steps: [
      { id: 'perceptron', note: 'The first neuron: one line, learning from its mistakes — but it can’t separate XOR.' },
      { id: 'logisticregression', note: 'Keep the line, but output a probability, trained on a convex loss that always converges.' },
      { id: 'svm', note: 'Among all separating lines, pick the widest-margin one — pinned by just a few support vectors.' },
      { id: 'decisiontree', note: 'Swap lines for yes/no questions: axis-aligned regions that even solve the XOR a perceptron can’t.' },
      { id: 'randomforest', note: 'One deep tree overfits; average many decorrelated trees to slash the variance.' },
      { id: 'gradientboosting', note: 'Or add shallow trees in sequence, each fitting the errors the last one left behind.' },
    ],
  },
  {
    id: 'mlstructure',
    title: 'Finding structure without labels',
    icon: '🔍',
    blurb: 'Unsupervised learning: compress the dimensions, then find clusters by centers, by density, and by probability — no labels required.',
    steps: [
      { id: 'pca', note: 'Compress high-dimensional data onto the few axes it actually varies along.' },
      { id: 'kmeans', note: 'Partition the points into k round clusters, each owned by its nearest center.' },
      { id: 'dbscan', note: 'Cluster by density instead — clusters of any shape, with outliers left labeled as noise.' },
      { id: 'gmm', note: 'Soft, elliptical clusters via Expectation-Maximization; k-means is the hard-assignment special case.' },
    ],
  },
  {
    id: 'exploits',
    title: 'Breaking a program: exploits & defenses',
    icon: '💥',
    blurb: 'The attacker–defender arms race, from a stack buffer overflow up through ASLR and CFI to the CPU speculation attacks that leak beneath them all. Sandboxed and conceptual.',
    steps: [
      { id: 'bufferoverflow', note: 'Overflow a stack buffer to overwrite the saved return address and hijack control flow.' },
      { id: 'nxbit', note: 'First defense: mark the stack non-executable so injected shellcode can’t run as code.' },
      { id: 'rop', note: 'Defeat NX by chaining gadgets — snippets of existing code that each end in a return.' },
      { id: 'aslr', note: 'Randomize the address layout so the attacker can’t find those gadgets in the first place.' },
      { id: 'stackcanary', note: 'A random guard between the locals and the return address; the linear overflow smashes it and aborts.' },
      { id: 'cfi', note: 'Verify every indirect call and return lands on a legitimate target, not an attacker’s.' },
      { id: 'spectre', note: 'Even with perfect software defenses, speculation leaks secrets through cache timing.' },
      { id: 'meltdown', note: 'Out-of-order execution reads across the user/kernel boundary — fixed only by unmapping the kernel.' },
    ],
  },
  {
    id: 'sketches',
    title: 'Approximate answers in tiny memory',
    icon: '📊',
    blurb: 'Trade exactness for space: four probabilistic sketches that answer membership, frequency, cardinality, and similarity in a fraction of the memory, with tunable error.',
    steps: [
      { id: 'bloom', note: 'Membership in a few bits per element — no false negatives, tunable false positives, and it never stores the items themselves.' },
      { id: 'countmin', note: 'The frequency of each item in a high-volume stream, in sublinear space — counts that can overestimate but never miss.' },
      { id: 'hll', note: 'Count distinct items (cardinality) in kilobytes even for billions, from the longest run of leading zeros in their hashes.' },
      { id: 'minhash', note: 'Estimate how similar two sets are (their Jaccard overlap) from a handful of min-hashes — the engine of near-duplicate detection.' },
    ],
  },
  {
    id: 'randomized',
    title: 'Randomness as an algorithm',
    icon: '🎲',
    blurb: 'Randomness isn’t just noise — it’s a tool. Estimate, sample from a stream, draw by weight, shuffle fairly, and fit through outliers, each solved cleanly by the controlled use of chance.',
    steps: [
      { id: 'montecarlo', note: 'Estimate a quantity by random sampling — throw darts to get π, with error shrinking as 1/√N in any number of dimensions.' },
      { id: 'reservoir', note: 'Sample k items uniformly from a stream of unknown length, in a single pass and O(k) memory.' },
      { id: 'aliasmethod', note: 'Draw from a weighted distribution in O(1) — one die roll plus one coin flip, after a clever setup.' },
      { id: 'shuffle', note: 'Shuffle an array so every permutation is equally likely (Fisher–Yates) — and the subtle bias of doing it the wrong way.' },
      { id: 'ransac', note: 'Fit a model despite 50% outliers by random sampling plus consensus — where averaging with least-squares gets dragged off.' },
      { id: 'wfc', note: 'Generate structure with chance: wave function collapse makes a random choice at the most-constrained cell and propagates, building a rule-abiding map.' },
    ],
  },
  {
    id: 'language',
    title: 'How your code actually runs',
    icon: '⚙️',
    blurb: 'Follow a line of source from characters to running native code: lex it, parse it, compile it, run it on a VM, JIT the hot paths, and let the collector reclaim memory.',
    steps: [
      { id: 'dfa', note: 'Lexing: a finite-state machine scans characters into tokens — numbers, names, operators — in one linear pass.' },
      { id: 'shuntingyard', note: 'Parsing: shunting-yard turns infix tokens into unambiguous postfix, resolving precedence with a stack.' },
      { id: 'compiler', note: 'Codegen: walk the parsed expression and emit the actual machine instructions a CPU runs.' },
      { id: 'ssa', note: 'The optimizer’s form: rename each variable to a single-assignment version, with φ nodes at branch joins, so every use has one definition.' },
      { id: 'hindley', note: 'Type-checking: Hindley-Milner infers every type from usage alone, catching mismatches before a line runs.' },
      { id: 'regalloc', note: 'A backend pass fits the code’s unlimited temporaries into the CPU’s few registers by coloring an interference graph.' },
      { id: 'peephole', note: 'The last polish: a sliding window rewrites local patterns into cheaper ones — mul by a power of two becomes a shift, no-ops vanish.' },
      { id: 'bytecode', note: 'Or target a portable bytecode and run it on a stack VM — how the JVM and CPython execute.' },
      { id: 'jit', note: 'Hot bytecode is compiled to native code at runtime — profile, specialize, and patch the call site.' },
      { id: 'gc', note: 'The runtime reclaims unreachable memory automatically, so the program never has to free by hand.' },
    ],
  },
  {
    id: 'graphics',
    title: 'How a screen gets drawn',
    icon: '🎨',
    blurb: 'From the humblest pixel line to photorealistic rays: the primitives and paradigms that turn geometry and math into the image on your display.',
    steps: [
      { id: 'bresenham', note: 'The humblest primitive: draw a straight line on a pixel grid with nothing but integer adds.' },
      { id: 'bezier', note: 'Smooth curves from a few control points — every font glyph and SVG path is Béziers.' },
      { id: 'perspective', note: 'Project the 3D scene onto the 2D screen by dividing by depth — and interpolate perspective-correctly, or the texture warps.' },
      { id: 'rasterize', note: 'Fill a triangle by testing pixels against its edges — the primitive every GPU is built around.' },
      { id: 'raytracing', note: 'The other paradigm: trace a ray from the eye through each pixel to find what it hits.' },
      { id: 'raymarch', note: 'March along each ray in steps sized by a signed-distance field — the shader and demoscene way.' },
      { id: 'perlin', note: 'Procedural noise builds textures, terrain, and clouds — infinite detail with no stored image.' },
    ],
  },
  {
    id: 'compression',
    title: 'Compression: keep what matters',
    icon: '🗜️',
    blurb: 'How data shrinks — from lossless codes that give back every bit, through repeat-finding and byte-reordering, to lossy schemes that throw away exactly what you won’t miss.',
    steps: [
      { id: 'huffman', note: 'Lossless entropy coding: give frequent symbols shorter codes with an optimal prefix tree.' },
      { id: 'lz77', note: 'Replace repeated substrings with back-references to earlier text — the core of gzip and zip.' },
      { id: 'bwt', note: 'The Burrows-Wheeler transform reversibly clusters similar bytes so the coder compresses harder (bzip2).' },
      { id: 'jpeg', note: 'Go lossy for images: the DCT concentrates energy into low frequencies you can quantize away.' },
      { id: 'svd', note: 'Low-rank approximation keeps only an image’s top singular values — the provably optimal rank-k.' },
    ],
  },
  {
    id: 'strings',
    title: 'Searching and assembling text',
    icon: '🔤',
    blurb: 'Work with sequences at scale: find one pattern without backtracking, match thousands at once, index every suffix, search inside compressed data, and reassemble a whole sequence from fragments.',
    steps: [
      { id: 'kmp', note: 'Find a pattern in text without ever backtracking, using a precomputed failure function.' },
      { id: 'rabinkarp', note: 'A rolling hash slides a fingerprint along the text to spot candidate matches in O(1) per step.' },
      { id: 'ahocorasick', note: 'Match thousands of patterns at once with a trie threaded by failure links.' },
      { id: 'suffixarray', note: 'Sort all suffixes once, then answer any substring query by binary search.' },
      { id: 'bwt', note: 'The Burrows-Wheeler transform powers the FM-index — full-text search inside compressed data.' },
      { id: 'debruijn', note: 'Assemble a whole sequence from short overlapping k-mers by walking an Eulerian path.' },
    ],
  },
  {
    id: 'dp',
    title: 'Dynamic programming everywhere',
    icon: '🧩',
    blurb: 'One idea — build the answer from overlapping subproblems and never recompute one twice — solves a startling range of problems. Watch the same table-filling logic reappear across sequences, images, and probabilities.',
    steps: [
      { id: 'lis', note: 'The core move: the best answer ending here is built from the best answers before it (longest increasing subsequence).' },
      { id: 'knapsack', note: 'DP over choices: a table of best value per weight budget, each cell reusing smaller ones.' },
      { id: 'editdist', note: 'DP over two sequences: the cheapest edits to turn one string into another, one cell per prefix pair.' },
      { id: 'diff', note: 'The same longest-common-subsequence DP is exactly how git diff lines up two files.' },
      { id: 'seamcarve', note: 'DP over a pixel grid: the least-energy connected seam, for content-aware image resizing.' },
      { id: 'viterbi', note: 'DP over a probability trellis: the single most likely hidden sequence — speech, decoding, tagging.' },
    ],
  },
  {
    id: 'iterative',
    title: 'How computers converge on an answer',
    icon: '🔁',
    blurb: 'Most real math has no closed form, so computers iterate: start with a guess and improve it until it stops changing. Five very different problems, all solved by convergence.',
    steps: [
      { id: 'newton', note: 'Root-finding by tangent steps — the correct digits roughly double each iteration (quadratic convergence).' },
      { id: 'conjgrad', note: 'Solve a linear system Ax=b by conjugate directions — exact in n steps, far fewer when preconditioned.' },
      { id: 'pagerank', note: 'Find a matrix’s dominant eigenvector by multiplying repeatedly — the random surfer’s stationary distribution.' },
      { id: 'kmeans', note: 'Alternate assign-to-nearest and move-the-center until the clustering stops changing.' },
      { id: 'montecarlo', note: 'When you can’t integrate, sample at random — the estimate’s error shrinks as 1/√N.' },
    ],
  },
  {
    id: 'memory',
    title: 'Allocating and reclaiming memory',
    icon: '🧹',
    blurb: 'A program asks for memory and later stops using it — but how is it handed out, and how does the system know when it’s free again? Allocation, then three ways to reclaim, each fixing the last one’s blind spot.',
    steps: [
      { id: 'buddyalloc', note: 'Allocation: the kernel hands out memory in power-of-two blocks, splitting and merging buddies to fight fragmentation.' },
      { id: 'arena', note: 'The opposite extreme: one block, one bump pointer, no per-object free — reset the whole arena at once when the request or frame ends.' },
      { id: 'refcount', note: 'The simplest reclaim: count references and free at zero — but a reference cycle keeps itself alive and leaks.' },
      { id: 'gc', note: 'Tracing mark-and-sweep collects from the roots instead, so it reclaims the cycles reference counting can’t.' },
      { id: 'cheney', note: 'A copying collector goes further — it relocates the survivors into a fresh space, compacting fragmentation away.' },
    ],
  },
  {
    id: 'query',
    title: 'How a database answers a query',
    icon: '📇',
    blurb: 'The read path: find the rows with an index, combine tables with a join, handle inputs far bigger than memory, and let the planner pick the cheapest way to do it all.',
    steps: [
      { id: 'btree', note: 'The B+tree index finds a row by sorted key in a handful of disk seeks — the default database index.' },
      { id: 'exthash', note: 'A hash index finds rows by exact key and grows without rehashing, splitting one bucket at a time.' },
      { id: 'joins', note: 'Combine two tables on a key — nested-loop, hash, or sort-merge, all returning the same rows at different costs.' },
      { id: 'gracejoin', note: 'When both tables dwarf memory, partition by hash and join the aligned partition-pairs one at a time.' },
      { id: 'queryplan', note: 'The optimizer estimates the cost of each index and join order, then picks the cheapest plan to execute.' },
    ],
  },
  {
    id: 'moderncrypto',
    title: 'Cryptography beyond secrecy',
    icon: '🔏',
    blurb: 'Crypto is more than hiding messages. Commit to a value, prove membership, transfer a choice obliviously, generate verifiable randomness — then go post-quantum and meet the lattice attack that sets the bar.',
    steps: [
      { id: 'pedersen', note: 'A commitment locks in a value you can’t change but haven’t revealed — Pedersen commitments are perfectly hiding, computationally binding.' },
      { id: 'merkle', note: 'A Merkle tree commits to a whole set with one hash and proves any member belongs with a short path.' },
      { id: 'accumulator', note: 'An RSA accumulator commits to a set with one number and proves membership with one number — constant size, no growing path.' },
      { id: 'ot', note: 'Oblivious transfer: the sender offers two messages, the receiver takes one, and neither learns the other’s choice — the seed of secure computation.' },
      { id: 'garbled', note: 'Yao garbled circuits build on OT: two parties compute f(a,b) revealing neither input, by evaluating an encrypted, shuffled gate.' },
      { id: 'vrf', note: 'A verifiable random function emits randomness plus a proof it was computed correctly — unpredictable yet checkable.' },
      { id: 'sumcheck', note: 'The sumcheck protocol proves a huge sum over 2ⁿ inputs in n cheap rounds and one evaluation — the engine inside modern SNARKs.' },
      { id: 'vdf', note: 'A verifiable delay function forces a fixed sequential compute (repeated squaring) that a tiny proof checks fast — unbiasable randomness beacons.' },
      { id: 'pqc', note: 'Post-quantum encryption hides a bit in noise (Learning With Errors), staying secure even against a quantum computer.' },
      { id: 'lll', note: 'And the attack that sets the bar: LLL reduces a lattice basis to find short vectors — why lattice crypto needs hundreds of dimensions.' },
    ],
  },
  {
    id: 'privacy',
    title: 'Privacy beyond encryption',
    icon: '🕶️',
    blurb: 'Encryption hides the contents of your data — but not the statistics you publish, the computation you run, the queries you make, or the blocks you touch. Four techniques that hide those too.',
    steps: [
      { id: 'diffpriv', note: 'Publish statistics about a group while provably hiding every individual — add calibrated Laplace noise (differential privacy).' },
      { id: 'garbled', note: 'Compute a function of two parties’ secret inputs, revealing neither — Yao garbled circuits.' },
      { id: 'pir', note: 'Fetch a record from a database without the server learning which record you asked for.' },
      { id: 'oram', note: 'Hide even your access pattern to your own outsourced storage — every access looks like a random path.' },
    ],
  },
  {
    id: 'arithmetic',
    title: 'From transistors to matrix multiply',
    icon: '🔢',
    blurb: 'Build arithmetic from the bottom up: a transistor is a switch, switches make an adder, an adder plus logic makes an ALU, a tree of adders multiplies fast, and a grid of multiply-accumulate cells becomes the matrix engine inside a TPU.',
    steps: [
      { id: 'transistor', note: 'The switch: a voltage on the gate opens or closes a channel — the physical 1s and 0s under everything else.' },
      { id: 'adder', note: 'Wire gates into a binary adder; the carry ripples (or looks ahead) to sum two numbers bit by bit.' },
      { id: 'alu', note: 'The compute core: an adder plus logic gates and a mux the opcode uses to pick add/sub/and/or/shift, raising the flags.' },
      { id: 'wallace', note: 'Multiplication done fast: a Wallace tree reduces the partial-product dot diagram with carry-save adders in O(log n) depth.' },
      { id: 'systolic', note: 'Now tile multiply-accumulate cells into a grid: data flows through and a whole matrix multiply falls out — the heart of a TPU.' },
    ],
  },
  {
    id: 'sortselect',
    title: 'How computers sort and select',
    icon: '📊',
    blurb: 'From the five textbook sorts to the one in your standard library, then the flip side: finding the k-th element without sorting at all. Partitioning is the thread that ties them together.',
    steps: [
      { id: 'sorting', note: 'The five textbook sorts — bubble, insertion, selection, merge, quicksort — and the O(n²) vs O(n log n) gap between them.' },
      { id: 'timsort', note: 'The real-world hybrid (Python, Java, Rust default): exploit natural runs, merge in balanced order, gallop — adaptive and stable.' },
      { id: 'dnf', note: 'Dutch national flag: partition into <, =, > a pivot in one linear pass — the three-way split quicksort and selection lean on.' },
      { id: 'quickselect', note: 'Don’t sort to find the k-th element — partition and recurse into only the side that holds it, O(n) on average.' },
      { id: 'medianofmedians', note: 'Choose the pivot as a median of medians and quickselect becomes O(n) even in the worst case — a provably good split.' },
      { id: 'heap', note: 'A binary heap keeps the min or max at the root in O(log n) — heapsort, and the priority queue behind schedulers and Dijkstra.' },
    ],
  },
  {
    id: 'searching',
    title: 'How computers search for a solution',
    icon: '🧭',
    blurb: 'Most hard problems are a search through an enormous space of possibilities. The art is not visiting all of it — heuristics to aim, pruning to skip, propagation to shrink, and randomness to escape when exact search is hopeless.',
    steps: [
      { id: 'astar', note: 'Informed search: A* aims toward the goal with a heuristic, expanding far fewer nodes than blind breadth-first while still finding the shortest path.' },
      { id: 'alphabeta', note: 'Adversarial search: explore a game tree, but prune whole branches that provably can’t change the decision (alpha-beta) — searching deeper for free.' },
      { id: 'dpll', note: 'Systematic search: DPLL tries a variable, propagates forced consequences (unit propagation), and backtracks on conflict — the backbone of SAT solvers.' },
      { id: 'twosat', note: 'When structure helps: 2-SAT looks NP-hard but the implication graph makes it linear-time — the right model collapses the search entirely.' },
      { id: 'wfc', note: 'Constraint propagation as generation: collapse the most-constrained choice, then ripple the consequences outward — arc-consistency building a valid pattern.' },
      { id: 'simanneal', note: 'When exact is hopeless: wander the space accepting occasional worse moves, cooling over time — stochastic local search that escapes local optima.' },
    ],
  },
  {
    id: 'digitalaudio',
    title: 'How digital audio works',
    icon: '🎧',
    blurb: 'A sound is just a list of numbers. Analyze it into frequencies, hear its pitch, synthesize new timbres from scratch, place it in a room, and shrink it by an order of magnitude — the signal-processing pipeline behind every note you hear from a computer.',
    steps: [
      { id: 'fft', note: 'Every sound is a sum of pure tones. The FFT converts between the waveform (samples in time) and its spectrum (how much of each frequency) in O(n log n) — the lens for everything else.' },
      { id: 'pitch', note: 'What note is this? Autocorrelation slides a sound against itself and finds the lag where it best repeats — that period is the pitch a tuner shows.' },
      { id: 'goertzel', note: 'Detecting one specific tone — a phone touch-tone — doesn’t need a full FFT: the Goertzel algorithm evaluates a single frequency bin with a tiny recurrence.' },
      { id: 'karplus', note: 'Synthesize a plucked string from almost nothing: fill a short delay line with noise and feed it back through a lowpass — the Karplus–Strong pluck.' },
      { id: 'adsr', note: 'Shape the raw tone into a note: an ADSR envelope swells and fades the amplitude (attack, decay, sustain, release) so it doesn’t click and sounds like a pluck or a pad.' },
      { id: 'fmsynth', note: 'Wobble one oscillator’s frequency with another and rich Bessel-weighted sidebands bloom — Chowning’s FM synthesis, the sound of the DX7.' },
      { id: 'convreverb', note: 'Put a dry sound in a cathedral by convolving it with the room’s impulse response — every echo of the space applied at once.' },
      { id: 'biquad', note: 'Shape the tone with a filter: a two-pole biquad passes or cuts bands (lowpass, notch, resonant peak) — the unit cell of every EQ and synth filter.' },
      { id: 'mp3', note: 'Shrink audio ~10× by discarding what the ear can’t hear: psychoacoustic masking drops quiet tones hidden next to loud ones.' },
    ],
  },
  {
    id: 'noisychannel',
    title: 'How bits survive a noisy channel',
    icon: '📡',
    blurb: 'A wire carries voltage, not bits, and it corrupts what it carries. Follow a message down the stack: turned into a signal, framed into packets, checked for corruption, and — when noise still wins — repaired in place without asking for a resend.',
    steps: [
      { id: 'linecode', note: 'First bits become a physical signal — voltage levels and transitions. A good line code (Manchester, 8b/10b) keeps the receiver’s clock recoverable and the line DC-balanced.' },
      { id: 'cobs', note: 'The receiver must find where each packet ends. COBS byte-stuffing removes every zero byte so a lone zero can mark the boundary unambiguously — framing at almost no cost.' },
      { id: 'crc32', note: 'Noise flips bits in transit. A CRC treats the message as a polynomial and divides by a fixed one; the remainder is a checksum that catches virtually all real-world errors cheaply.' },
      { id: 'hamming', note: 'Detection only means “resend.” To fix a single flipped bit in place, add parity bits: Hamming(7,4) pinpoints exactly which bit went wrong and flips it back.' },
      { id: 'reedsolomon', note: 'Real channels corrupt whole bursts — scratches, fades, dead pixels. Reed–Solomon works over polynomials to correct bursts and erasures; it’s in CDs, QR codes, and deep-space links.' },
    ],
  },
  {
    id: 'hashing',
    title: 'Where does this key go? (hashing)',
    icon: '🪣',
    blurb: 'A hash turns a key into a location. Start with one table and its collisions, tighten the worst-case lookup, then scale the same question across a whole cluster — where adding or removing a server should move as few keys as possible.',
    steps: [
      { id: 'hashtable', note: 'Turn a key into a bucket index with a hash, and handle two keys landing in the same bucket — collisions — by chaining or probing. The O(1)-average lookup behind every dictionary.' },
      { id: 'cuckoo', note: 'Guarantee O(1) worst-case lookup: each key lives in one of just two buckets, and inserting kicks the current occupant to its alternate slot, cuckoo-style, until everyone fits.' },
      { id: 'robinhood', note: 'Even out probe lengths in open addressing: if you’ve probed further than the key you’re looking at, steal its slot and push it onward — robbing the rich to help the poor, so the worst lookup stays short.' },
      { id: 'chash', note: 'Now spread keys across many servers so adding or removing one moves only ~1/N of keys, not all of them: consistent hashing places servers and keys on a ring.' },
      { id: 'jumphash', note: 'A memoryless consistent hash: map a key to one of N shards with a tiny loop — no ring, no table — so growing N by one moves only the keys that should move.' },
      { id: 'rendezvous', note: 'Highest-Random-Weight: score a key against every node and pick the top — no ring, an even spread, and the full ranking doubles as a replica preference list.' },
    ],
  },
  {
    id: 'balanced',
    title: 'Keeping search O(log n) (balanced structures)',
    icon: '⚖️',
    blurb: 'A plain binary search tree degrades to a linked list on sorted input. Five different strategies keep search logarithmic — strict rotations, randomness, self-adjustment, coin-flip lanes, and a heap-BST hybrid.',
    steps: [
      { id: 'avl', note: 'The strict way: after each insert, rotate so no node’s two subtrees differ in height by more than 1 — a guaranteed O(log n) height, paid for with rebalancing on every change.' },
      { id: 'treap', note: 'The lazy way: give each key a random priority and keep a heap on priorities atop the BST on keys. Random priorities balance the tree in expectation, with no explicit balance rules.' },
      { id: 'splaytree', note: 'The adaptive way: don’t balance by height at all — splay every accessed node to the root, so recently-used keys stay near the top and hot workloads run fast (amortized O(log n)).' },
      { id: 'skiplist', note: 'Drop the tree: stack sorted linked lists with coin-flip express lanes; a search rides the top lane down — O(log n) expected with far simpler code (it’s inside Redis and LevelDB).' },
      { id: 'cartesian', note: 'The dual view: a tree that’s a BST on position and a heap on value at once, so range-minimum queries become lowest-common-ancestor lookups — two classic problems, one structure.' },
    ],
  },
  {
    id: 'routingpaths',
    title: 'How packets find their way (routing)',
    icon: '🗺️',
    blurb: 'A packet carries a destination, not a route. Follow how each hop decides where to send it — the forwarding lookup, the two ways routers learn paths, inter-domain policy, and the trust gap that lets traffic be hijacked.',
    steps: [
      { id: 'lpm', note: 'The per-hop decision: a router matches the destination against its table and picks the most specific (longest) prefix — the single lookup every packet triggers at every hop.' },
      { id: 'distvec', note: 'How routers learn routes without a map: each tells neighbors its distance to every destination and they keep the best — simple, but prone to slow count-to-infinity when a link fails.' },
      { id: 'ospf', note: 'The link-state alternative: every router floods the whole topology to everyone, then each runs Dijkstra on the identical map — fast convergence, at the cost of flooding.' },
      { id: 'bgp', note: 'Between autonomous systems it’s policy, not shortest path: BGP advertises AS-paths and each network picks by business rules, then forwards along the chosen one.' },
      { id: 'bgphijack', note: 'BGP trusts what it’s told, so a network announcing a prefix it doesn’t own can pull the world’s traffic to itself — the routing attack behind real outages and interceptions.' },
      { id: 'anycast', note: 'One IP announced from many locations at once; ordinary routing delivers each user to the nearest instance — how DNS roots and CDNs are everywhere at the same address.' },
    ],
  },
  {
    id: 'curvesigs',
    title: 'Signing on elliptic curves',
    icon: '🔏',
    blurb: 'Elliptic curves give a group where signatures are short and forgery is hard. Follow how curve signatures evolved — from the standard with its dangerous nonce, to deterministic, linear, aggregatable, and finally split-across-parties.',
    steps: [
      { id: 'ecc', note: 'The setting: adding points on an elliptic curve forms a group where a scalar times a point is easy but recovering the scalar (discrete log) is hard — far smaller keys than RSA for the same strength.' },
      { id: 'ecdsa', note: 'The standard curve signature (Bitcoin, TLS) — but it needs a fresh random nonce per signature, and a repeated or biased one leaks the private key outright.' },
      { id: 'eddsa', note: 'The modern fix: Ed25519 derives the nonce deterministically from the key and message, so a broken RNG can’t leak the key — fast and misuse-resistant.' },
      { id: 'schnorr', note: 'The clean scheme underneath: Schnorr signatures are linear, so several signers’ keys and signatures add into one — the basis of multisignatures (MuSig, Bitcoin Taproot).' },
      { id: 'bls', note: 'Go further with a pairing: BLS aggregates any number of signatures — even on different messages — into a single short one, verified in one shot (Ethereum consensus).' },
      { id: 'threshsig', note: 'Split the private key so no one holds it: any k of n parties jointly produce a valid signature but fewer cannot — threshold signing for custody and validators.' },
    ],
  },
  {
    id: 'dnssystem',
    title: 'The name system and its attacks',
    icon: '🏷️',
    blurb: 'Turning a name into an IP is a cached, trusting, plaintext lookup — which makes it a target. Follow the resolution, the classic cache-poisoning attack, the two things that harden it (signing and encryption), and two ways attackers still abuse names.',
    steps: [
      { id: 'dns', note: 'The lookup: a name becomes an IP by walking root → TLD → authoritative, and the answer is cached at every resolver along the way — which is exactly what makes it worth attacking.' },
      { id: 'kaminsky', note: 'Poison that cache: guess the query’s 16-bit ID and race a forged answer to the resolver before the real one arrives — the 2008 Kaminsky attack that forced source-port randomization.' },
      { id: 'dnssec', note: 'Sign the answers: a chain of signatures from the root down lets a resolver cryptographically reject forged records — authentication for DNS (but not encryption).' },
      { id: 'encdns', note: 'Hide the query: DoH/DoT wrap DNS in TLS so the network can’t see which names you look up or tamper with the reply — encryption, where DNSSEC only signs.' },
      { id: 'dnsrebind', note: 'Turn the browser into a proxy: after a page loads, rebind its hostname to 127.0.0.1 so the same-origin policy now lets the page talk to services on the victim’s own network.' },
      { id: 'subdomain', note: 'The dangling pointer: a DNS record still aimed at a deprovisioned cloud resource lets whoever re-registers that resource serve content as your subdomain.' },
    ],
  },
  {
    id: 'lockfree',
    title: 'Coordinating threads without locks',
    icon: '🔀',
    blurb: 'A mutex is easy to get wrong and slow when contended. Walk from a correct lock built from plain reads and writes, to a fast one, to lock-free reads, to readers that never block — and the subtle bug lurking underneath it all.',
    steps: [
      { id: 'bakery', note: 'A correct mutex from nothing but reads and writes: take a numbered ticket like a bakery queue and wait until you hold the lowest — Lamport’s proof that mutual exclusion needs no special hardware.' },
      { id: 'futex', note: 'The fast path: when a lock is uncontended, spin on an atomic in userspace and never enter the kernel; only call futex to sleep when you actually have to block. The mutex behind pthreads.' },
      { id: 'seqlock', note: 'Lock-free reads: a writer bumps a sequence counter around its update and a reader retries if it changed mid-read — perfect for rarely-written, often-read data like the kernel clock.' },
      { id: 'rcu', note: 'Readers that never block: read-copy-update publishes a new version and defers freeing the old copy until every pre-existing reader has finished — how Linux scales read-mostly structures across many cores.' },
      { id: 'aba', note: 'The lock-free trap: a compare-and-swap sees the same pointer value and assumes nothing changed — but it was freed and reallocated in between (ABA), corrupting the structure. Fixed with version tags or hazard pointers.' },
    ],
  },
  {
    id: 'tcptuning',
    title: 'TCP’s finer points',
    icon: '🛠️',
    blurb: 'The handshake and retransmission are only the start. These are the refinements and edge cases that decide how TCP actually behaves in production — from batching tiny writes to spreading one connection across two networks.',
    steps: [
      { id: 'nagle', note: 'Batch small writes: Nagle holds a tiny segment until the previous one is ACKed, coalescing keystrokes into fewer packets — but its interaction with delayed ACKs can stall a request 40–200 ms.' },
      { id: 'sws', note: 'Silly window syndrome: a slow reader advertising tiny windows and an eager sender filling them collapse a connection into a flood of runt segments — cured by Clark’s receiver rule and Nagle on the sender.' },
      { id: 'pmtud', note: 'Find the biggest packet that fits: Path MTU Discovery sends don’t-fragment probes and shrinks on the ICMP “too big” reply — and black-holes silently when a firewall eats those ICMPs.' },
      { id: 'tfo', note: 'Skip a round trip: TCP Fast Open carries data in the SYN using a server-issued cookie, so a repeat connection delivers the request before the handshake even finishes.' },
      { id: 'timewait', note: 'Why a closed socket lingers: the active closer holds TIME_WAIT for 2·MSL so a stray old segment can’t corrupt a new connection — which quietly exhausts ephemeral ports on a busy client.' },
      { id: 'mptcp', note: 'One connection, many paths: Multipath TCP spreads a single stream across wifi and cellular at once, surviving a path loss and pooling bandwidth — why a download survives leaving the house.' },
    ],
  },
  {
    id: 'disttime',
    title: 'Keeping time in a distributed system',
    icon: '⏱️',
    blurb: 'With no shared clock, machines disagree about “now” — and ordering events across them is a deep problem. Follow how systems synchronize physical time, bound its uncertainty, blend it with causality, and even use timing to decide who’s dead.',
    steps: [
      { id: 'ntp', note: 'Sync wall clocks over the network: NTP estimates the offset to a reference by timing a round trip and assuming symmetry — good to milliseconds, but never exact, and asymmetry skews it.' },
      { id: 'gps', note: 'The reference itself: GPS satellites carry atomic clocks, and your receiver solves for position AND precise time from the signal delays — the source many NTP servers ultimately trust.' },
      { id: 'truetime', note: 'Own the uncertainty instead of hiding it: Spanner’s TrueTime returns an interval [earliest, latest] for “now”, and commit-wait sleeps out that interval so transaction timestamps order globally.' },
      { id: 'hlc', note: 'Blend causality with the clock: Hybrid Logical Clocks track happened-before like a logical clock while staying within a bound of physical time — monotonic timestamps that also read like wall time.' },
      { id: 'phiaccrual', note: 'Turn timing into a verdict: the φ accrual failure detector scores how overdue a heartbeat is against its observed distribution, so “is that node dead?” becomes a tunable suspicion level, not a fixed timeout.' },
    ],
  },
  {
    id: 'physicsim',
    title: 'Simulating the physical world',
    icon: '⚛️',
    blurb: 'A physics or game engine turns forces into motion, keeps energy from leaking, scales to millions of bodies, and decides when things collide. Follow the pieces that make a simulated world move and touch.',
    steps: [
      { id: 'verlet', note: 'Move things by integrating forces: Verlet integration updates a particle from its last two positions, which makes stiff constraints (a rope’s links, a cloth’s grid) trivial to enforce — the backbone of game physics.' },
      { id: 'orbit', note: 'Keep energy from leaking: a naive integrator slowly spirals a stable orbit inward or outward, but a symplectic integrator conserves energy over millions of steps, so the planet keeps orbiting.' },
      { id: 'doublependulum', note: 'The limit of prediction: a double pendulum is fully deterministic yet chaotic — two runs a hair apart diverge exponentially, the same sensitivity that makes weather unforecastable past days.' },
      { id: 'barneshut', note: 'Scale to a galaxy: computing gravity between every pair is O(n²); the Barnes-Hut tree lumps a distant cluster into one mass, dropping it to O(n log n) with bounded error.' },
      { id: 'spatialhash', note: 'Find collision candidates fast: bucket objects into a grid by position so each one only tests its neighbors — skipping the O(n²) all-pairs check that dooms a naïve collision loop.' },
      { id: 'sat', note: 'Confirm the hit: the Separating Axis Theorem checks whether two convex shapes actually overlap by looking for a gap along any of their face normals — no separating axis means a collision.' },
    ],
  },
  {
    id: 'webattacks',
    title: 'How web apps get attacked (and defended)',
    icon: '🕳️',
    blurb: 'Most breaches aren’t exotic — they abuse a server that trusts input too much or a browser boundary that isn’t enforced. Six classic web-app attack classes, each shown sandboxed with the fix that closes it.',
    steps: [
      { id: 'ssrf', note: 'Make the server fetch for you: if an app requests a user-supplied URL, an attacker points it at internal services or cloud metadata (169.254.169.254) the outside can’t reach — closed by allow-lists and blocking link-local ranges.' },
      { id: 'xxe', note: 'Abuse the XML parser: a crafted external entity makes the parser read local files or make requests on the attacker’s behalf — closed by disabling external-entity resolution.' },
      { id: 'smuggle', note: 'Desync the pipeline: front-end and back-end disagree on where one request ends (Content-Length vs Transfer-Encoding), so a smuggled prefix poisons the next user’s response — closed by consistent parsing and HTTP/2.' },
      { id: 'openredirect', note: 'Borrow the site’s trust: an unvalidated redirect parameter sends users to an attacker’s page from a legitimate domain — the pivot in phishing and OAuth token theft, closed by allow-listing redirect targets.' },
      { id: 'clickjack', note: 'Steal the click: frame the real site invisibly over a decoy so a click on “win a prize” lands on “delete account” — closed by X-Frame-Options / frame-ancestors CSP.' },
      { id: 'protopollute', note: 'Poison the prototype: injecting a __proto__ key into a merged object writes onto every object’s prototype, flipping security checks — closed by null-prototype objects and rejecting __proto__ keys.' },
    ],
  },
  {
    id: 'graphalgos',
    title: 'Classic graph algorithms',
    icon: '🔗',
    blurb: 'So many problems are secretly a graph — dependencies, maps, networks, exchange rates. Six workhorse algorithms answer the recurring questions: order it, cluster it, connect it cheaply, find shortest paths, and push maximum flow.',
    steps: [
      { id: 'toposort', note: 'Order a DAG so every edge points forward: topological sort turns a graph of dependencies (build steps, course prereqs) into a valid linear schedule — or reports the cycle that makes one impossible.' },
      { id: 'scc', note: 'Find the tightly-knit clusters: a strongly connected component is a maximal set where every node reaches every other; condensing them collapses any directed graph into a DAG (Tarjan finds them in one DFS).' },
      { id: 'unionfind', note: 'Track connectivity as it grows: union-find answers “are these two in the same group?” in near-constant time with union-by-rank and path compression — the engine inside Kruskal and connected-components.' },
      { id: 'mst', note: 'Connect everything as cheaply as possible: a minimum spanning tree is the lowest-weight edge set that keeps the graph connected — Kruskal sorts edges and adds each unless it forms a cycle (checked with union-find).' },
      { id: 'bellmanford', note: 'Shortest paths even with negative edges: Bellman-Ford relaxes every edge V−1 times, and a further relaxation that still improves proves a negative cycle — which over exchange rates is an arbitrage loop.' },
      { id: 'maxflow', note: 'Push as much as the network allows: max-flow augments along residual paths until none remain, and the min-cut — the bottleneck edges — always equals the maximum flow.' },
    ],
  },
  {
    id: 'webtransport',
    title: 'How the web got faster (HTTP/2 → HTTP/3)',
    icon: '⚡',
    blurb: 'HTTP/1 opened a fresh connection per request and blocked on the slow ones. Follow the fixes — multiplexing, flow control, a new transport on UDP, connection migration, and zero-round-trip resumption — that turned the web fast.',
    steps: [
      { id: 'http2', note: 'One connection, many streams: HTTP/2 multiplexes independent requests over a single connection, so a big download no longer blocks small ones behind it — the first cure for HTTP/1’s head-of-line blocking.' },
      { id: 'h2flow', note: 'Share the pipe fairly: per-stream flow-control windows let the receiver throttle a firehose stream without stalling the others sharing the connection.' },
      { id: 'quic', note: 'But TCP still blocks: one lost packet stalls every HTTP/2 stream (transport head-of-line blocking). QUIC rebuilds the transport on UDP so each stream recovers independently — and folds in the TLS handshake for fewer round trips.' },
      { id: 'quicmig', note: 'Survive changing networks: QUIC names a connection by a connection ID, not the IP/port 4-tuple, so it keeps going as you walk from wifi onto cellular — where TCP would drop and reconnect.' },
      { id: 'zerortt', note: 'Send data in the first packet: on resumption, TLS 1.3 / QUIC 0-RTT ships the request before the handshake completes — a round trip saved, at the cost of a replay risk that needs idempotent handling.' },
      { id: 'http3', note: 'HTTP over QUIC: HTTP/3 carries the same HTTP semantics on QUIC, with QPACK header compression redesigned so a lost header block can’t stall unrelated streams — head-of-line blocking gone end to end.' },
    ],
  },
  {
    id: 'compgeom',
    title: 'Computational geometry',
    icon: '📐',
    blurb: 'Reasoning about points and shapes in the plane underlies maps, meshes, graphics, and simulation. Six algorithms: wrap a point set, triangulate it, partition around it, index it for nearest-neighbor, scatter points evenly, and trace a contour.',
    steps: [
      { id: 'convexhull', note: 'The tightest boundary: the convex hull is the shape a rubber band snaps to around a scatter of points — a sort plus a stack scan (Graham/Andrew) in O(n log n), the first step of countless geometry algorithms.' },
      { id: 'delaunay', note: 'The best triangulation: connect points into triangles so no point lies inside any triangle’s circumcircle, which maximizes the smallest angle and avoids slivers — the mesh behind terrain and finite-element grids.' },
      { id: 'voronoi', note: 'The dual partition: split the plane into one cell per point, each the region closest to that point. It’s the exact dual of the Delaunay triangulation — two points’ cells touch iff they’re Delaunay neighbors.' },
      { id: 'kdtree', note: 'Nearest neighbor, fast: a k-d tree recursively splits space on alternating axes, so a nearest-point query prunes whole half-spaces instead of scanning every point — O(log n) average in low dimensions.' },
      { id: 'poisson', note: 'Points that don’t clump: Poisson-disk sampling scatters random points no two closer than r apart (“blue noise”), the natural, even spread used for stippling, textures, and anti-aliasing.' },
      { id: 'marchsquares', note: 'From a field to a contour: marching squares walks a grid of scalar values and, cell by cell, draws the line where the field crosses a threshold — the 2D isoline, and the ancestor of marching cubes.' },
    ],
  },
  {
    id: 'authpath',
    title: 'Proving who you are online',
    icon: '🪪',
    blurb: 'Every login is a proof of identity — and each protocol makes that proof differently. Walk from the basic factors through a second factor, stateless tokens, enterprise single sign-on, server login, and proving which domain sent an email.',
    steps: [
      { id: 'identity', note: 'The landscape: authentication proves who you are, authorization decides what you may do. Factors are things you know (a password), have (a phone or key), or are (a fingerprint) — and combining kinds is what makes two-factor strong.' },
      { id: 'totp', note: 'A second factor from a shared secret: TOTP hashes a secret with the current 30-second time window (RFC 6238) into a 6-digit code, so your authenticator app and the server derive the same number without ever communicating.' },
      { id: 'jwt', note: 'A token trusted without a lookup: a JWT is a signed JSON claim the client carries, verified by signature alone — fast and stateless, but infamous for the alg=none and algorithm-confusion attacks when the verifier believes the token’s own header.' },
      { id: 'kerberos', note: 'Single sign-on with tickets: authenticate once to a key distribution center for a ticket-granting ticket, then exchange it for per-service tickets — proving identity to many services without resending your password.' },
      { id: 'ssh', note: 'Logging into a server: SSH authenticates you by public key (the server challenges, you sign) and authenticates the server by its host key, pinned on first use — the mutual check that stops a machine-in-the-middle.' },
      { id: 'mailauth', note: 'Proving a domain sent the mail: SPF lists which IPs may send for a domain and DKIM signs the message with the domain’s key, so a receiver can reject forgeries — the anti-phishing backbone, aligned by DMARC.' },
    ],
  },
  {
    id: 'numerics',
    title: 'Fast and careful arithmetic',
    icon: '🧮',
    blurb: 'Numbers on a computer are neither exact nor free. Follow how fractions are actually stored, how precision is lost and recovered, and the bit-level and divide-and-conquer tricks that make square roots, trig, and big multiplies fast.',
    steps: [
      { id: 'float', note: 'How a computer stores a fraction: IEEE-754 splits a number into sign, exponent, and mantissa — which is why 0.1 has no exact binary form and 0.1 + 0.2 ≠ 0.3. The representation every other numeric trick works within.' },
      { id: 'kahan', note: 'Careful summation: adding many floats drops the low bits of each step, so a long sum drifts; Kahan’s algorithm carries a running compensation term for what was lost, recovering near-full precision.' },
      { id: 'fastinvsqrt', note: 'The bit-level hack: Quake’s 1/√x reinterprets the float’s bits as an integer, subtracts that from 0x5f3759df to halve-and-negate the exponent, then refines with one Newton step — a reciprocal square root with no divide.' },
      { id: 'cordic', note: 'Trig with only shifts and adds: CORDIC rotates a vector by ever-smaller fixed angles, picking each direction by sign, to compute sine, cosine, and more — how calculators and FPGAs do trig with no multiplier.' },
      { id: 'karatsuba', note: 'Multiply big numbers faster: splitting each factor in half naively needs four sub-multiplies, but Karatsuba does it in three, turning O(n²) into O(n^1.585) — the first step beyond schoolbook multiplication.' },
      { id: 'ntt', note: 'Fast polynomial multiply: the number-theoretic transform is an FFT over a finite field — transform, multiply pointwise, transform back for O(n log n) products. The engine inside lattice crypto like Kyber.' },
    ],
  },
  {
    id: 'leaderless',
    title: 'A datastore with no leader',
    icon: '🌐',
    blurb: 'Dynamo-style stores (Cassandra, Riak) have no primary node — every peer is equal. Follow how a leaderless cluster locates keys, spreads news, detects failures, and stays consistent, all without a central coordinator.',
    steps: [
      { id: 'chord', note: 'Locate a key with no directory: Chord arranges nodes in a hash ring, each owning the keys up to its successor, and routes lookups in O(log n) hops with a finger table of exponentially-spaced shortcuts — a distributed hash table with no central index.' },
      { id: 'gossip', note: 'Spread news like a rumor: each node periodically tells a few random peers what it knows, so an update reaches everyone in O(log n) rounds — the epidemic protocol that disseminates membership and state without a coordinator.' },
      { id: 'swim', note: 'Detect failures at scale: SWIM has each node ping a random peer and, on silence, ask others to ping it before declaring it dead — spreading suspicion over gossip, so failure detection stays constant work per node.' },
      { id: 'hintedhandoff', note: 'Stay writable when a replica is down: a peer accepts the write on the absent node’s behalf and stores a hint, replaying it once the node returns — availability during a partition, at the cost of temporary divergence.' },
      { id: 'readrepair', note: 'Fix staleness on read: when a read gathers replicas that disagree, the newest value is returned and the lagging replicas are updated in the background — cheap convergence driven by ordinary traffic.' },
      { id: 'antientropy', note: 'Reconcile what reads miss: nodes periodically compare Merkle-tree hashes of their key ranges and exchange only the differing parts, healing replicas no recent read touched — the backstop for eventual consistency.' },
    ],
  },
  {
    id: 'symmcrypto',
    title: 'Inside symmetric crypto',
    icon: '🔐',
    blurb: 'One shared key, used to both scramble and authenticate. Follow the building blocks — a reversible block cipher, a modern stream cipher, two kinds of message authenticator, and the timing side channel that undoes them if you compare carelessly.',
    steps: [
      { id: 'feistel', note: 'Make a cipher reversible for free: a Feistel network (DES) splits each block in half and each round mixes one half through a function of the other, then swaps — decryption runs the identical steps in reverse, so the round function itself never needs to be invertible.' },
      { id: 'aesround', note: 'The modern block cipher: each AES round substitutes bytes through an S-box, shifts rows, mixes columns, and XORs in a round key — confusion and diffusion repeated 10–14 times until every output bit depends on every input and key bit.' },
      { id: 'chacha', note: 'Encrypt as a keystream: ChaCha20 builds a stream cipher from add-rotate-XOR quarter-rounds on a 4×4 state — no S-box, no data-dependent table lookups — and XORs the output over the plaintext, fast and constant-time in software.' },
      { id: 'poly1305', note: 'Authenticate in one shot: Poly1305 treats the message as the coefficients of a polynomial and evaluates it at a secret point modulo 2¹³⁰−5, producing a 16-byte tag — a one-time MAC that pairs with ChaCha20 for authenticated encryption.' },
      { id: 'hmac', note: 'A MAC from any hash: HMAC nests two keyed hashes — H((k⊕opad) ∥ H((k⊕ipad) ∥ m)) — authenticating a message and resisting the length-extension attack that a naive H(k ∥ m) falls to.' },
      { id: 'consttime', note: 'The timing side channel: comparing a tag or password byte by byte and returning on the first mismatch leaks how many bytes matched through timing — so crypto compares in constant time, touching every byte regardless of where they differ.' },
    ],
  },
  {
    id: 'failover',
    title: 'Agreeing and failing over',
    icon: '🗳️',
    blurb: 'When any node can crash, pause, or lie, a cluster still has to agree who leads, replicate consistently, and commit work. Walk from electing a leader to Byzantine consensus and transaction failover.',
    steps: [
      { id: 'bully', note: 'Pick a coordinator when the old one dies: the bully algorithm has any node that notices the leader is gone challenge everyone with a higher id, and the highest-id live node wins and announces itself — leader election after a crash.' },
      { id: 'leases', note: 'Hold leadership on a timer: a leader takes a lease valid for a bounded time and must renew it, so if it dies the lease simply expires and another can take over — but the scheme rests on clocks not drifting too far apart.' },
      { id: 'fencing', note: 'Stop a zombie leader: one that paused (a GC stall) can wake believing it still leads. A monotonically increasing fencing token on every write lets the storage reject anything stamped with an old number.' },
      { id: 'chainrep', note: 'Replicate in a line: chain replication passes each write head→tail through the replicas and serves reads only at the tail, giving strong consistency and a simple, well-defined failover when any link dies.' },
      { id: 'pbft', note: 'Agree despite traitors: Practical Byzantine Fault Tolerance reaches consensus even when up to a third of nodes lie or send conflicting messages, by voting in rounds and acting only on a two-thirds quorum — the basis of many permissioned blockchains.' },
      { id: 'saga', note: 'Fail forward across services: a saga replaces one distributed transaction with a chain of local ones, each paired with a compensating action, so a failure partway is cleaned up by running the compensations backward — no global lock.' },
    ],
  },
  {
    id: 'texteditor',
    title: 'Data structures inside a text editor',
    icon: '📝',
    blurb: 'Editing a big document means inserting and deleting anywhere, fast, thousands of times a second — a plain array can’t keep up. Follow the buffers that make it cheap, plus the trie behind autocomplete and the persistent map behind undo.',
    steps: [
      { id: 'gapbuffer', note: 'The classic buffer (Emacs): keep an empty gap in the array right at the cursor, so typing and deleting there are O(1) — just move the gap’s edges. Moving the cursor shuffles the gap to the new spot.' },
      { id: 'piecetable', note: 'The modern buffer (VS Code): never mutate the loaded file; append every insertion to a separate add-buffer and keep an ordered list of pieces pointing into the original or the add-buffer — cheap edits and near-free undo.' },
      { id: 'rope', note: 'For a huge document: a rope stores the text as a balanced tree of small chunks, so insert, delete, and index-by-position are O(log n) instead of O(n) on one giant contiguous array — the buffer that scales to gigabytes.' },
      { id: 'trie', note: 'Autocomplete as you type: a trie stores words along shared-prefix paths, so completing what you’ve typed is a walk of one node per character down to the subtree of everything that continues it.' },
      { id: 'hamt', note: 'Undo without copying: a hash array mapped trie is an immutable map where each edit shares almost all its structure with the previous version — so keeping every past state for undo (or collaborative editing) costs only the changed path.' },
    ],
  },
  {
    id: 'localnet',
    title: 'How a local network works',
    icon: '🔌',
    blurb: 'Before a packet ever reaches the internet it has to survive the local link — sharing the medium, getting an address, and finding its neighbors. Follow a device from joining the wire to discovering the printer down the hall.',
    steps: [
      { id: 'csma', note: 'Share the air with no scheduler: WiFi’s CSMA/CA has each device listen first and, if the channel is busy, wait a random backoff before transmitting — collisions are avoided by politeness, not a central slot assignment.' },
      { id: 'stptree', note: 'Keep frames from looping forever: with redundant links a broadcast would circulate endlessly, so the Spanning Tree Protocol elects a root switch and disables backup links to leave one loop-free path — re-enabled if a link fails.' },
      { id: 'vlan', note: 'Many networks on one switch: an 802.1Q VLAN tag in the frame header partitions a physical switch fabric into isolated virtual LANs, so ports in different VLANs can’t reach each other without going through a router.' },
      { id: 'dhcp', note: 'Get an address on joining: a new device broadcasts and a DHCP server answers in four steps — Discover, Offer, Request, Ack (DORA) — leasing it an IP, gateway, and DNS server so it can start talking.' },
      { id: 'icmp', note: 'How the network reports back: ICMP carries the control and error messages IP itself can’t — echo request/reply is ping, and time-exceeded is how traceroute maps every hop along a path.' },
      { id: 'mdns', note: 'Find services with no server: mDNS resolves .local names by multicasting the query to the whole link and DNS-SD advertises what each device offers — how your laptop finds a printer or a Chromecast with nothing configured.' },
    ],
  },
  {
    id: 'trafficshape',
    title: 'Shaping and limiting traffic',
    icon: '🚦',
    blurb: 'A shared link or service has a finite rate, so traffic has to be capped, smoothed, prioritized, and told to slow down. Follow the algorithms that limit senders and keep queues — and latency — under control.',
    steps: [
      { id: 'ratelimit', note: 'Cap the rate with room for bursts: a token bucket adds tokens at a fixed rate up to a cap and each request spends one, so steady traffic is limited but a short burst can drain the saved tokens at once — the classic API rate limiter.' },
      { id: 'leakybucket', note: 'Smooth a bursty stream: the leaky bucket queues arrivals and drains at a constant rate, so however spiky the input, the output is a steady trickle — shaping traffic to a fixed rate rather than only capping it.' },
      { id: 'gcra', note: 'Rate-limit with no queue: the generic cell rate algorithm tracks a single theoretical arrival time and admits a packet only if it isn’t too early — enforcing a rate and a burst allowance with one comparison and no stored queue.' },
      { id: 'qos', note: 'Decide who goes first: when a link is contended, QoS scheduling — priority queues, weighted fair queuing — serves classes of traffic in a chosen order, so a latency-sensitive packet isn’t stuck behind a bulk download.' },
      { id: 'ecn', note: 'Signal congestion without dropping: instead of discarding a packet when a queue fills, ECN sets a mark the receiver echoes back, telling the sender to slow down — congestion feedback a full round trip earlier than a loss would give.' },
      { id: 'bufferbloat', note: 'The latency trap: oversized buffers never drop, so they fill with a huge standing backlog that adds seconds of delay; active queue management (CoDel) watches how long packets sit and drops early to keep the queue — and latency — short.' },
    ],
  },
];

export const pathById: Record<string, LearningPath> = Object.fromEntries(PATHS.map((p) => [p.id, p]));

/** The index of `sectionId` within a path's steps, or -1 if the learner has stepped off the path. */
export function stepIndexOf(path: LearningPath, sectionId: string): number {
  return path.steps.findIndex((s) => s.id === sectionId);
}
