// Sidebar taxonomy — the 32 sections grouped into collapsible categories so the
// nav stays navigable. Pure data + a tiny lookup, kept here (and tested) so the
// grouping can't silently drift out of sync with the sections themselves.

export interface SectionMeta { id: string; label: string; icon: string }

export const SECTION_META: SectionMeta[] = [
  { id: 'network', label: 'Network', icon: '🌐' },
  { id: 'switch', label: 'L2 switch', icon: '🔌' },
  { id: 'dhcp', label: 'DHCP (DORA)', icon: '📨' },
  { id: 'nat', label: 'NAT / PAT', icon: '🔀' },
  { id: 'ttlhop', label: 'TTL & checksum', icon: '⏬' },
  { id: 'traceroute', label: 'Traceroute', icon: '🛰️' },
  { id: 'subnet', label: 'Subnetting', icon: '🧮' },
  { id: 'pmtud', label: 'Path MTU Discovery', icon: '📏' },
  { id: 'fragment', label: 'IP fragmentation', icon: '🧩' },
  { id: 'natpunch', label: 'NAT traversal', icon: '🕳️' },
  { id: 'ipcompare', label: 'IPv4 vs IPv6', icon: '⇄' },
  { id: 'happyeyeballs', label: 'Happy Eyeballs', icon: '👀' },
  { id: 'sctp', label: 'SCTP multi-homing', icon: '🔀' },
  { id: 'nagle', label: 'Nagle & delayed ACK', icon: '🐢' },
  { id: 'icmp', label: 'ICMP messages', icon: '🚨' },
  { id: 'anycast', label: 'Anycast', icon: '📡' },
  { id: 'multicast', label: 'Multicast & IGMP', icon: '📡' },
  { id: 'wpa', label: 'WPA2 handshake', icon: '📶' },
  { id: 'dot1x', label: '802.1X / EAPOL', icon: '🔌' },
  { id: 'vlan', label: 'VLAN tagging', icon: '🏷️' },
  { id: 'ntp', label: 'NTP clock sync', icon: '🕰️' },
  { id: 'btree', label: 'B+tree index', icon: '🌲' },
  { id: 'pagereplace', label: 'Page replacement', icon: '📄' },
  { id: 'lsm', label: 'LSM-tree', icon: '🪵' },
  { id: 'mvcc', label: 'MVCC isolation', icon: '🔀' },
  { id: 'wal', label: 'Write-Ahead Log', icon: '📒' },
  { id: 'skiplist', label: 'Skip list', icon: '🪜' },
  { id: 'locking', label: 'Locking & deadlock', icon: '🔒' },
  { id: 'joins', label: 'Join algorithms', icon: '🔗' },
  { id: 'queryplan', label: 'Query planner (cost)', icon: '🧠' },
  { id: 'rum', label: 'RUM amplification', icon: '⚖️' },
  { id: 'trie', label: 'Trie (prefix tree)', icon: '🌿' },
  { id: 'hashtable', label: 'Hash table collisions', icon: '🗃️' },
  { id: 'cuckoo', label: 'Cuckoo hashing', icon: '🐦' },
  { id: 'geohash', label: 'Geohashing', icon: '🌍' },
  { id: 'unionfind', label: 'Union-Find', icon: '🔗' },
  { id: 'fenwick', label: 'Fenwick tree', icon: '🌴' },
  { id: 'heap', label: 'Binary heap', icon: '⛰️' },
  { id: 'segtree', label: 'Segment tree', icon: '🌲' },
  { id: 'avl', label: 'AVL tree', icon: '🌳' },
  { id: 'sorting', label: 'Sorting algorithms', icon: '📊' },
  { id: 'quickselect', label: 'Quickselect (k-th)', icon: '🎯' },
  { id: 'aliasmethod', label: 'Alias method (weighted sampling)', icon: '🎰' },
  { id: 'kmp', label: 'KMP string search', icon: '🔎' },
  { id: 'editdist', label: 'Edit distance', icon: '📝' },
  { id: 'knapsack', label: '0/1 Knapsack (DP)', icon: '🎒' },
  { id: 'toposort', label: 'Topological sort', icon: '🔢' },
  { id: 'astar', label: 'A* pathfinding', icon: '🧭' },
  { id: 'maxflow', label: 'Max-flow / min-cut', icon: '🌊' },
  { id: 'mst', label: 'Minimum spanning tree', icon: '🌲' },
  { id: 'scc', label: 'Strongly connected comps', icon: '🔗' },
  { id: 'floyd', label: 'Floyd-Warshall (all-pairs)', icon: '🔲' },
  { id: 'bellmanford', label: 'Bellman-Ford & arbitrage', icon: '💱' },
  { id: 'newton', label: "Newton's method", icon: '➗' },
  { id: 'fft', label: 'Fast Fourier Transform', icon: '〰️' },
  { id: 'rabinkarp', label: 'Rabin-Karp', icon: '🎞️' },
  { id: 'ahocorasick', label: 'Aho-Corasick', icon: '🔱' },
  { id: 'boyermoore', label: 'Boyer-Moore search', icon: '🏃' },
  { id: 'suffixarray', label: 'Suffix array', icon: '🔡' },
  { id: 'manacher', label: 'Manacher (palindromes)', icon: '🔁' },
  { id: 'arp', label: 'ARP resolution', icon: '📇' },
  { id: 'stptree', label: 'Spanning Tree', icon: '🌳' },
  { id: 'slaac', label: 'IPv6 SLAAC', icon: '🆔' },
  { id: 'csma', label: 'WiFi CSMA/CA', icon: '📶' },
  { id: 'routing', label: 'Routing & paths', icon: '🧭' },
  { id: 'distvec', label: 'Distance-vector', icon: '📐' },
  { id: 'ospf', label: 'OSPF link-state', icon: '🗺️' },
  { id: 'bgp', label: 'BGP best-path', icon: '🥇' },
  { id: 'bgphijack', label: 'BGP hijack', icon: '🏴‍☠️' },
  { id: 'bgprr', label: 'BGP route reflectors', icon: '🪞' },
  { id: 'mpls', label: 'MPLS switching', icon: '🏷️' },
  { id: 'vxlan', label: 'VXLAN overlay', icon: '🪆' },
  { id: 'vrrp', label: 'VRRP redundancy', icon: '🛟' },
  { id: 'ipsec', label: 'IPsec ESP (VPN)', icon: '🔐' },
  { id: 'ecmp', label: 'ECMP load spreading', icon: '🔱' },
  { id: 'dnssec', label: 'DNSSEC chain', icon: '🔏' },
  { id: 'dns', label: 'DNS journey', icon: '🔎' },
  { id: 'mdns', label: 'mDNS & DNS-SD', icon: '🖨️' },
  { id: 'encdns', label: 'Encrypted DNS', icon: '🕵️' },
  { id: 'tcphand', label: 'TCP handshake', icon: '🤝' },
  { id: 'tfo', label: 'TCP Fast Open', icon: '⚡' },
  { id: 'zerortt', label: '0-RTT resumption & replay', icon: '⏩' },
  { id: 'congestion', label: 'TCP congestion', icon: '📈' },
  { id: 'cubic', label: 'TCP CUBIC', icon: '📈' },
  { id: 'bbr', label: 'TCP BBR', icon: '🌊' },
  { id: 'flow', label: 'Flow control', icon: '🪟' },
  { id: 'h2flow', label: 'H2/QUIC flow control', icon: '🚰' },
  { id: 'sack', label: 'TCP SACK', icon: '🎯' },
  { id: 'arq', label: 'ARQ (GBN vs SR)', icon: '🔁' },
  { id: 'rto', label: 'RTO & Karn', icon: '⏱️' },
  { id: 'bdp', label: 'Bandwidth-Delay Product', icon: '🪣' },
  { id: 'queueing', label: 'M/M/1 queueing', icon: '📉' },
  { id: 'bufferbloat', label: 'Bufferbloat', icon: '🚰' },
  { id: 'ecn', label: 'ECN marking', icon: '🚩' },
  { id: 'qos', label: 'QoS scheduling', icon: '🚦' },
  { id: 'http2', label: 'HTTP/2 multiplexing', icon: '🧵' },
  { id: 'quic', label: 'QUIC vs TCP', icon: '🚀' },
  { id: 'quicmig', label: 'QUIC connection migration', icon: '📶' },
  { id: 'http3', label: 'HTTP/3 & QPACK', icon: '🌐' },
  { id: 'websocket', label: 'WebSocket', icon: '🔌' },
  { id: 'realtime', label: 'Realtime: SSE vs WS', icon: '📡' },
  { id: 'grpc', label: 'gRPC & protobuf', icon: '📡' },
  { id: 'cdn', label: 'CDN & caching', icon: '⚡' },
  { id: 'conditional', label: 'Conditional & range', icon: '🔖' },
  { id: 'ratelimit', label: 'Rate limiting', icon: '🪣' },
  { id: 'leakybucket', label: 'Leaky bucket', icon: '🚿' },
  { id: 'retry', label: 'Retry & circuit breaker', icon: '🔁' },
  { id: 'crypto', label: 'Cryptography', icon: '🔒' },
  { id: 'classical', label: 'Classical ciphers', icon: '🏛️' },
  { id: 'otpad', label: 'One-time pad', icon: '🎲' },
  { id: 'ecbpenguin', label: 'ECB penguin / modes', icon: '🐧' },
  { id: 'aesround', label: 'AES internals', icon: '🧊' },
  { id: 'feistel', label: 'Feistel / DES', icon: '🔁' },
  { id: 'aead', label: 'CTR & AEAD', icon: '🔐' },
  { id: 'rsa', label: 'RSA', icon: '🗝️' },
  { id: 'ecc', label: 'Elliptic curves', icon: '➰' },
  { id: 'ecdsa', label: 'ECDSA & nonce reuse', icon: '✍️' },
  { id: 'eddsa', label: 'EdDSA (Ed25519)', icon: '🖋️' },
  { id: 'pedersen', label: 'Pedersen commitment', icon: '✉️' },
  { id: 'blindsig', label: 'Blind signatures', icon: '🙈' },
  { id: 'vrf', label: 'Verifiable random function', icon: '🎲' },
  { id: 'ot', label: 'Oblivious transfer', icon: '🤝' },
  { id: 'paillier', label: 'Homomorphic (Paillier)', icon: '➕' },
  { id: 'schnorr', label: 'Zero-knowledge (Schnorr)', icon: '🕵️‍♂️' },
  { id: 'chacha', label: 'ChaCha20', icon: '🌀' },
  { id: 'poly1305', label: 'Poly1305 MAC', icon: '🏷️' },
  { id: 'consttime', label: 'Timing attacks', icon: '⏱️' },
  { id: 'hashint', label: 'SHA-256 internals', icon: '🧮' },
  { id: 'hashbreak', label: 'Broken hashes', icon: '💥' },
  { id: 'dhkex', label: 'Diffie–Hellman', icon: '🤝' },
  { id: 'dhmitm', label: 'DH man-in-the-middle', icon: '🕴️' },
  { id: 'tlsdowngrade', label: 'TLS downgrade', icon: '⬇️' },
  { id: 'pwhash', label: 'Password hashing', icon: '🔑' },
  { id: 'pqc', label: 'Post-quantum (LWE)', icon: '🔮' },
  { id: 'ntt', label: 'NTT (Kyber engine)', icon: '🦋' },
  { id: 'bb84', label: 'Quantum key (BB84)', icon: '⚛️' },
  { id: 'certs', label: 'Certificates (PKI)', icon: '📜' },
  { id: 'kerberos', label: 'Kerberos', icon: '🎟️' },
  { id: 'revocation', label: 'Revocation & CT', icon: '🚫' },
  { id: 'ssh', label: 'SSH transport', icon: '🖧' },
  { id: 'identity', label: 'Identity & Auth', icon: '🪪' },
  { id: 'cors', label: 'CORS / Same-Origin', icon: '🚧' },
  { id: 'mailauth', label: 'Email auth (SPF/DKIM)', icon: '📧' },
  { id: 'webauthn', label: 'Passkeys (WebAuthn)', icon: '🔑' },
  { id: 'cookies', label: 'Cookies & sessions', icon: '🍪' },
  { id: 'csp', label: 'Content-Security-Policy', icon: '🧱' },
  { id: 'webinject', label: 'Injection (SQLi/XSS)', icon: '💉' },
  { id: 'smuggle', label: 'Request smuggling', icon: '📦' },
  { id: 'ssrf', label: 'SSRF', icon: '🎯' },
  { id: 'clickjack', label: 'Clickjacking', icon: '👆' },
  { id: 'hsts', label: 'HSTS & SSL stripping', icon: '🔒' },
  { id: 'openredirect', label: 'Open redirect', icon: '↪️' },
  { id: 'hashflood', label: 'Hash flooding (DoS)', icon: '🌊' },
  { id: 'redos', label: 'ReDoS (regex DoS)', icon: '💣' },
  { id: 'siteisolation', label: 'Site isolation', icon: '🧱' },
  { id: 'sri', label: 'Subresource Integrity', icon: '🔗' },
  { id: 'attacks', label: 'Attacks', icon: '⚔️' },
  { id: 'shamir', label: 'Secret sharing', icon: '🧩' },
  { id: 'feldman', label: 'Verifiable secret sharing', icon: '🧩' },
  { id: 'threshsig', label: 'Threshold signatures', icon: '✍️' },
  { id: 'pow', label: 'Proof of Work', icon: '⛏️' },
  { id: 'ratchet', label: 'Double Ratchet', icon: '🔗' },
  { id: 'x3dh', label: 'X3DH key agreement', icon: '🤝' },
  { id: 'hashchain', label: 'Hash chain', icon: '⛓️' },
  { id: 'merkle', label: 'Merkle tree', icon: '🌳' },
  { id: 'encoding', label: 'Encoding', icon: '🔤' },
  { id: 'varint', label: 'Varint & zigzag', icon: '📏' },
  { id: 'linecode', label: 'Line coding', icon: '〰️' },
  { id: 'lz77', label: 'LZ77 compression', icon: '🪟' },
  { id: 'lzw', label: 'LZW compression', icon: '📖' },
  { id: 'bwt', label: 'Burrows-Wheeler', icon: '🔄' },
  { id: 'mtf', label: 'Move-to-front', icon: '↩️' },
  { id: 'cdc', label: 'Content-defined chunking', icon: '✂️' },
  { id: 'dfa', label: 'Finite automata (DFA)', icon: '🔄' },
  { id: 'huffman', label: 'Huffman coding', icon: '🗜️' },
  { id: 'golombrice', label: 'Golomb-Rice coding', icon: '📐' },
  { id: 'arith', label: 'Arithmetic coding', icon: '🎯' },
  { id: 'viterbi', label: 'Viterbi / convolutional', icon: '🧬' },
  { id: 'reedsolomon', label: 'Reed-Solomon', icon: '💿' },
  { id: 'crc32', label: 'CRC-32 walk', icon: '🔁' },
  { id: 'errors', label: 'Error control', icon: '🛡️' },
  { id: 'chord', label: 'Chord DHT', icon: '💍' },
  { id: 'chash', label: 'Consistent hashing', icon: '⭕' },
  { id: 'lb', label: 'Load balancing', icon: '⚖️' },
  { id: 'hll', label: 'HyperLogLog', icon: '🔢' },
  { id: 'countmin', label: 'Count-Min Sketch', icon: '📊' },
  { id: 'majority', label: 'Majority vote', icon: '🗳️' },
  { id: 'reservoir', label: 'Reservoir sampling', icon: '🪣' },
  { id: 'bloom', label: 'Bloom filter', icon: '🌸' },
  { id: 'chandy', label: 'Chandy-Lamport snapshot', icon: '📸' },
  { id: 'phiaccrual', label: 'Failure detectors (φ)', icon: '💓' },
  { id: 'taillatency', label: 'Tail latency (p99)', icon: '📉' },
  { id: 'hdrhist', label: 'HdrHistogram (percentiles)', icon: '📊' },
  { id: 'watermark', label: 'Stream watermarks', icon: '🌊' },
  { id: 'swim', label: 'SWIM failure detection', icon: '💓' },
  { id: 'deployments', label: 'Deployment strategies', icon: '🚀' },
  { id: 'healthcheck', label: 'Liveness vs readiness', icon: '🩺' },
  { id: 'autoscale', label: 'Autoscaling (HPA)', icon: '📈' },
  { id: 'slo', label: 'SLOs & error budgets', icon: '🎯' },
  { id: 'tracing', label: 'Distributed tracing', icon: '🔭' },
  { id: 'featureflags', label: 'Feature flags', icon: '🚩' },
  { id: 'gracefulshutdown', label: 'Graceful shutdown', icon: '🔌' },
  { id: 'idempotency', label: 'Idempotency keys', icon: '🔁' },
  { id: 'loadshed', label: 'Load shedding', icon: '🚰' },
  { id: 'chaos', label: 'Chaos engineering', icon: '🐵' },
  { id: 'singleflight', label: 'Request coalescing', icon: '🤝' },
  { id: 'lamport', label: 'Lamport clocks', icon: '⏱️' },
  { id: 'hlc', label: 'Hybrid Logical Clocks', icon: '🕓' },
  { id: 'truetime', label: 'TrueTime & commit-wait', icon: '🛰️' },
  { id: 'snowflake', label: 'Snowflake IDs', icon: '❄️' },
  { id: 'vclock', label: 'Vector clocks', icon: '🕰️' },
  { id: 'causalbcast', label: 'Causal broadcast', icon: '➰' },
  { id: 'crdt', label: 'CRDTs', icon: '🧬' },
  { id: 'gossip', label: 'Gossip spread', icon: '🗣️' },
  { id: 'antientropy', label: 'Read-repair & anti-entropy', icon: '🩹' },
  { id: 'hintedhandoff', label: 'Hinted handoff', icon: '📨' },
  { id: 'paxos', label: 'Paxos consensus', icon: '🏛️' },
  { id: 'bully', label: 'Leader election', icon: '👑' },
  { id: 'fencing', label: 'Fencing tokens', icon: '🚧' },
  { id: 'pbft', label: 'PBFT (Byzantine)', icon: '😈' },
  { id: 'raft', label: 'Raft election', icon: '👑' },
  { id: 'raftlog', label: 'Raft log replication', icon: '📜' },
  { id: 'consistency', label: 'Consistency models', icon: '⚖️' },
  { id: 'cap', label: 'CAP theorem', icon: '⚖️' },
  { id: 'quorum', label: 'Quorum (R+W>N)', icon: '🗳️' },
  { id: 'replication', label: 'Replication (WAL)', icon: '🗄️' },
  { id: 'chainrep', label: 'Chain replication', icon: '⛓️' },
  { id: 'twopc', label: 'Two-phase commit', icon: '🤝' },
  { id: 'saga', label: 'Saga pattern', icon: '🔄' },
  { id: 'cpusched', label: 'CPU scheduling', icon: '⏱️' },
  { id: 'pagewalk', label: 'Page-table walk', icon: '🗺️' },
  { id: 'mesi', label: 'MESI cache coherence', icon: '🧠' },
  { id: 'tso', label: 'Memory consistency (TSO)', icon: '🧮' },
  { id: 'branchpredict', label: 'Branch prediction', icon: '🔮' },
  { id: 'cow', label: 'Copy-on-write fork', icon: '🐄' },
  { id: 'tlb', label: 'TLB (address cache)', icon: '🗂️' },
  { id: 'numa', label: 'NUMA & first-touch', icon: '🧮' },
  { id: 'epoll', label: 'epoll & C10k', icon: '📡' },
  { id: 'futex', label: 'futex (fast mutex)', icon: '🔓' },
  { id: 'iouring', label: 'io_uring (async I/O)', icon: '💍' },
  { id: 'bakery', label: 'Lamport bakery (mutex)', icon: '🎫' },
  { id: 'cfs', label: 'Linux CFS scheduler', icon: '⚖️' },
  { id: 'pipeline', label: 'Pipeline hazards', icon: '🚰' },
];

export const metaById: Record<string, SectionMeta> = Object.fromEntries(SECTION_META.map((m) => [m.id, m]));

export interface SectionGroup { label: string; icon: string; ids: string[] }

export const GROUPS: SectionGroup[] = [
  { label: 'Network basics', icon: '🌐', ids: ['network', 'switch', 'stptree', 'arp', 'csma', 'dhcp', 'nat', 'natpunch', 'ttlhop', 'traceroute', 'subnet', 'fragment', 'pmtud', 'ipcompare', 'happyeyeballs', 'nagle', 'slaac', 'icmp', 'anycast', 'multicast', 'wpa', 'dot1x', 'vlan', 'ntp'] },
  { label: 'Routing & naming', icon: '🧭', ids: ['routing', 'distvec', 'ospf', 'bgp', 'bgphijack', 'bgprr', 'mpls', 'vxlan', 'vrrp', 'ipsec', 'ecmp', 'dns', 'dnssec', 'mdns', 'encdns'] },
  { label: 'Transport & web', icon: '🚀', ids: ['tcphand', 'tfo', 'zerortt', 'congestion', 'cubic', 'bbr', 'flow', 'sack', 'arq', 'rto', 'bdp', 'queueing', 'bufferbloat', 'ecn', 'qos', 'h2flow', 'http2', 'quic', 'quicmig', 'http3', 'grpc', 'websocket', 'realtime', 'sctp', 'cdn', 'conditional', 'ratelimit', 'leakybucket', 'retry'] },
  { label: 'Cryptography', icon: '🔒', ids: ['crypto', 'classical', 'otpad', 'aesround', 'ecbpenguin', 'feistel', 'aead', 'chacha', 'poly1305', 'consttime', 'hashint', 'hashbreak', 'rsa', 'ecc', 'ecdsa', 'eddsa', 'pedersen', 'blindsig', 'vrf', 'ot', 'paillier', 'schnorr', 'dhkex', 'dhmitm', 'tlsdowngrade', 'pwhash', 'pqc', 'ntt', 'bb84', 'shamir', 'feldman', 'threshsig', 'pow', 'ratchet', 'x3dh', 'merkle', 'hashchain'] },
  { label: 'Security & web', icon: '🛡️', ids: ['certs', 'kerberos', 'revocation', 'ssh', 'identity', 'mailauth', 'webauthn', 'cookies', 'cors', 'webinject', 'smuggle', 'ssrf', 'clickjack', 'hsts', 'openredirect', 'hashflood', 'redos', 'siteisolation', 'sri', 'csp', 'attacks'] },
  { label: 'Data & encoding', icon: '🔤', ids: ['encoding', 'varint', 'linecode', 'lz77', 'lzw', 'bwt', 'mtf', 'cdc', 'dfa', 'huffman', 'golombrice', 'arith', 'crc32', 'reedsolomon', 'viterbi', 'errors'] },
  { label: 'Distributed systems', icon: '🕸️', ids: ['chash', 'chord', 'lb', 'hll', 'countmin', 'majority', 'reservoir', 'bloom', 'snowflake', 'lamport', 'chandy', 'phiaccrual', 'taillatency', 'hdrhist', 'watermark', 'swim', 'hlc', 'truetime', 'vclock', 'causalbcast', 'crdt', 'gossip', 'antientropy', 'hintedhandoff', 'paxos', 'bully', 'fencing', 'pbft', 'raft', 'raftlog', 'consistency', 'cap', 'quorum', 'replication', 'chainrep', 'twopc', 'saga'] },
  { label: 'Operations & SRE', icon: '🛠️', ids: ['deployments', 'healthcheck', 'autoscale', 'slo', 'tracing', 'featureflags', 'gracefulshutdown', 'idempotency', 'loadshed', 'chaos', 'singleflight'] },
  { label: 'Storage & databases', icon: '🗄️', ids: ['btree', 'lsm', 'pagereplace', 'mvcc', 'wal', 'skiplist', 'locking', 'joins', 'queryplan', 'rum', 'trie', 'hashtable', 'cuckoo', 'geohash', 'unionfind', 'fenwick', 'heap', 'segtree', 'avl', 'sorting', 'quickselect', 'aliasmethod', 'kmp', 'rabinkarp', 'ahocorasick', 'boyermoore', 'suffixarray', 'manacher', 'editdist', 'knapsack', 'toposort', 'astar', 'maxflow', 'mst', 'scc', 'floyd', 'bellmanford', 'newton', 'fft'] },
  { label: 'Systems & OS', icon: '🖥️', ids: ['cpusched', 'cfs', 'pipeline', 'branchpredict', 'cow', 'pagewalk', 'tlb', 'numa', 'epoll', 'futex', 'iouring', 'bakery', 'mesi', 'tso'] },
];

/** The label of the group that contains `id` (or null if ungrouped). */
export function groupOf(id: string): string | null {
  return GROUPS.find((g) => g.ids.includes(id))?.label ?? null;
}
