// Sidebar taxonomy — every section grouped into collapsible categories so the nav stays navigable. Pure data
// plus a tiny lookup, kept here (and tested) so the grouping can't silently drift out of sync with the sections
// themselves. (For the live count, run `npm run stats` — nothing here hardcodes it.)

export interface SectionMeta { id: string; label: string; icon: string }

export const SECTION_META: SectionMeta[] = [
  { id: 'network', label: 'Network', icon: '🌐' },
  { id: 'switch', label: 'L2 switch', icon: '🔌' },
  { id: 'dhcp', label: 'DHCP (DORA)', icon: '📨' },
  { id: 'nat', label: 'NAT / PAT', icon: '🔀' },
  { id: 'ttlhop', label: 'TTL & checksum', icon: '⏬' },
  { id: 'traceroute', label: 'Traceroute', icon: '🛰️' },
  { id: 'subnet', label: 'Subnetting', icon: '🧮' },
  { id: 'pmtud', label: 'Path MTU Discovery', icon: '📏' },
  { id: 'fragment', label: 'IP fragmentation', icon: '🧩' },
  { id: 'natpunch', label: 'NAT traversal', icon: '🕳️' },
  { id: 'ipcompare', label: 'IPv4 vs IPv6', icon: '⇄' },
  { id: 'happyeyeballs', label: 'Happy Eyeballs', icon: '👀' },
  { id: 'sctp', label: 'SCTP multi-homing', icon: '🔀' },
  { id: 'mptcp', label: 'Multipath TCP', icon: '🔀' },
  { id: 'nagle', label: 'Nagle & delayed ACK', icon: '🐢' },
  { id: 'sws', label: 'Silly window syndrome', icon: '🪟' },
  { id: 'icmp', label: 'ICMP messages', icon: '🚨' },
  { id: 'anycast', label: 'Anycast', icon: '📡' },
  { id: 'multicast', label: 'Multicast & IGMP', icon: '📡' },
  { id: 'wpa', label: 'WPA2 handshake', icon: '📶' },
  { id: 'dot1x', label: '802.1X / EAPOL', icon: '🔌' },
  { id: 'vlan', label: 'VLAN tagging', icon: '🏷️' },
  { id: 'ntp', label: 'NTP clock sync', icon: '🕰️' },
  { id: 'gps', label: 'How GPS finds your position', icon: '🎬' },
  { id: 'btree', label: 'B+tree index', icon: '🌲' },
  { id: 'exthash', label: 'How a hash index grows (extendible hashing)', icon: '🎬' },
  { id: 'gitobjects', label: 'How Git stores your code', icon: '🎬' },
  { id: 'pagereplace', label: 'Page replacement', icon: '📄' },
  { id: 'lsm', label: 'LSM-tree', icon: '🪵' },
  { id: 'mvcc', label: 'MVCC isolation', icon: '🔀' },
  { id: 'wal', label: 'Write-Ahead Log', icon: '📒' },
  { id: 'skiplist', label: 'Skip list', icon: '🪜' },
  { id: 'locking', label: 'Locking & deadlock', icon: '🔒' },
  { id: 'serializable', label: 'When is an interleaving safe? (conflict serializability)', icon: '🎬' },
  { id: 'joins', label: 'Join algorithms', icon: '🔗' },
  { id: 'gracejoin', label: 'How to join tables bigger than RAM (grace hash join)', icon: '🎬' },
  { id: 'queryplan', label: 'Query planner (cost)', icon: '🧠' },
  { id: 'rum', label: 'RUM amplification', icon: '⚖️' },
  { id: 'trie', label: 'Trie (prefix tree)', icon: '🌿' },
  { id: 'hamt', label: 'HAMT (persistent map)', icon: '🍂' },
  { id: 'hashtable', label: 'Hash table collisions', icon: '🗃️' },
  { id: 'cuckoo', label: 'Cuckoo hashing', icon: '🐦' },
  { id: 'robinhood', label: 'Robin Hood hashing', icon: '🏹' },
  { id: 'geohash', label: 'Geohashing', icon: '🌍' },
  { id: 'kdtree', label: 'k-d tree (nearest neighbor)', icon: '📍' },
  { id: 'unionfind', label: 'Union-Find', icon: '🔗' },
  { id: 'fenwick', label: 'Fenwick tree', icon: '🌴' },
  { id: 'sparsetable', label: 'Sparse table (RMQ)', icon: '⚡' },
  { id: 'cartesian', label: 'Cartesian tree (RMQ=LCA)', icon: '🌲' },
  { id: 'roaring', label: 'Roaring bitmaps', icon: '🧲' },
  { id: 'bitmapindex', label: 'Bitmap index', icon: '🗂️' },
  { id: 'heap', label: 'Binary heap', icon: '⛰️' },
  { id: 'pairingheap', label: 'Pairing heap (mergeable)', icon: '🫱' },
  { id: 'segtree', label: 'Segment tree', icon: '🌲' },
  { id: 'intervaltree', label: 'Interval tree', icon: '📊' },
  { id: 'avl', label: 'AVL tree', icon: '🌳' },
  { id: 'splaytree', label: 'Splay tree', icon: '🔃' },
  { id: 'treap', label: 'Treap (randomized BST)', icon: '🎲' },
  { id: 'piecetable', label: 'Piece table (text editor)', icon: '📝' },
  { id: 'rope', label: 'Rope (text editor tree)', icon: '🪢' },
  { id: 'gapbuffer', label: 'Gap buffer (Emacs)', icon: '⌨️' },
  { id: 'timsort', label: 'The sort in your standard library (Timsort)', icon: '🎬' },
  { id: 'sorting', label: 'Sorting algorithms', icon: '📊' },
  { id: 'kadane', label: 'Kadane (max subarray)', icon: '📈' },
  { id: 'lis', label: 'Longest increasing subseq', icon: '📶' },
  { id: 'quickselect', label: 'Quickselect (k-th)', icon: '🎯' },
  { id: 'medianofmedians', label: 'Median of medians', icon: '🎯' },
  { id: 'dnf', label: 'Dutch national flag', icon: '🇳🇱' },
  { id: 'shuffle', label: 'Shuffle bias (Fisher–Yates)', icon: '🔀' },
  { id: 'aliasmethod', label: 'Alias method (weighted sampling)', icon: '🎰' },
  { id: 'montecarlo', label: 'Estimating π by throwing darts (Monte Carlo)', icon: '🎬' },
  { id: 'ransac', label: 'Fitting a line through 50% outliers (RANSAC)', icon: '🎬' },
  { id: 'kmp', label: 'KMP string search', icon: '🔎' },
  { id: 'editdist', label: 'Edit distance', icon: '📝' },
  { id: 'diff', label: 'How diff works (git diff, code review)', icon: '🎬' },
  { id: 'bktree', label: 'How fuzzy search finds typos (BK-tree)', icon: '🎬' },
  { id: 'knapsack', label: '0/1 Knapsack (DP)', icon: '🎒' },
  { id: 'toposort', label: 'Topological sort', icon: '🔢' },
  { id: 'astar', label: 'A* pathfinding', icon: '🧭' },
  { id: 'dpll', label: 'How a SAT solver works (DPLL)', icon: '🎬' },
  { id: 'maxflow', label: 'Max-flow / min-cut', icon: '🌊' },
  { id: 'mst', label: 'Minimum spanning tree', icon: '🌲' },
  { id: 'scc', label: 'Strongly connected comps', icon: '🔗' },
  { id: 'twosat', label: '2-SAT (implication graph)', icon: '🔀' },
  { id: 'cycledetect', label: 'Cycle detection (tortoise & hare)', icon: '🐢' },
  { id: 'floyd', label: 'Floyd-Warshall (all-pairs)', icon: '🔲' },
  { id: 'bellmanford', label: 'Bellman-Ford & arbitrage', icon: '💱' },
  { id: 'pagerank', label: 'How Google first ranked the web (PageRank)', icon: '🎬' },
  { id: 'kmeans', label: 'How k-means finds clusters (unsupervised)', icon: '🎬' },
  { id: 'dbscan', label: 'Clustering any shape + finding outliers (DBSCAN)', icon: '🎬' },
  { id: 'gmm', label: 'Soft clustering with Gaussians (GMM / EM)', icon: '🎬' },
  { id: 'pca', label: 'How PCA compresses data (principal components)', icon: '🎬' },
  { id: 'svd', label: 'How SVD compresses an image (low rank)', icon: '🎬' },
  { id: 'perceptron', label: 'The first neural net (perceptron & XOR)', icon: '🎬' },
  { id: 'logisticregression', label: 'From a hard line to a probability (logistic regression)', icon: '🎬' },
  { id: 'svm', label: 'The widest street between classes (SVM)', icon: '🎬' },
  { id: 'decisiontree', label: 'How a decision tree splits data (Gini)', icon: '🎬' },
  { id: 'randomforest', label: 'Why a forest beats one tree (bagging)', icon: '🎬' },
  { id: 'gradientboosting', label: 'Learning from residuals (gradient boosting)', icon: '🎬' },
  { id: 'newton', label: "Newton's method", icon: '➗' },
  { id: 'conjgrad', label: 'How conjugate gradient beats zigzag descent', icon: '🎬' },
  { id: 'simplex', label: 'How linear programming finds the best plan (simplex)', icon: '🎬' },
  { id: 'fft', label: 'Fast Fourier Transform', icon: '〰️' },
  { id: 'haarwavelet', label: 'Multi-resolution & compression (Haar wavelet)', icon: '🎬' },
  { id: 'goertzel', label: 'How a phone hears touch-tones (Goertzel)', icon: '🎬' },
  { id: 'pitch', label: 'How a tuner hears pitch (autocorrelation)', icon: '🎬' },
  { id: 'karplus', label: 'How to synthesize a plucked string (Karplus-Strong)', icon: '🎬' },
  { id: 'convreverb', label: 'How reverb puts you in a cathedral (convolution)', icon: '🎬' },
  { id: 'fastinvsqrt', label: 'Fast inverse square root', icon: '⚡' },
  { id: 'kahan', label: 'Kahan summation', icon: '➕' },
  { id: 'cordic', label: 'How calculators do trig (CORDIC)', icon: '🎬' },
  { id: 'karatsuba', label: 'Karatsuba multiplication', icon: '✖️' },
  { id: 'simanneal', label: 'Simulated annealing', icon: '🌡️' },
  { id: 'alphabeta', label: 'How game AI searches (alpha-beta)', icon: '🎬' },
  { id: 'backprop', label: 'How a neural network learns (backprop)', icon: '🎬' },
  { id: 'word2vec', label: 'How word embeddings work (word2vec)', icon: '🎬' },
  { id: 'vectorsearch', label: 'How vector search finds nearest embeddings (HNSW)', icon: '🎬' },
  { id: 'attention', label: 'How attention works (transformers)', icon: '🎬' },
  { id: 'bresenham', label: 'Bresenham line drawing', icon: '📐' },
  { id: 'bezier', label: 'How curves are drawn (Bézier & de Casteljau)', icon: '🎬' },
  { id: 'raytracing', label: 'How ray tracing renders an image', icon: '🎬' },
  { id: 'rasterize', label: 'How a GPU rasterizes a triangle', icon: '🎬' },
  { id: 'perspective', label: 'How 3D becomes 2D (perspective & the texture warp)', icon: '🎬' },
  { id: 'msaa', label: 'How GPUs smooth jagged edges (MSAA)', icon: '🎬' },
  { id: 'verlet', label: 'How game physics simulates rope & cloth', icon: '🎬' },
  { id: 'barneshut', label: 'How galaxies simulate gravity fast (Barnes-Hut)', icon: '🎬' },
  { id: 'doublependulum', label: 'Why the weather is unpredictable (chaos)', icon: '🎬' },
  { id: 'orbit', label: 'Why simulated orbits drift (symplectic integrators)', icon: '🎬' },
  { id: 'raymarch', label: 'How ray-marching renders with math (SDF)', icon: '🎬' },
  { id: 'quaternion', label: 'How 3D rotation really works (quaternions & slerp)', icon: '🎬' },
  { id: 'convexhull', label: 'Convex hull', icon: '🔷' },
  { id: 'sat', label: 'How games detect collisions (SAT)', icon: '🎬' },
  { id: 'spatialhash', label: 'How games skip the n² collision test (spatial hash)', icon: '🎬' },
  { id: 'marchsquares', label: 'Marching squares', icon: '🗺️' },
  { id: 'voronoi', label: 'Voronoi diagram', icon: '🔺' },
  { id: 'delaunay', label: 'Delaunay triangulation', icon: '📐' },
  { id: 'wfc', label: 'Generating maps by constraints (wave function collapse)', icon: '🎬' },
  { id: 'perlin', label: 'Perlin noise', icon: '🏔️' },
  { id: 'poisson', label: 'Poisson-disk sampling', icon: '⚪' },
  { id: 'rabinkarp', label: 'Rabin-Karp', icon: '🎞️' },
  { id: 'ahocorasick', label: 'Aho-Corasick', icon: '🔱' },
  { id: 'boyermoore', label: 'Boyer-Moore search', icon: '🏃' },
  { id: 'suffixarray', label: 'Suffix array', icon: '🔡' },
  { id: 'manacher', label: 'Manacher (palindromes)', icon: '🔁' },
  { id: 'zalgo', label: 'Z-algorithm', icon: '📏' },
  { id: 'arp', label: 'ARP resolution', icon: '📇' },
  { id: 'stptree', label: 'Spanning Tree', icon: '🌳' },
  { id: 'slaac', label: 'IPv6 SLAAC', icon: '🆔' },
  { id: 'csma', label: 'WiFi CSMA/CA', icon: '📶' },
  { id: 'routing', label: 'Routing & paths', icon: '🧭' },
  { id: 'lpm', label: 'How a router forwards (longest-prefix)', icon: '🎬' },
  { id: 'distvec', label: 'Distance-vector', icon: '📐' },
  { id: 'ospf', label: 'OSPF link-state', icon: '🗺️' },
  { id: 'bgp', label: 'BGP best-path', icon: '🥇' },
  { id: 'bgphijack', label: 'BGP hijack', icon: '🏴‍☠️' },
  { id: 'bgprr', label: 'BGP route reflectors', icon: '🪞' },
  { id: 'routeflap', label: 'BGP route flap damping', icon: '📉' },
  { id: 'mpls', label: 'MPLS switching', icon: '🏷️' },
  { id: 'segrouting', label: 'Segment routing', icon: '🧵' },
  { id: 'vxlan', label: 'VXLAN overlay', icon: '🪆' },
  { id: 'vrrp', label: 'VRRP redundancy', icon: '🛟' },
  { id: 'ipsec', label: 'IPsec ESP (VPN)', icon: '🔐' },
  { id: 'ecmp', label: 'ECMP load spreading', icon: '🔱' },
  { id: 'dnssec', label: 'DNSSEC chain', icon: '🔏' },
  { id: 'kaminsky', label: 'DNS cache poisoning', icon: '☠️' },
  { id: 'dns', label: 'DNS journey', icon: '🔎' },
  { id: 'mdns', label: 'mDNS & DNS-SD', icon: '🖨️' },
  { id: 'encdns', label: 'Encrypted DNS', icon: '🕵️' },
  { id: 'tcphand', label: 'TCP handshake', icon: '🤝' },
  { id: 'timewait', label: 'TIME_WAIT & ports', icon: '⏱️' },
  { id: 'tfo', label: 'TCP Fast Open', icon: '⚡' },
  { id: 'zerortt', label: '0-RTT resumption & replay', icon: '⏩' },
  { id: 'congestion', label: 'TCP congestion', icon: '📈' },
  { id: 'cubic', label: 'TCP CUBIC', icon: '📈' },
  { id: 'bbr', label: 'TCP BBR', icon: '🌊' },
  { id: 'flow', label: 'Flow control', icon: '🪟' },
  { id: 'h2flow', label: 'H2/QUIC flow control', icon: '🚰' },
  { id: 'sack', label: 'TCP SACK', icon: '🎯' },
  { id: 'arq', label: 'ARQ (GBN vs SR)', icon: '🔁' },
  { id: 'rto', label: 'RTO & Karn', icon: '⏱️' },
  { id: 'bdp', label: 'Bandwidth-Delay Product', icon: '🪣' },
  { id: 'queueing', label: 'M/M/1 queueing', icon: '📉' },
  { id: 'bufferbloat', label: 'Bufferbloat', icon: '🚰' },
  { id: 'ecn', label: 'ECN marking', icon: '🚩' },
  { id: 'qos', label: 'QoS scheduling', icon: '🚦' },
  { id: 'http2', label: 'HTTP/2 multiplexing', icon: '🧵' },
  { id: 'quic', label: 'QUIC vs TCP', icon: '🚀' },
  { id: 'quicmig', label: 'QUIC connection migration', icon: '📶' },
  { id: 'http3', label: 'HTTP/3 & QPACK', icon: '🌐' },
  { id: 'websocket', label: 'WebSocket', icon: '🔌' },
  { id: 'realtime', label: 'Realtime: SSE vs WS', icon: '📡' },
  { id: 'grpc', label: 'gRPC & protobuf', icon: '📡' },
  { id: 'cdn', label: 'CDN & caching', icon: '⚡' },
  { id: 'conditional', label: 'Conditional & range', icon: '🔖' },
  { id: 'ratelimit', label: 'Rate limiting', icon: '🪣' },
  { id: 'leakybucket', label: 'Leaky bucket', icon: '🚿' },
  { id: 'gcra', label: 'GCRA (virtual scheduling)', icon: '⏱️' },
  { id: 'retry', label: 'Retry & circuit breaker', icon: '🔁' },
  { id: 'crypto', label: 'Cryptography', icon: '🔒' },
  { id: 'classical', label: 'Classical ciphers', icon: '🏛️' },
  { id: 'otpad', label: 'One-time pad', icon: '🎲' },
  { id: 'ecbpenguin', label: 'ECB penguin / modes', icon: '🐧' },
  { id: 'aesround', label: 'AES internals', icon: '🧊' },
  { id: 'feistel', label: 'Feistel / DES', icon: '🔁' },
  { id: 'aead', label: 'CTR & AEAD', icon: '🔐' },
  { id: 'montgomery', label: 'Montgomery multiplication', icon: '✖️' },
  { id: 'rsa', label: 'RSA', icon: '🗝️' },
  { id: 'crt', label: 'One number, many remainders (Chinese Remainder Theorem)', icon: '🎬' },
  { id: 'pubkey', label: 'How public-key crypto works', icon: '🎬' },
  { id: 'ecc', label: 'Elliptic curves', icon: '➰' },
  { id: 'montladder', label: 'Exponentiation that doesn’t leak (Montgomery ladder)', icon: '🎬' },
  { id: 'ecdsa', label: 'ECDSA & nonce reuse', icon: '✍️' },
  { id: 'eddsa', label: 'EdDSA (Ed25519)', icon: '🖋️' },
  { id: 'pedersen', label: 'Pedersen commitment', icon: '✉️' },
  { id: 'blindsig', label: 'Blind signatures', icon: '🙈' },
  { id: 'vrf', label: 'Verifiable random function', icon: '🎲' },
  { id: 'ot', label: 'Oblivious transfer', icon: '🤝' },
  { id: 'garbled', label: 'Compute on secrets (Yao garbled circuits)', icon: '🎬' },
  { id: 'oram', label: 'Hiding what you access (Path ORAM)', icon: '🎬' },
  { id: 'pir', label: 'Fetching a record privately (PIR)', icon: '🎬' },
  { id: 'paillier', label: 'Homomorphic (Paillier)', icon: '➕' },
  { id: 'elgamal', label: 'ElGamal encryption', icon: '🔐' },
  { id: 'schnorr', label: 'Zero-knowledge (Schnorr)', icon: '🕵️‍♂️' },
  { id: 'sumcheck', label: 'Proving a huge sum cheaply (sumcheck)', icon: '🎬' },
  { id: 'vdf', label: 'A clock you can’t rush (verifiable delay function)', icon: '🎬' },
  { id: 'chacha', label: 'ChaCha20', icon: '🌀' },
  { id: 'poly1305', label: 'Poly1305 MAC', icon: '🏷️' },
  { id: 'consttime', label: 'Timing attacks', icon: '⏱️' },
  { id: 'hashint', label: 'SHA-256 internals', icon: '🧮' },
  { id: 'hashbreak', label: 'Broken hashes', icon: '💥' },
  { id: 'lenext', label: 'Length-extension attack', icon: '➕' },
  { id: 'hmac', label: 'HMAC', icon: '🔏' },
  { id: 'paddingoracle', label: 'Padding oracle attack', icon: '🔓' },
  { id: 'dhkex', label: 'Diffie–Hellman', icon: '🤝' },
  { id: 'dhmitm', label: 'DH man-in-the-middle', icon: '🕴️' },
  { id: 'tlsdowngrade', label: 'TLS downgrade', icon: '⬇️' },
  { id: 'tlsflow', label: 'How HTTPS secures a connection', icon: '🎬' },
  { id: 'pwhash', label: 'Password hashing', icon: '🔑' },
  { id: 'pqc', label: 'Post-quantum (LWE)', icon: '🔮' },
  { id: 'lll', label: 'How LLL reduces a lattice (& breaks crypto)', icon: '🎬' },
  { id: 'ntt', label: 'NTT (Kyber engine)', icon: '🦋' },
  { id: 'bb84', label: 'Quantum key (BB84)', icon: '⚛️' },
  { id: 'certs', label: 'Certificates (PKI)', icon: '📜' },
  { id: 'kerberos', label: 'Kerberos', icon: '🎟️' },
  { id: 'revocation', label: 'Revocation & CT', icon: '🚫' },
  { id: 'ssh', label: 'SSH transport', icon: '🖧' },
  { id: 'identity', label: 'Identity & Auth', icon: '🪪' },
  { id: 'jwt', label: 'JWT & alg=none', icon: '🎫' },
  { id: 'cors', label: 'CORS / Same-Origin', icon: '🚧' },
  { id: 'mailauth', label: 'Email auth (SPF/DKIM)', icon: '📧' },
  { id: 'totp', label: 'How your 2FA code works (TOTP)', icon: '🎬' },
  { id: 'webauthn', label: 'Passkeys (WebAuthn)', icon: '🔑' },
  { id: 'cookies', label: 'Cookies & sessions', icon: '🍪' },
  { id: 'csp', label: 'Content-Security-Policy', icon: '🧱' },
  { id: 'webinject', label: 'Injection (SQLi/XSS)', icon: '💉' },
  { id: 'bufferoverflow', label: 'How a buffer overflow hijacks a program', icon: '🎬' },
  { id: 'nxbit', label: 'How NX / DEP stops your shellcode', icon: '🎬' },
  { id: 'rop', label: 'How ROP bypasses NX', icon: '🎬' },
  { id: 'aslr', label: 'How ASLR randomizes the addresses', icon: '🎬' },
  { id: 'stackcanary', label: 'How a stack canary catches the overflow', icon: '🎬' },
  { id: 'cfi', label: 'How CFI and shadow stacks kill ROP', icon: '🎬' },
  { id: 'smuggle', label: 'Request smuggling', icon: '📦' },
  { id: 'ssrf', label: 'SSRF', icon: '🎯' },
  { id: 'xxe', label: 'XXE (XML entities)', icon: '📄' },
  { id: 'dnsrebind', label: 'DNS rebinding', icon: '🔀' },
  { id: 'arpspoof', label: 'ARP spoofing (MITM)', icon: '🎭' },
  { id: 'clickjack', label: 'Clickjacking', icon: '👆' },
  { id: 'hsts', label: 'HSTS & SSL stripping', icon: '🔒' },
  { id: 'openredirect', label: 'Open redirect', icon: '↪️' },
  { id: 'protopollute', label: 'Prototype pollution', icon: '🧬' },
  { id: 'hashflood', label: 'Hash flooding (DoS)', icon: '🌊' },
  { id: 'redos', label: 'ReDoS (regex DoS)', icon: '💣' },
  { id: 'subdomain', label: 'Subdomain takeover', icon: '🏴' },
  { id: 'siteisolation', label: 'Site isolation', icon: '🧱' },
  { id: 'sri', label: 'Subresource Integrity', icon: '🔗' },
  { id: 'attacks', label: 'Attacks', icon: '⚔️' },
  { id: 'shamir', label: 'Secret sharing', icon: '🧩' },
  { id: 'envelope', label: 'Envelope encryption (KMS)', icon: '✉️' },
  { id: 'feldman', label: 'Verifiable secret sharing', icon: '🧩' },
  { id: 'threshsig', label: 'Threshold signatures', icon: '✍️' },
  { id: 'pow', label: 'Proof of Work', icon: '⛏️' },
  { id: 'ratchet', label: 'Double Ratchet', icon: '🔗' },
  { id: 'x3dh', label: 'X3DH key agreement', icon: '🤝' },
  { id: 'hashchain', label: 'Hash chain', icon: '⛓️' },
  { id: 'merkle', label: 'Merkle tree', icon: '🌳' },
  { id: 'accumulator', label: 'A whole set in one number (RSA accumulator)', icon: '🎬' },
  { id: 'lamportsig', label: 'Lamport signatures', icon: '🔏' },
  { id: 'encoding', label: 'Encoding', icon: '🔤' },
  { id: 'float', label: 'How a computer stores a fraction (IEEE-754)', icon: '🎬' },
  { id: 'graycode', label: 'Why encoders use Gray code (one bit at a time)', icon: '🎬' },
  { id: 'varint', label: 'Varint & zigzag', icon: '📏' },
  { id: 'base58', label: 'Base58 & Base58Check', icon: '🅱️' },
  { id: 'linecode', label: 'Line coding', icon: '〰️' },
  { id: 'lz77', label: 'LZ77 compression', icon: '🪟' },
  { id: 'lzw', label: 'LZW compression', icon: '📖' },
  { id: 'bwt', label: 'Burrows-Wheeler', icon: '🔄' },
  { id: 'debruijn', label: 'How genomes are assembled (de Bruijn graphs)', icon: '🎬' },
  { id: 'mtf', label: 'Move-to-front', icon: '↩️' },
  { id: 'cdc', label: 'Content-defined chunking', icon: '✂️' },
  { id: 'rsync', label: 'rsync (delta sync)', icon: '🔃' },
  { id: 'dfa', label: 'Finite automata (DFA)', icon: '🔄' },
  { id: 'huffman', label: 'Huffman coding', icon: '🗜️' },
  { id: 'jpeg', label: 'How JPEG compresses an image', icon: '🎬' },
  { id: 'seamcarve', label: 'How content-aware resize works (seam carving)', icon: '🎬' },
  { id: 'interframe', label: 'How video inter-frame compression works', icon: '🎬' },
  { id: 'mp3', label: 'How MP3 shrinks audio (psychoacoustic masking)', icon: '🎬' },
  { id: 'dithering', label: 'How dithering fakes gray with black & white', icon: '🎬' },
  { id: 'gamma', label: 'Why 128 isn’t half-bright (gamma)', icon: '🎬' },
  { id: 'colorspace', label: 'Why RGB blends look muddy (OKLab)', icon: '🎬' },
  { id: 'hdr', label: 'How HDR fits the sun on your screen (tone-mapping)', icon: '🎬' },
  { id: 'golombrice', label: 'Golomb-Rice coding', icon: '📐' },
  { id: 'eliascode', label: 'Elias γ/δ coding', icon: '🔢' },
  { id: 'gorilla', label: 'Gorilla (time-series)', icon: '🦍' },
  { id: 'cobs', label: 'COBS (byte stuffing)', icon: '📦' },
  { id: 'arith', label: 'Arithmetic coding', icon: '🎯' },
  { id: 'viterbi', label: 'Viterbi / convolutional', icon: '🧬' },
  { id: 'hamming', label: 'Hamming(7,4) code', icon: '🩹' },
  { id: 'reedsolomon', label: 'Reed-Solomon', icon: '💿' },
  { id: 'crc32', label: 'CRC-32 walk', icon: '🔁' },
  { id: 'errors', label: 'Error control', icon: '🛡️' },
  { id: 'barcode', label: 'How a barcode works (UPC check digit)', icon: '🎬' },
  { id: 'chord', label: 'Chord DHT', icon: '💍' },
  { id: 'kademlia', label: 'Kademlia DHT (XOR)', icon: '🔀' },
  { id: 'chash', label: 'Consistent hashing', icon: '⭕' },
  { id: 'jumphash', label: 'Jump consistent hash', icon: '🦘' },
  { id: 'rendezvous', label: 'Rendezvous hashing (HRW)', icon: '🎯' },
  { id: 'lb', label: 'Load balancing', icon: '⚖️' },
  { id: 'hll', label: 'HyperLogLog', icon: '🔢' },
  { id: 'countmin', label: 'Count-Min Sketch', icon: '📊' },
  { id: 'diffpriv', label: 'Publishing data without leaking you (differential privacy)', icon: '🎬' },
  { id: 'minhash', label: 'MinHash (set similarity)', icon: '🧬' },
  { id: 'majority', label: 'Majority vote', icon: '🗳️' },
  { id: 'reservoir', label: 'Reservoir sampling', icon: '🪣' },
  { id: 'bloom', label: 'Bloom filter', icon: '🌸' },
  { id: 'chandy', label: 'Chandy-Lamport snapshot', icon: '📸' },
  { id: 'phiaccrual', label: 'Failure detectors (φ)', icon: '💓' },
  { id: 'taillatency', label: 'Tail latency (p99)', icon: '📉' },
  { id: 'hdrhist', label: 'HdrHistogram (percentiles)', icon: '📊' },
  { id: 'ddsketch', label: 'DDSketch (quantiles)', icon: '📶' },
  { id: 'watermark', label: 'Stream watermarks', icon: '🌊' },
  { id: 'swim', label: 'SWIM failure detection', icon: '💓' },
  { id: 'deployments', label: 'Deployment strategies', icon: '🚀' },
  { id: 'healthcheck', label: 'Liveness vs readiness', icon: '🩺' },
  { id: 'autoscale', label: 'Autoscaling (HPA)', icon: '📈' },
  { id: 'usl', label: 'Universal Scalability Law', icon: '📉' },
  { id: 'pid', label: 'PID controller', icon: '🎛️' },
  { id: 'kalman', label: 'How a Kalman filter tracks', icon: '🎬' },
  { id: 'slo', label: 'SLOs & error budgets', icon: '🎯' },
  { id: 'tracing', label: 'Distributed tracing', icon: '🔭' },
  { id: 'featureflags', label: 'Feature flags', icon: '🚩' },
  { id: 'gracefulshutdown', label: 'Graceful shutdown', icon: '🔌' },
  { id: 'idempotency', label: 'Idempotency keys', icon: '🔁' },
  { id: 'loadshed', label: 'Load shedding', icon: '🚰' },
  { id: 'bulkhead', label: 'Bulkhead isolation', icon: '🚢' },
  { id: 'chaos', label: 'Chaos engineering', icon: '🐵' },
  { id: 'singleflight', label: 'Request coalescing', icon: '🤝' },
  { id: 'lamport', label: 'Lamport clocks', icon: '⏱️' },
  { id: 'hlc', label: 'Hybrid Logical Clocks', icon: '🕓' },
  { id: 'truetime', label: 'TrueTime & commit-wait', icon: '🛰️' },
  { id: 'snowflake', label: 'Snowflake IDs', icon: '❄️' },
  { id: 'vclock', label: 'Vector clocks', icon: '🕰️' },
  { id: 'causalbcast', label: 'Causal broadcast', icon: '➰' },
  { id: 'crdt', label: 'CRDTs', icon: '🧬' },
  { id: 'optransform', label: 'Operational transform', icon: '✍️' },
  { id: 'gossip', label: 'Gossip spread', icon: '🗣️' },
  { id: 'antientropy', label: 'Read-repair & anti-entropy', icon: '🩹' },
  { id: 'readrepair', label: 'Read repair (fix-on-read)', icon: '🔧' },
  { id: 'hintedhandoff', label: 'Hinted handoff', icon: '📨' },
  { id: 'paxos', label: 'Paxos consensus', icon: '🏛️' },
  { id: 'bully', label: 'Leader election', icon: '👑' },
  { id: 'fencing', label: 'Fencing tokens', icon: '🚧' },
  { id: 'leases', label: 'Leases & clock skew', icon: '⏳' },
  { id: 'pbft', label: 'PBFT (Byzantine)', icon: '😈' },
  { id: 'raft', label: 'Raft election', icon: '👑' },
  { id: 'raftlog', label: 'Raft log replication', icon: '📜' },
  { id: 'consistency', label: 'Consistency models', icon: '⚖️' },
  { id: 'cap', label: 'CAP theorem', icon: '⚖️' },
  { id: 'quorum', label: 'Quorum (R+W>N)', icon: '🗳️' },
  { id: 'replication', label: 'Replication (WAL)', icon: '🗄️' },
  { id: 'chainrep', label: 'Chain replication', icon: '⛓️' },
  { id: 'twopc', label: 'Two-phase commit', icon: '🤝' },
  { id: 'threepc', label: 'Three-phase commit', icon: '🔀' },
  { id: 'saga', label: 'Saga pattern', icon: '🔄' },
  { id: 'cpusched', label: 'CPU scheduling', icon: '⏱️' },
  { id: 'pagewalk', label: 'Page-table walk', icon: '🗺️' },
  { id: 'pagefault', label: 'How a page fault brings in memory', icon: '🎬' },
  { id: 'inode', label: 'inode & indirect blocks', icon: '🗃️' },
  { id: 'mesi', label: 'MESI cache coherence', icon: '🧠' },
  { id: 'falseshare', label: 'False sharing', icon: '🔀' },
  { id: 'tso', label: 'Memory consistency (TSO)', icon: '🧮' },
  { id: 'branchpredict', label: 'Branch prediction', icon: '🔮' },
  { id: 'strideprefetch', label: 'How the CPU prefetches memory (stride prefetcher)', icon: '🎬' },
  { id: 'branchless', label: 'Code with no branches (branchless / cmov)', icon: '🎬' },
  { id: 'oooexec', label: 'Out-of-order execution', icon: '🔀' },
  { id: 'spectre', label: 'Spectre (speculation)', icon: '👻' },
  { id: 'meltdown', label: 'How Meltdown reads kernel memory (transient execution)', icon: '🎬' },
  { id: 'rowhammer', label: 'How Rowhammer flips bits in DRAM (fault injection)', icon: '🎬' },
  { id: 'killchain', label: 'The kill chain & defense-in-depth (attacker’s lens)', icon: '🎬' },
  { id: 'cow', label: 'Copy-on-write fork', icon: '🐄' },
  { id: 'tlb', label: 'TLB (address cache)', icon: '🗂️' },
  { id: 'nestedpaging', label: 'How a VM translates memory (nested paging)', icon: '🎬' },
  { id: 'numa', label: 'NUMA & first-touch', icon: '🧮' },
  { id: 'buddyalloc', label: 'Buddy allocator', icon: '🧱' },
  { id: 'gc', label: 'How garbage collection works', icon: '🎬' },
  { id: 'cheney', label: 'How a copying collector compacts the heap (Cheney)', icon: '🎬' },
  { id: 'refcount', label: 'How reference counting frees memory', icon: '🎬' },
  { id: 'ownership', label: 'How Rust ownership prevents memory bugs', icon: '🎬' },
  { id: 'timingwheel', label: 'Timing wheel', icon: '🎡' },
  { id: 'epoll', label: 'epoll & C10k', icon: '📡' },
  { id: 'futex', label: 'futex (fast mutex)', icon: '🔓' },
  { id: 'syscall', label: 'How a syscall enters the kernel', icon: '🎬' },
  { id: 'container', label: 'How a container isolates a process', icon: '🎬' },
  { id: 'breakpoint', label: 'How a debugger breakpoint works', icon: '🎬' },
  { id: 'rcu', label: 'RCU (read-copy-update)', icon: '📖' },
  { id: 'aba', label: 'ABA problem (lock-free)', icon: '🔁' },
  { id: 'seqlock', label: 'seqlock (torn reads)', icon: '🔢' },
  { id: 'iouring', label: 'io_uring (async I/O)', icon: '💍' },
  { id: 'bakery', label: 'Lamport bakery (mutex)', icon: '🎫' },
  { id: 'cfs', label: 'Linux CFS scheduler', icon: '⚖️' },
  { id: 'eevdf', label: 'How Linux schedules now (EEVDF)', icon: '🎬' },
  { id: 'priorityinv', label: 'Priority inversion', icon: '🔺' },
  { id: 'pipeline', label: 'Pipeline hazards', icon: '🚰' },
  { id: 'cpucycle', label: 'How a CPU runs an instruction', icon: '🎬' },
  { id: 'shuntingyard', label: 'How a calculator parses math (shunting-yard)', icon: '🎬' },
  { id: 'compiler', label: 'How code becomes machine code', icon: '🎬' },
  { id: 'regalloc', label: 'How variables get registers (graph coloring)', icon: '🎬' },
  { id: 'hindley', label: 'How types are inferred with none written (Hindley-Milner)', icon: '🎬' },
  { id: 'bytecode', label: 'How a bytecode VM runs code', icon: '🎬' },
  { id: 'wasm', label: 'How WebAssembly sandboxes untrusted code', icon: '🎬' },
  { id: 'jit', label: 'How a JIT makes code fast', icon: '🎬' },
  { id: 'transistor', label: 'Transistors → logic gates', icon: '🔀' },
  { id: 'cpucache', label: 'CPU cache (sets & ways)', icon: '⚡' },
  { id: 'dram', label: 'How RAM works (DRAM)', icon: '🧠' },
  { id: 'memorystory', label: 'Memory, up close (guided tour)', icon: '🎬' },
  { id: 'adder', label: 'Binary adder (gates→math)', icon: '➕' },
  { id: 'latch', label: 'Flip-flop (how bits are stored)', icon: '💾' },
  { id: 'alu', label: 'ALU (the compute core)', icon: '🧮' },
  { id: 'wallace', label: 'How hardware multiplies fast (Wallace tree)', icon: '🎬' },
  { id: 'membus', label: 'Address decoding & buses', icon: '🚌' },
  { id: 'io', label: 'Polling · interrupts · DMA', icon: '🔔' },
  { id: 'keystroke', label: 'How a keystroke reaches the screen', icon: '🎬' },
  { id: 'ssd', label: 'How an SSD works (flash/FTL)', icon: '💽' },
  { id: 'flashcell', label: 'How flash stores a bit (floating gate)', icon: '🎬' },
  { id: 'gpu', label: 'GPU / SIMT execution', icon: '🎮' },
  { id: 'systolic', label: 'How a TPU multiplies matrices (systolic array)', icon: '🎬' },
];

export const metaById: Record<string, SectionMeta> = Object.fromEntries(SECTION_META.map((m) => [m.id, m]));

export interface SectionGroup { label: string; icon: string; ids: string[] }

export const GROUPS: SectionGroup[] = [
  { label: 'Network basics', icon: '🌐', ids: ['network', 'switch', 'stptree', 'arp', 'csma', 'dhcp', 'nat', 'natpunch', 'ttlhop', 'traceroute', 'subnet', 'fragment', 'pmtud', 'ipcompare', 'happyeyeballs', 'nagle', 'slaac', 'icmp', 'anycast', 'multicast', 'wpa', 'dot1x', 'vlan', 'ntp', 'gps'] },
  { label: 'Routing & naming', icon: '🧭', ids: ['routing', 'lpm', 'distvec', 'ospf', 'bgp', 'bgphijack', 'bgprr', 'routeflap', 'mpls', 'segrouting', 'vxlan', 'vrrp', 'ipsec', 'ecmp', 'dns', 'dnssec', 'kaminsky', 'mdns', 'encdns'] },
  { label: 'Transport & web', icon: '🚀', ids: ['tcphand', 'timewait', 'tfo', 'zerortt', 'congestion', 'cubic', 'bbr', 'flow', 'sws', 'sack', 'arq', 'rto', 'bdp', 'queueing', 'bufferbloat', 'ecn', 'qos', 'h2flow', 'http2', 'quic', 'quicmig', 'http3', 'grpc', 'websocket', 'realtime', 'sctp', 'mptcp', 'cdn', 'conditional', 'ratelimit', 'leakybucket', 'gcra', 'retry'] },
  { label: 'Cryptography', icon: '🔒', ids: ['crypto', 'classical', 'otpad', 'aesround', 'ecbpenguin', 'feistel', 'aead', 'chacha', 'poly1305', 'consttime', 'hashint', 'hashbreak', 'lenext', 'hmac', 'paddingoracle', 'montgomery', 'pubkey', 'rsa', 'crt', 'ecc', 'montladder', 'ecdsa', 'eddsa', 'pedersen', 'blindsig', 'vrf', 'ot', 'garbled', 'oram', 'pir', 'paillier', 'elgamal', 'schnorr', 'sumcheck', 'vdf', 'dhkex', 'dhmitm', 'tlsdowngrade', 'tlsflow', 'pwhash', 'pqc', 'lll', 'ntt', 'bb84', 'shamir', 'envelope', 'feldman', 'threshsig', 'pow', 'ratchet', 'x3dh', 'merkle', 'accumulator', 'lamportsig', 'hashchain'] },
  { label: 'Security & web', icon: '🛡️', ids: ['certs', 'kerberos', 'revocation', 'ssh', 'identity', 'jwt', 'mailauth', 'totp', 'webauthn', 'cookies', 'cors', 'webinject', 'bufferoverflow', 'nxbit', 'rop', 'aslr', 'stackcanary', 'cfi', 'smuggle', 'ssrf', 'xxe', 'dnsrebind', 'arpspoof', 'clickjack', 'hsts', 'openredirect', 'protopollute', 'hashflood', 'redos', 'subdomain', 'siteisolation', 'sri', 'csp', 'attacks'] },
  { label: 'Data & encoding', icon: '🔤', ids: ['encoding', 'float', 'graycode', 'varint', 'base58', 'linecode', 'lz77', 'lzw', 'bwt', 'debruijn', 'mtf', 'cdc', 'rsync', 'dfa', 'huffman', 'jpeg', 'seamcarve', 'interframe', 'mp3', 'dithering', 'gamma', 'colorspace', 'hdr', 'golombrice', 'eliascode', 'gorilla', 'cobs', 'arith', 'crc32', 'hamming', 'reedsolomon', 'viterbi', 'errors', 'barcode'] },
  { label: 'Distributed systems', icon: '🕸️', ids: ['chash', 'jumphash', 'rendezvous', 'chord', 'kademlia', 'lb', 'hll', 'countmin', 'diffpriv', 'minhash', 'majority', 'reservoir', 'bloom', 'snowflake', 'lamport', 'chandy', 'phiaccrual', 'taillatency', 'hdrhist', 'ddsketch', 'watermark', 'swim', 'hlc', 'truetime', 'vclock', 'causalbcast', 'crdt', 'optransform', 'gossip', 'antientropy', 'readrepair', 'hintedhandoff', 'paxos', 'bully', 'fencing', 'leases', 'pbft', 'raft', 'raftlog', 'consistency', 'cap', 'quorum', 'replication', 'chainrep', 'twopc', 'threepc', 'saga'] },
  { label: 'Operations & SRE', icon: '🛠️', ids: ['deployments', 'healthcheck', 'autoscale', 'usl', 'pid', 'kalman', 'slo', 'tracing', 'featureflags', 'gracefulshutdown', 'idempotency', 'loadshed', 'bulkhead', 'chaos', 'singleflight'] },
  { label: 'Storage & databases', icon: '🗄️', ids: ['btree', 'exthash', 'gitobjects', 'lsm', 'pagereplace', 'mvcc', 'wal', 'skiplist', 'locking', 'serializable', 'joins', 'gracejoin', 'queryplan', 'rum', 'trie', 'hamt', 'hashtable', 'cuckoo', 'robinhood', 'geohash', 'kdtree', 'unionfind', 'fenwick', 'sparsetable', 'cartesian', 'roaring', 'bitmapindex', 'heap', 'pairingheap', 'segtree', 'intervaltree', 'avl', 'splaytree', 'treap', 'piecetable', 'rope', 'gapbuffer', 'timsort', 'sorting', 'kadane', 'lis', 'quickselect', 'medianofmedians', 'dnf', 'shuffle', 'aliasmethod', 'montecarlo', 'ransac', 'kmp', 'rabinkarp', 'ahocorasick', 'boyermoore', 'suffixarray', 'manacher', 'zalgo', 'editdist', 'diff', 'bktree', 'knapsack', 'toposort', 'astar', 'dpll', 'maxflow', 'mst', 'scc', 'twosat', 'floyd', 'cycledetect', 'bellmanford', 'pagerank', 'kmeans', 'dbscan', 'gmm', 'pca', 'svd', 'perceptron', 'logisticregression', 'svm', 'decisiontree', 'randomforest', 'gradientboosting', 'newton', 'conjgrad', 'simplex', 'fft', 'haarwavelet', 'goertzel', 'pitch', 'karplus', 'convreverb', 'fastinvsqrt', 'kahan', 'cordic', 'karatsuba', 'simanneal', 'alphabeta', 'backprop', 'word2vec', 'vectorsearch', 'attention', 'bresenham', 'bezier', 'raytracing', 'rasterize', 'perspective', 'msaa', 'verlet', 'barneshut', 'doublependulum', 'orbit', 'raymarch', 'quaternion', 'convexhull', 'sat', 'spatialhash', 'marchsquares', 'voronoi', 'delaunay', 'wfc', 'perlin', 'poisson'] },
  { label: 'Systems & OS', icon: '🖥️', ids: ['cpusched', 'cfs', 'eevdf', 'priorityinv', 'cpucycle', 'shuntingyard', 'compiler', 'regalloc', 'hindley', 'bytecode', 'wasm', 'jit', 'pipeline', 'branchpredict', 'strideprefetch', 'branchless', 'oooexec', 'spectre', 'meltdown', 'rowhammer', 'killchain', 'cow', 'pagewalk', 'pagefault', 'inode', 'tlb', 'nestedpaging', 'numa', 'buddyalloc', 'gc', 'cheney', 'refcount', 'ownership', 'timingwheel', 'epoll', 'syscall', 'container', 'breakpoint', 'futex', 'rcu', 'aba', 'seqlock', 'iouring', 'bakery', 'mesi', 'falseshare', 'tso'] },
  { label: 'Hardware', icon: '🔌', ids: ['transistor', 'adder', 'latch', 'alu', 'wallace', 'membus', 'cpucache', 'dram', 'memorystory', 'io', 'keystroke', 'ssd', 'flashcell', 'gpu', 'systolic'] },
];

/** The label of the group that contains `id` (or null if ungrouped). */
export function groupOf(id: string): string | null {
  return GROUPS.find((g) => g.ids.includes(id))?.label ?? null;
}
